// apps/creator-next-app/app/(dashboard)/subscriptions/page.tsx
"use client"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Icons } from "@/components/ui/icons"
import { useSubscriptions, useCancelSubscription } from "@/lib/subscription/subscription-hooks"
import { useAuthStore } from "@/lib/auth/auth-store"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import Link from "next/link"

export default function SubscriptionsPage() {
  const { t } = useTranslation()
  const { isAuthenticated } = useAuthStore()
  const { data: subscriptions, isLoading: loading, error } = useSubscriptions()
  const cancelMutation = useCancelSubscription()

  // Simplify hydration logic
  if (typeof window === "undefined") {
    return null
  }

  // Check authentication only after client hydration
  if (!isAuthenticated()) {
    return (
      <div className="container mx-auto max-w-6xl p-6">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Please log in to view your subscriptions
          </h2>
          <Button onClick={() => (window.location.href = "/auth")}>Go to Login</Button>
        </div>
      </div>
    )
  }

  const activeSubscriptions = subscriptions?.filter((sub) => sub.isActive) || []
  const expiredSubscriptions = subscriptions?.filter((sub) => !sub.isActive) || []

  const formatDate = (date: string | Date) => {
    return new Date(date).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })
  }

  const handleCancelSubscription = async (id: string) => {
    cancelMutation.mutate(id, {
      onSuccess: () => {
        toast.success(t("subscriptions.cancelSuccess"))
      },
      onError: () => {
        toast.error(t("subscriptions.cancelError"))
      },
    })
  }

  if (loading) {
    return (
      <div className="container mx-auto max-w-6xl p-6">
        <div className="space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4 animate-pulse"></div>
          <div className="text-center py-12">
            <Icons.spinner className="h-8 w-8 mx-auto animate-spin text-primary-500" />
            <p className="mt-2 text-gray-500 dark:text-gray-200">{t("subscriptions.loading")}</p>
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container mx-auto max-w-6xl p-6">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-red-600 mb-4">Failed to load subscriptions</h2>
          <Button onClick={() => window.location.reload()}>Retry</Button>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto max-w-6xl p-6">
      <div>
        <h1 className="text-2xl font-bold mb-6">{t("subscriptions.title")}</h1>

        {/* Active subscriptions */}
        <div className="mb-8">
          <h2 className="text-lg font-semibold mb-4">{t("subscriptions.activeSubscriptions")}</h2>

          {loading ? (
            <div className="text-center py-12">
              <Icons.spinner className="h-8 w-8 mx-auto animate-spin text-primary-500" />
              <p className="mt-2 text-gray-500 dark:text-gray-200">{t("subscriptions.loading")}</p>
            </div>
          ) : activeSubscriptions.length === 0 ? (
            <Card className="bg-white dark:bg-gray-900 rounded-lg shadow-sm">
              <CardContent className="p-8 text-center">
                <Icons.user className="h-12 w-12 mx-auto text-gray-400" />
                <h3 className="mt-2 text-lg font-medium text-gray-900 dark:text-gray-100">
                  {t("subscriptions.noActiveSubscriptions.title")}
                </h3>
                <p className="mt-1 text-gray-500 dark:text-gray-200">
                  {t("subscriptions.noActiveSubscriptions.description")}
                </p>
                <Link href="/explore">
                  <Button className="mt-4">{t("subscriptions.noActiveSubscriptions.cta")}</Button>
                </Link>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {activeSubscriptions.map((subscription) => (
                <Card key={subscription.id} className="bg-white dark:bg-gray-900 rounded-lg shadow-sm overflow-hidden">
                  <CardContent className="p-6">
                    <div className="flex items-center space-x-4">
                      <div className="h-16 w-16 rounded-full overflow-hidden">
                        <img
                          src={subscription.creator.profileImage || "/placeholder.png"}
                          alt={subscription.creator.displayName}
                          className="h-full w-full object-cover"
                        />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center">
                          <h3 className="text-lg font-semibold truncate">{subscription.creator.displayName}</h3>
                          {subscription.creator.isVerified && <Icons.check className="ml-1 h-4 w-4 text-primary-500" />}
                        </div>
                        <p className="text-sm text-gray-500 dark:text-gray-200">@{subscription.creator.username}</p>
                      </div>
                    </div>

                    <div className="mt-4 space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500 dark:text-gray-200">{t("subscriptions.plan")}</span>
                        <span className="font-medium">
                          {subscription.plan === "monthly" ? t("common.monthly") : t("common.yearly")}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500 dark:text-gray-200">{t("subscriptions.price")}</span>
                        <span className="font-medium">
                          ${subscription.price}/{subscription.plan === "monthly" ? t("common.month") : t("common.year")}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500 dark:text-gray-200">{t("subscriptions.nextBillingDate")}</span>
                        <span className="font-medium">{formatDate(subscription.endDate)}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500 dark:text-gray-200">{t("subscriptions.autoRenew")}</span>
                        <span
                          className={
                            subscription.autoRenew
                              ? "text-green-600 dark:text-green-400"
                              : "text-red-600 dark:text-red-400"
                          }
                        >
                          {subscription.autoRenew ? t("subscriptions.enabled") : t("subscriptions.disabled")}
                        </span>
                      </div>
                    </div>

                    <div className="mt-6 flex space-x-3">
                      <Link href={`/creators/${subscription.creator.username}`} className="flex-1">
                        <Button variant="outline" className="w-full bg-transparent">
                          {t("subscriptions.viewProfile")}
                        </Button>
                      </Link>
                      {subscription.autoRenew && (
                        <Button
                          variant="outline"
                          className="text-red-600 hover:bg-red-50 hover:border-red-600 dark:text-red-400 dark:hover:bg-red-900/20 bg-transparent"
                          onClick={() => handleCancelSubscription(subscription.id)}
                          disabled={cancelMutation.isPending}
                        >
                          {cancelMutation.isPending ? (
                            <Icons.spinner className="h-4 w-4 animate-spin" />
                          ) : (
                            t("subscriptions.cancel")
                          )}
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>

        {/* Expired subscriptions */}
        {expiredSubscriptions.length > 0 && (
          <div>
            <h2 className="text-lg font-semibold mb-4">{t("subscriptions.expiredSubscriptions")}</h2>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {expiredSubscriptions.map((subscription) => (
                <Card
                  key={subscription.id}
                  className="bg-white dark:bg-gray-900 rounded-lg shadow-sm overflow-hidden opacity-75"
                >
                  <CardContent className="p-6">
                    <div className="flex items-center space-x-4">
                      <div className="h-16 w-16 rounded-full overflow-hidden">
                        <img
                          src={subscription.creator.profileImage || "/placeholder.png"}
                          alt={subscription.creator.displayName}
                          className="h-full w-full object-cover grayscale"
                        />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center">
                          <h3 className="text-lg font-semibold truncate">{subscription.creator.displayName}</h3>
                          {subscription.creator.isVerified && <Icons.check className="ml-1 h-4 w-4 text-primary-500" />}
                        </div>
                        <p className="text-sm text-gray-500 dark:text-gray-200">@{subscription.creator.username}</p>
                      </div>
                    </div>

                    <div className="mt-4">
                      <p className="text-sm text-gray-500 dark:text-gray-200">
                        {t("subscriptions.expiredOn")} {formatDate(subscription.endDate)}
                      </p>
                    </div>

                    <div className="mt-6">
                      <Link href={`/creators/${subscription.creator.username}`}>
                        <Button className="w-full">{t("subscriptions.renewSubscription")}</Button>
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// apps/creator/pages/subscriptions/index.vue
<template>
	<div class="container mx-auto max-w-6xl">
		<div>
			<h1 class="text-2xl font-bold mb-6">{{ $t('subscriptions.title') }}</h1>

			<!-- Active subscriptions -->

			<div class="mb-8">
				<h2 class="text-lg font-semibold mb-4">{{ $t('subscriptions.activeSubscriptions') }}</h2>

				<div v-if="loading" class="text-center py-12">
					<Icon name="lucide:loader" class="h-8 w-8 mx-auto animate-spin text-primary-500" />
					<p class="mt-2 text-gray-500 dark:text-gray-200">{{ $t('subscriptions.loading') }}</p>
				</div>

				<div
					v-else-if="activeSubscriptions.length === 0"
					class="bg-white dark:bg-gray-900 rounded-lg shadow-sm p-8 text-center"
				>
					<Icon name="lucide:users" class="h-12 w-12 mx-auto text-gray-400" />
					<h3 class="mt-2 text-lg font-medium text-gray-900">{{ $t('subscriptions.noActiveSubscriptions.title') }}</h3>

					<p class="mt-1 text-gray-500 dark:text-gray-200">
						{{ $t('subscriptions.noActiveSubscriptions.description') }}
					</p>
					<NuxtLink to="/explore" class="btn-primary mt-4"
					>{{ $t('subscriptions.noActiveSubscriptions.cta') }}
					</NuxtLink>
				</div>

				<div v-else class="grid gap-6 md:grid-cols-3">
					<div
						v-for="subscription in activeSubscriptions"
						:key="subscription.id"
						class="bg-white dark:bg-gray-900 rounded-lg shadow-sm overflow-hidden"
					>
						<div class="p-6">
							<div class="flex items-center space-x-4">
								<div class="avatar h-16 w-16">
									<img
										:src="subscription.creator.profileImage"
										:alt="subscription.creator.displayName"
										class="h-full w-full object-cover"
									/>
								</div>

								<div class="flex-1 min-w-0">
									<div class="flex items-center">
										<h3 class="text-lg font-semibold truncate">{{ subscription.creator.displayName }}</h3>
										<span v-if="subscription.creator.isVerified" class="ml-1 text-primary-500">
											<Icon name="lucide:badge-check" class="h-4 w-4" />
										</span>
									</div>

									<p class="text-sm text-gray-500 dark:text-gray-200">@{{ subscription.creator.username }}</p>
								</div>
							</div>

							<div class="mt-4 space-y-2">
								<div class="flex justify-between text-sm">
									<span class="text-gray-500 dark:text-gray-200">{{ $t('subscriptions.plan') }}</span>
									<span class="font-medium">{{
										subscription.plan === 'monthly' ? $t('common.monthly') : $t('common.yearly')
									}}</span>
								</div>

								<div class="flex justify-between text-sm">
									<span class="text-gray-500 dark:text-gray-200">{{ $t('subscriptions.price') }}</span>
									<span class="font-medium"
									>${{ subscription.price }}/{{
										subscription.plan === 'monthly' ? $t('common.month') : $t('common.year')
									}}</span
									>
								</div>

								<div class="flex justify-between text-sm">
									<span class="text-gray-500 dark:text-gray-200">{{ $t('subscriptions.nextBillingDate') }}</span>
									<span class="font-medium">{{ formatDate(subscription.endDate) }}</span>
								</div>

								<div class="flex justify-between text-sm">
									<span class="text-gray-500 dark:text-gray-200">{{ $t('subscriptions.autoRenew') }}</span>
									<span :class="subscription.autoRenew ? 'text-success-600' : 'text-error-600'">
										{{ subscription.autoRenew ? $t('subscriptions.enabled') : $t('subscriptions.disabled') }}
									</span>
								</div>
							</div>

							<div class="mt-6 flex space-x-3">
								<NuxtLink :to="`/creators/${subscription.creator.username}`" class="btn-outline flex-1">
									{{ $t('subscriptions.viewProfile') }}
								</NuxtLink>
								<button
									v-if="subscription.autoRenew"
									class="btn-outline text-error-600 hover:bg-error-50 hover:border-error-600"
									@click="cancelSubscription(subscription.id)"
								>
									{{ $t('subscriptions.cancel') }}
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Expired subscriptions -->

			<div v-if="expiredSubscriptions.length > 0">
				<h2 class="text-lg font-semibold mb-4">{{ $t('subscriptions.expiredSubscriptions') }}</h2>

				<div class="grid gap-6 md:grid-cols-2">
					<div
						v-for="subscription in expiredSubscriptions"
						:key="subscription.id"
						class="bg-white dark:bg-gray-900 rounded-lg shadow-sm overflow-hidden opacity-75"
					>
						<div class="p-6">
							<div class="flex items-center space-x-4">
								<div class="avatar h-16 w-16">
									<img
										:src="subscription.creator.profileImage"
										:alt="subscription.creator.displayName"
										class="h-full w-full object-cover grayscale"
									/>
								</div>

								<div class="flex-1 min-w-0">
									<div class="flex items-center">
										<h3 class="text-lg font-semibold truncate">{{ subscription.creator.displayName }}</h3>
										<span v-if="subscription.creator.isVerified" class="ml-1 text-primary-500">
											<Icon name="lucide:badge-check" class="h-4 w-4" />
										</span>
									</div>

									<p class="text-sm text-gray-500 dark:text-gray-200">@{{ subscription.creator.username }}</p>
								</div>
							</div>

							<div class="mt-4">
								<p class="text-sm text-gray-500 dark:text-gray-200">
									{{ $t('subscriptions.expiredOn') }} {{ formatDate(subscription.endDate) }}
								</p>
							</div>

							<div class="mt-6">
								<NuxtLink :to="`/creators/${subscription.creator.username}`" class="btn-primary w-full">
									{{ $t('subscriptions.renewSubscription') }}
								</NuxtLink>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
// import { useSubscriptionStore } from '~/stores/subscription';

// const { t } = useI18n();

definePageMeta({
	layout: 'creator',
	middleware: ['auth'],
	meta: {
		requiresAuth: true,
	},
});

// const subscriptionStore = useSubscriptionStore();
const loading = ref(true);

// Dummy data for 5 subscriptions
const dummySubscriptions = [
	{
		id: '1',
		isActive: true,
		plan: 'monthly',
		price: 9.99,
		endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
		autoRenew: true,
		creator: {
			displayName: 'Alice Smith',
			username: 'alicesmith',
			profileImage: 'https://randomuser.me/api/portraits/women/1.jpg',
			isVerified: true,
		},
	},
	{
		id: '2',
		isActive: true,
		plan: 'yearly',
		price: 99.99,
		endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
		autoRenew: false,
		creator: {
			displayName: 'Bob Johnson',
			username: 'bobjohnson',
			profileImage: 'https://randomuser.me/api/portraits/men/2.jpg',
			isVerified: false,
		},
	},
	{
		id: '3',
		isActive: true,
		plan: 'monthly',
		price: 9.99,
		endDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
		autoRenew: true,
		creator: {
			displayName: 'Carol Lee',
			username: 'carollee',
			profileImage: 'https://randomuser.me/api/portraits/women/3.jpg',
			isVerified: true,
		},
	},
	{
		id: '4',
		isActive: false,
		plan: 'monthly',
		price: 9.99,
		endDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
		autoRenew: false,
		creator: {
			displayName: 'David Kim',
			username: 'davidkim',
			profileImage: 'https://randomuser.me/api/portraits/men/4.jpg',
			isVerified: false,
		},
	},
	{
		id: '5',
		isActive: false,
		plan: 'yearly',
		price: 99.99,
		endDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
		autoRenew: false,
		creator: {
			displayName: 'Eva Green',
			username: 'evagreen',
			profileImage: 'https://randomuser.me/api/portraits/women/5.jpg',
			isVerified: true,
		},
	},
];

const subscriptions = ref(dummySubscriptions);

onMounted(() => {
	// await subscriptionStore.fetchUserSubscriptions('current-user');
	// loading.value = false;
	loading.value = false;
});

const activeSubscriptions = computed(() => {
	return subscriptions.value.filter((sub) => sub.isActive);
});

const expiredSubscriptions = computed(() => {
	return subscriptions.value.filter((sub) => !sub.isActive);
});

function formatDate(date) {
	return new Date(date).toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
	});
}

function cancelSubscription(id) {
	console.log(id);
	// await subscriptionStore.cancelSubscription(id);
	// Show success message
}
</script>
