// apps/creator-next-app/app/(dashboard)/settings/page.tsx
"use client"

import type React from "react"

import { useState, useRef, useCallback, useMemo } from "react"
import { useTranslation } from "react-i18next"
import { useAuthStore } from "@/lib/auth/auth-store"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { toast } from "sonner"
import { Camera, Loader2, Trash2 } from "lucide-react"

interface ProfileForm {
  displayName: string
  username: string
  bio: string
}

interface EmailForm {
  current: string
  new: string
  password: string
}

interface PasswordForm {
  current: string
  new: string
  confirm: string
}

interface NotificationPreferences {
  newSubscriber: boolean
  newMessage: boolean
  newComment: boolean
  newTip: boolean
  marketing: boolean
  newsletter: boolean
}

interface FormErrors {
  displayName?: string
  username?: string
  bio?: string
  email?: string
  password?: string
  currentPassword?: string
  newPassword?: string
  confirmPassword?: string
}

export default function CreatorSettingsPage() {
  const { t } = useTranslation()
  const { user, setUser } = useAuthStore()
  const fileInputRef = useRef<HTMLInputElement>(null)

  // Loading states
  const [loading, setLoading] = useState(false)
  const [loadingDelete, setLoadingDelete] = useState(false)

  // Profile image
  const [profileImage, setProfileImage] = useState<string>("/placeholder.svg?height=96&width=96&text=Avatar")

  // Form states
  const [profile, setProfile] = useState<ProfileForm>({
    displayName: user?.data?.creatorProfile?.displayName || user?.data?.name || "",
    username: user?.data?.creatorProfile?.username || "",
    bio: user?.data?.creatorProfile?.bio || "",
  })

  const [email, setEmail] = useState<EmailForm>({
    current: user?.data?.email || "",
    new: "",
    password: "",
  })

  const [password, setPassword] = useState<PasswordForm>({
    current: "",
    new: "",
    confirm: "",
  })

  const [notifications, setNotifications] = useState<NotificationPreferences>({
    newSubscriber: true,
    newMessage: true,
    newComment: true,
    newTip: true,
    marketing: false,
    newsletter: true,
  })

  const [errors, setErrors] = useState<FormErrors>({})

  // Computed user initials
  const userInitials = useMemo(() => {
    const name = profile.displayName
    if (!name) return "?"

    const parts = name.split(" ")
    if (parts.length > 1) {
      return `${parts[0][0]}${parts[1][0]}`.toUpperCase()
    }
    return name.substring(0, 2).toUpperCase()
  }, [profile.displayName])

  // Notification labels and descriptions
  const getNotificationLabel = useCallback(
    (key: keyof NotificationPreferences) => {
      const labels = {
        newSubscriber: t("settings.notifications.newSubscriber"),
        newMessage: t("settings.notifications.newMessage"),
        newComment: t("settings.notifications.newComment"),
        newTip: t("settings.notifications.newTip"),
        marketing: t("settings.notifications.marketing"),
        newsletter: t("settings.notifications.newsletter"),
      }
      return labels[key] || key
    },
    [t],
  )

  const getNotificationDescription = useCallback(
    (key: keyof NotificationPreferences) => {
      const descriptions = {
        newSubscriber: t("settings.notifications.newSubscriberDesc"),
        newMessage: t("settings.notifications.newMessageDesc"),
        newComment: t("settings.notifications.newCommentDesc"),
        newTip: t("settings.notifications.newTipDesc"),
        marketing: t("settings.notifications.marketingDesc"),
        newsletter: t("settings.notifications.newsletterDesc"),
      }
      return descriptions[key] || ""
    },
    [t],
  )

  // Handle image upload
  const handleImageUpload = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    // Validate file type
    if (!file.type.startsWith("image/")) {
      toast.error("Please select a valid image file")
      return
    }

    // Validate file size (5MB max)
    if (file.size > 5 * 1024 * 1024) {
      toast.error("Image size must be less than 5MB")
      return
    }

    const imageUrl = URL.createObjectURL(file)
    setProfileImage(imageUrl)
    toast.success("Profile image updated successfully")
  }, [])

  // Form handlers
  const updateProfile = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setLoading(true)
      setErrors({})

      try {
        // Validation
        const newErrors: FormErrors = {}
        if (!profile.displayName.trim()) {
          newErrors.displayName = "Display name is required"
        }
        if (!profile.username.trim()) {
          newErrors.username = "Username is required"
        }

        if (Object.keys(newErrors).length > 0) {
          setErrors(newErrors)
          return
        }

        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1000))

        toast.success("Profile updated successfully")
      } catch (error) {
        toast.error("Failed to update profile")
      } finally {
        setLoading(false)
      }
    },
    [profile],
  )

  const updateEmail = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setLoading(true)
      setErrors({})

      try {
        // Validation
        const newErrors: FormErrors = {}
        if (!email.new.trim()) {
          newErrors.email = "New email is required"
        }
        if (!email.password.trim()) {
          newErrors.password = "Password is required"
        }

        if (Object.keys(newErrors).length > 0) {
          setErrors(newErrors)
          return
        }

        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1000))

        toast.success("Email updated successfully")
        setEmail((prev) => ({
          current: prev.new,
          new: "",
          password: "",
        }))
      } catch (error) {
        toast.error("Failed to update email")
      } finally {
        setLoading(false)
      }
    },
    [email],
  )

  const updatePassword = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setLoading(true)
      setErrors({})

      try {
        // Validation
        const newErrors: FormErrors = {}
        if (!password.current.trim()) {
          newErrors.currentPassword = "Current password is required"
        }
        if (!password.new.trim()) {
          newErrors.newPassword = "New password is required"
        }
        if (password.new !== password.confirm) {
          newErrors.confirmPassword = "Passwords do not match"
        }

        if (Object.keys(newErrors).length > 0) {
          setErrors(newErrors)
          return
        }

        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1000))

        toast.success("Password updated successfully")
        setPassword({ current: "", new: "", confirm: "" })
      } catch (error) {
        toast.error("Failed to update password")
      } finally {
        setLoading(false)
      }
    },
    [password],
  )

  const updateNotifications = useCallback(async () => {
    setLoading(true)

    try {
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 1000))

      toast.success("Notification preferences saved")
    } catch (error) {
      toast.error("Failed to save preferences")
    } finally {
      setLoading(false)
    }
  }, [notifications])

  const confirmDeleteAccount = useCallback(async () => {
    if (!confirm("Are you sure you want to delete your account? This action cannot be undone.")) {
      return
    }

    setLoadingDelete(true)

    try {
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 2000))

      toast.success("Account deleted successfully")
      // In real app, would redirect to login
    } catch (error) {
      toast.error("Failed to delete account")
    } finally {
      setLoadingDelete(false)
    }
  }, [])

  return (
    <div className="p-6">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{t("settings.title")}</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Manage your account settings and preferences</p>
      </div>

      <div className="space-y-6">
        {/* Profile Settings */}
        <Card className="bg-white dark:bg-gray-900">
          <CardHeader>
            <CardTitle>{t("settings.profile.title")}</CardTitle>
            <CardDescription>Update your profile information and avatar</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Avatar Section */}
            <div className="flex items-center space-x-6">
              <div className="relative">
                <Avatar className="h-24 w-24">
                  <AvatarImage src={profileImage || "/placeholder.svg"} alt="Profile" />
                  <AvatarFallback className="text-xl font-medium">{userInitials}</AvatarFallback>
                </Avatar>
                <Button
                  size="sm"
                  variant="outline"
                  className="absolute bottom-0 right-0 rounded-full p-2 h-8 w-8 bg-transparent"
                  onClick={() => fileInputRef.current?.click()}
                >
                  <Camera className="h-4 w-4" />
                </Button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={handleImageUpload}
                />
              </div>
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Click the camera icon to update your profile picture
                </p>
                <p className="text-xs text-gray-400 mt-1">JPG, PNG or GIF. Max size 5MB.</p>
              </div>
            </div>

            {/* Profile Form */}
            <form onSubmit={updateProfile} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="displayName">Display Name *</Label>
                  <Input
                    id="displayName"
                    value={profile.displayName}
                    onChange={(e) => setProfile((prev) => ({ ...prev, displayName: e.target.value }))}
                    className={errors.displayName ? "border-red-500" : ""}
                  />
                  {errors.displayName && <p className="text-sm text-red-500">{errors.displayName}</p>}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="username">Username *</Label>
                  <Input
                    id="username"
                    value={profile.username}
                    onChange={(e) => setProfile((prev) => ({ ...prev, username: e.target.value }))}
                    className={errors.username ? "border-red-500" : ""}
                  />
                  {errors.username && <p className="text-sm text-red-500">{errors.username}</p>}
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="bio">Bio</Label>
                <Textarea
                  id="bio"
                  rows={3}
                  value={profile.bio}
                  onChange={(e) => setProfile((prev) => ({ ...prev, bio: e.target.value }))}
                  className={errors.bio ? "border-red-500" : ""}
                />
                {errors.bio && <p className="text-sm text-red-500">{errors.bio}</p>}
              </div>

              <Button type="submit" disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Update Profile
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Email Settings */}
        <Card className="bg-white dark:bg-gray-900">
          <CardHeader>
            <CardTitle>{t("settings.email.title")}</CardTitle>
            <CardDescription>Change your email address</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={updateEmail} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="currentEmail">Current Email</Label>
                <Input id="currentEmail" type="email" value={email.current} disabled />
              </div>

              <div className="space-y-2">
                <Label htmlFor="newEmail">New Email *</Label>
                <Input
                  id="newEmail"
                  type="email"
                  value={email.new}
                  onChange={(e) => setEmail((prev) => ({ ...prev, new: e.target.value }))}
                  className={errors.email ? "border-red-500" : ""}
                />
                {errors.email && <p className="text-sm text-red-500">{errors.email}</p>}
              </div>

              <div className="space-y-2">
                <Label htmlFor="emailPassword">Current Password *</Label>
                <Input
                  id="emailPassword"
                  type="password"
                  value={email.password}
                  onChange={(e) => setEmail((prev) => ({ ...prev, password: e.target.value }))}
                  className={errors.password ? "border-red-500" : ""}
                />
                {errors.password && <p className="text-sm text-red-500">{errors.password}</p>}
              </div>

              <Button type="submit" disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Update Email
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Password Settings */}
        <Card className="bg-white dark:bg-gray-900">
          <CardHeader>
            <CardTitle>{t("settings.password.title")}</CardTitle>
            <CardDescription>Change your password</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={updatePassword} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="currentPassword">Current Password *</Label>
                <Input
                  id="currentPassword"
                  type="password"
                  value={password.current}
                  onChange={(e) => setPassword((prev) => ({ ...prev, current: e.target.value }))}
                  className={errors.currentPassword ? "border-red-500" : ""}
                />
                {errors.currentPassword && <p className="text-sm text-red-500">{errors.currentPassword}</p>}
              </div>

              <div className="space-y-2">
                <Label htmlFor="newPassword">New Password *</Label>
                <Input
                  id="newPassword"
                  type="password"
                  value={password.new}
                  onChange={(e) => setPassword((prev) => ({ ...prev, new: e.target.value }))}
                  className={errors.newPassword ? "border-red-500" : ""}
                />
                {errors.newPassword && <p className="text-sm text-red-500">{errors.newPassword}</p>}
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm New Password *</Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  value={password.confirm}
                  onChange={(e) => setPassword((prev) => ({ ...prev, confirm: e.target.value }))}
                  className={errors.confirmPassword ? "border-red-500" : ""}
                />
                {errors.confirmPassword && <p className="text-sm text-red-500">{errors.confirmPassword}</p>}
              </div>

              <Button type="submit" disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Update Password
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Notification Settings */}
        <Card className="bg-white dark:bg-gray-900">
          <CardHeader>
            <CardTitle>{t("settings.notifications.title")}</CardTitle>
            <CardDescription>Manage your notification preferences</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {Object.entries(notifications).map(([key, value]) => (
              <div key={key} className="flex items-start space-x-3">
                <Checkbox
                  id={key}
                  checked={value}
                  onCheckedChange={(checked) =>
                    setNotifications((prev) => ({
                      ...prev,
                      [key]: checked === true,
                    }))
                  }
                />
                <div className="space-y-1">
                  <Label htmlFor={key} className="text-sm font-medium">
                    {getNotificationLabel(key as keyof NotificationPreferences)}
                  </Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {getNotificationDescription(key as keyof NotificationPreferences)}
                  </p>
                </div>
              </div>
            ))}

            <div className="border-t pt-4 mt-6">
              <Button onClick={updateNotifications} disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Save Preferences
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Delete Account */}
        <Card className="border-red-200 dark:border-red-800 bg-white dark:bg-gray-900">
          <CardHeader>
            <CardTitle className="text-red-600 dark:text-red-400">{t("settings.deleteAccount.title")}</CardTitle>
            <CardDescription>{t("settings.deleteAccount.description")}</CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="destructive" onClick={confirmDeleteAccount} disabled={loadingDelete}>
              {loadingDelete ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Deleting...
                </>
              ) : (
                <>
                  <Trash2 className="mr-2 h-4 w-4" />
                  Delete Account
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// apps/creator/pages/settings/index.vue
<template>
	<div class="container mx-auto max-w-6xl">
		<div>
			<h1 class="text-2xl font-bold mb-6">{{ $t('settings.title') }}</h1>

			<div class="bg-white dark:bg-gray-900 rounded-lg shadow-sm divide-y divide-gray-200">
				<div class="p-6">
					<h2 class="text-lg font-medium mb-4">{{ $t('settings.profile.title') }}</h2>

					<div class="flex items-center space-x-6 mb-6">
						<div class="relative">
							<div class="avatar h-24 w-24">
								<img v-if="profileImage" :src="profileImage" alt="Profile" class="h-full w-full object-cover" />
								<div
									v-else
									class="h-full w-full flex items-center justify-center bg-primary-100 text-primary-600 text-xl font-medium"
								>
									{{ userInitials }}
								</div>
							</div>
							<button
								class="absolute bottom-0 right-0 bg-white dark:bg-gray-900 rounded-full p-1.5 shadow-sm border border-gray-200 text-gray-500 dark:text-gray-200 hover:text-gray-700"
								@click="$refs.imageInput.click()"
							>
								<Icon name="lucide:camera" class="h-4 w-4" />
							</button>
							<input ref="imageInput" type="file" accept="image/*" class="hidden" @change="handleImageUpload" />
						</div>

						<div>
							<p class="text-sm text-gray-500 dark:text-gray-200">
								{{ $t('settings.profile.pictureUpdated') }}
							</p>
						</div>
					</div>

					<form class="space-y-4" @submit.prevent="updateProfile">
						<FormInput v-model="profile.displayName" label="Display Name" :error="errors.displayName" required />

						<FormInput v-model="profile.username" label="Username" :error="errors.username" required />

						<div>
							<label class="form-label">{{ $t('settings.profile.bio') }}</label>
							<textarea
								v-model="profile.bio"
								rows="3"
								class="form-input"
								:class="errors.bio ? 'border-error-300 focus:border-error-500 focus:ring-error-500' : ''"
							/>

							<p v-if="errors.bio" class="form-error">{{ errors.bio }}</p>
						</div>

						<div class="pt-4">
							<button type="submit" class="btn-primary" :disabled="loading">
								<Icon v-if="loading" name="lucide:loader-2" class="animate-spin h-5 w-5 mr-2" />
								{{ $t('settings.profile.updateProfile') }}
							</button>
						</div>
					</form>
				</div>

				<div class="p-6">
					<h2 class="text-lg font-medium mb-4">{{ $t('settings.email.title') }}</h2>

					<form class="space-y-4" @submit.prevent="updateEmail">
						<FormInput v-model="email.current" label="Current Email" type="email" disabled />

						<FormInput v-model="email.new" label="New Email" type="email" :error="errors.email" required />

						<FormInput
							v-model="email.password"
							label="Current Password"
							type="password"
							:error="errors.password"
							required
						/>

						<div class="pt-4">
							<button type="submit" class="btn-primary" :disabled="loading">
								<Icon v-if="loading" name="lucide:loader-2" class="animate-spin h-5 w-5 mr-2" />
								{{ $t('settings.email.updateEmail') }}
							</button>
						</div>
					</form>
				</div>

				<div class="p-6">
					<h2 class="text-lg font-medium mb-4">{{ $t('settings.password.title') }}</h2>

					<form class="space-y-4" @submit.prevent="updatePassword">
						<FormInput
							v-model="password.current"
							label="Current Password"
							type="password"
							:error="errors.currentPassword"
							required
						/>

						<FormInput
							v-model="password.new"
							label="New Password"
							type="password"
							:error="errors.newPassword"
							required
						/>

						<FormInput
							v-model="password.confirm"
							label="Confirm New Password"
							type="password"
							:error="errors.confirmPassword"
							required
						/>

						<div class="pt-4">
							<button type="submit" class="btn-primary" :disabled="loading">
								<Icon v-if="loading" name="lucide:loader-2" class="animate-spin h-5 w-5 mr-2" />
								{{ $t('settings.password.updatePassword') }}
							</button>
						</div>
					</form>
				</div>

				<div class="p-6">
					<h2 class="text-lg font-medium mb-4">{{ $t('settings.notifications.title') }}</h2>

					<div class="space-y-4">
						<div v-for="(pref, key) in notifications" :key="key" class="flex items-start">
							<div class="flex items-center h-5">
								<input
									:id="key"
									v-model="notifications[key]"
									type="checkbox"
									class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
								/>
							</div>

							<div class="ml-3 text-sm">
								<label :for="key" class="font-medium text-gray-700">{{ getNotificationLabel(key) }}</label>
								<p class="text-gray-500 dark:text-gray-200">{{ getNotificationDescription(key) }}</p>
							</div>
						</div>

						<div class="pt-4">
							<button class="btn-primary" :disabled="loading" @click="updateNotifications">
								<Icon v-if="loading" name="lucide:loader-2" class="animate-spin h-5 w-5 mr-2" />
								{{ $t('settings.notifications.savePreferences') }}
							</button>
						</div>
					</div>
				</div>

				<div class="p-6">
					<h2 class="text-lg font-medium text-error-600 mb-4">{{ $t('settings.deleteAccount.title') }}</h2>

					<p class="text-sm text-gray-500 dark:text-gray-200 mb-4">
						{{ $t('settings.deleteAccount.description') }}
					</p>

					<button class="btn-outline border-error-300 text-error-700 hover:bg-error-50" @click="confirmDeleteAccount" :disabled="loadingDelete">
						<Icon v-if="loadingDelete" name="lucide:loader-2" class="animate-spin h-5 w-5 mr-2" />
						<span v-if="loadingDelete">{{ t('deleting') }}</span>
						<span v-else>{{ $t('settings.deleteAccount.deleteAccount') }}</span>
					</button>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { toast } from 'vue3-toastify';
import { useI18n } from 'vue-i18n';
import { useUserStore } from '~/store/user';
import { useAuthStore } from '~/store/auth';
import FormInput from '@/components/ui/BaseInput.vue';

const { t } = useI18n();

definePageMeta({
	middleware: ['auth'],
	layout: 'creator',
});

const userStore = useUserStore();
const authStore = useAuthStore();

const loading = ref(false);
const loadingDelete = ref(false);
const profileImage = ref(userStore.user?.profileImage || '');
const errors = ref({});

const profile = ref({
	displayName: userStore.user?.displayName || '',
	username: '',
	bio: '',
});

const email = ref({
	current: userStore.user?.email || '',
	new: '',
	password: '',
});

const password = ref({
	current: '',
	new: '',
	confirm: '',
});

const notifications = ref({
	newSubscriber: true,
	newMessage: true,
	newComment: true,
	newTip: true,
	marketing: false,
	newsletter: true,
});

const userInitials = computed(() => {
	const name = profile.value.displayName;
	if (!name) {
		return '?';
	}

	const parts = name.split(' ');
	if (parts.length > 1) {
		return `${parts[0][0]}${parts[1][0]}`.toUpperCase();
	}
	return name.substring(0, 2).toUpperCase();
});

function getNotificationLabel(key) {
	const labels = {
		newSubscriber: t('settings.notifications.newSubscriber'),
		newMessage: t('settings.notifications.newMessage'),
		newComment: t('settings.notifications.newComment'),
		newTip: t('settings.notifications.newTip'),
		marketing: t('settings.notifications.marketing'),
		newsletter: t('settings.notifications.newsletter'),
	};
	return labels[key] || key;
}

function getNotificationDescription(key) {
	const descriptions = {
		newSubscriber: t('settings.notifications.newSubscriberDesc'),
		newMessage: t('settings.notifications.newMessageDesc'),
		newComment: t('settings.notifications.newCommentDesc'),
		newTip: t('settings.notifications.newTipDesc'),
		marketing: t('settings.notifications.marketingDesc'),
		newsletter: t('settings.notifications.newsletterDesc'),
	};
	return descriptions[key] || '';
}

function handleImageUpload(event) {
	const file = event.target.files[0];
	if (!file) {
		return;
	}

	profileImage.value = URL.createObjectURL(file);
	toast.success('Profile picture updated');
}

function updateProfile() {
	loading.value = true;
	errors.value = {};

	try {
		if (!profile.value.displayName) {
			errors.value.displayName = 'Display name is required';
			return;
		}

		toast.success('Profile updated successfully');
	} catch {
		toast.error('Failed to update profile');
	} finally {
		loading.value = false;
	}
}

function updateEmail() {
	loading.value = true;
	errors.value = {};

	try {
		if (!email.value.new) {
			errors.value.email = 'New email is required';
			return;
		}
		if (!email.value.password) {
			errors.value.password = 'Password is required';
			return;
		}

		toast.success('Email updated successfully');
		email.value.current = email.value.new;
		email.value.new = '';
		email.value.password = '';
	} catch {
		toast.error('Failed to update email');
	} finally {
		loading.value = false;
	}
}

function updatePassword() {
	loading.value = true;
	errors.value = {};

	try {
		if (!password.value.current) {
			errors.value.currentPassword = 'Current password is required';
			return;
		}
		if (!password.value.new) {
			errors.value.newPassword = 'New password is required';
			return;
		}
		if (password.value.new !== password.value.confirm) {
			errors.value.confirmPassword = 'Passwords do not match';
			return;
		}

		toast.success('Password updated successfully');
		password.value = { current: '', new: '', confirm: '' };
	} catch {
		toast.error('Failed to update password');
	} finally {
		loading.value = false;
	}
}

function updateNotifications() {
	loading.value = true;

	try {
		toast.success('Notification preferences updated');
	} catch (error) {
		toast.error('Failed to update notification preferences');
	} finally {
		loading.value = false;
	}
}

async function confirmDeleteAccount() {
	if (confirm('Are you sure you want to delete your account? This action cannot be undone.')) {
		loadingDelete.value = true;
		try {
			// Simulate API call
			await new Promise(resolve => setTimeout(resolve, 1000));
			toast.success('Account deleted successfully');
			authStore.logout();
			navigateTo('/');
		} finally {
			loadingDelete.value = false;
		}
	}
}

onMounted(() => {
	try {
		profile.value.displayName = 'John Doe';
		profile.value.username = 'johndoe';
		profile.value.bio = 'Content creator and digital artist';
		profileImage.value = '/images/default-avatar.png';
	} catch (error) {
		console.log('Error loading profile:', error);
	}
});
</script>
