// apps/creator-next-app/components/CreatorSidebar.tsx
"use client"

import { useMemo } from "react"
import { useTranslation } from "react-i18next"
import { X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useAuthStore } from "@/lib/auth-store"
import SidebarNavigationItem from "@/components/sidebar-navigation-item"
import Image from "next/image"

interface NavigationItem {
  name: string
  href: string
  icon: string
  divider?: boolean
}

interface CreatorSidebarProps {
  isMobileOpen: boolean
  onClose: () => void
}

export default function CreatorSidebar({ isMobileOpen, onClose }: CreatorSidebarProps) {
  const { t } = useTranslation("navigation")
  const { profile } = useAuthStore()

  const navigationItems = useMemo(() => {
    const creatorStatus = profile?.isCreator
    const isApprovedCreator = creatorStatus === true

    // Base navigation items that everyone sees
    const baseItems: NavigationItem[] = [
      { name: t("nav.home"), href: "/", icon: "home" },
      { name: t("nav.messages"), href: "/messages", icon: "message-circle" },
      { name: t("nav.wallet"), href: "/wallet", icon: "wallet" },
      { name: t("nav.subscriptions"), href: "/subscriptions", icon: "credit-card" },
      { name: t("nav.content"), href: "/content", icon: "image" },
    ]

    // Creator-specific navigation items
    const creatorItems: NavigationItem[] = isApprovedCreator
      ? [
          { name: t("nav.analytics"), href: "/creator/analytics", icon: "bar-chart" },
          { name: t("nav.subscribers"), href: "/creator/subscribers", icon: "users" },
          { name: t("nav.earnings"), href: "/creator/earnings", icon: "dollar-sign" },
        ]
      : []

    // "Become Creator" button (only shown if not approved)
    const becomeCreatorItem: NavigationItem[] = !isApprovedCreator
      ? [
          {
            name: t("nav.becomeCreator"),
            href: "/apply",
            icon: "user-plus",
            divider: true,
          },
        ]
      : []

    return [...baseItems, ...creatorItems, ...becomeCreatorItem]
  }, [profile?.isCreator, t])

  return (
    <div>
      {/* Mobile Sidebar */}
      {isMobileOpen && (
        <div className="fixed inset-0 lg:hidden z-[400]" role="dialog" aria-modal="true">
          <div
            className="fixed inset-0 bg-gray-600 bg-opacity-75 dark:bg-gray-900 dark:bg-opacity-80"
            onClick={onClose}
          />

          <div className="fixed inset-y-0 left-0 flex max-w-xs w-full bg-white dark:bg-gray-800 shadow-lg">
            <div className="flex flex-col w-full">
              <div className="px-4 py-6 bg-primary-700 dark:bg-primary-900 sm:px-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <Image src="/logo-white.svg" alt="Whispers" width={32} height={32} className="h-8 w-auto" />
                    <span className="text-xl font-bold text-white dark:text-gray-100">{t("nav.creatorStudio")}</span>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-white hover:text-gray-200 dark:text-gray-100 dark:hover:text-gray-200"
                    onClick={onClose}
                  >
                    <span className="sr-only">{t("common.close")}</span>
                    <X className="h-6 w-6" />
                  </Button>
                </div>
              </div>

              <div className="flex-1 px-2 py-4 space-y-1 overflow-y-auto">
                {navigationItems.map((item) => (
                  <SidebarNavigationItem key={item.name} item={item} onClick={onClose} />
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Desktop Sidebar */}
      <div className="sticky bottom-0 top-0 hidden lg:flex lg:flex-shrink-0 bg-white dark:bg-gray-800 h-screen">
        <div className="flex flex-col w-64">
          <div className="flex flex-col h-0 flex-1">
            <div className="px-4 py-6 bg-primary-700 dark:bg-primary-900 flex items-center">
              <div className="flex items-center space-x-2">
                <Image src="/logo-white.svg" alt="Whispers" width={32} height={32} className="h-8 w-auto" />
                <span className="text-xl font-bold text-white dark:text-gray-100">{t("creatorStudio")}</span>
              </div>
            </div>

            <div className="flex-1 flex flex-col overflow-y-auto">
              <nav className="flex-1 px-2 py-4 space-y-1">
                {navigationItems.map((item) => (
                  <SidebarNavigationItem key={item.name} item={item} />
                ))}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// apps/admin/components/CreatorSidebar.vue
<template>
	<div>
		<!-- Mobile sidebar -->

		<div v-if="isMobileOpen" class="fixed inset-0 z-40 lg:hidden" role="dialog" aria-modal="true">
			<!-- Background overlay -->

			<div class="fixed inset-0 bg-gray-600 bg-opacity-75" @click="$emit('close')" />

			<!-- Sidebar panel -->

			<div class="fixed inset-y-0 left-0 flex max-w-xs w-full bg-white shadow-lg">
				<div class="flex flex-col w-full">
					<div class="px-4 py-6 bg-primary-700 sm:px-6">
						<div class="flex items-center justify-between">
							<div class="flex items-center space-x-2">
								<img src="/logo-white.svg" alt="Whispers" class="h-8 w-auto" />
								<span class="text-xl font-bold text-white">Creator Studio</span>
							</div>
							<button type="button" class="text-white hover:text-gray-200" @click="$emit('close')">
								<span class="sr-only">Close sidebar</span> <Icon name="lucide:x" class="h-6 w-6" />
							</button>
						</div>
					</div>

					<div class="flex-1 px-2 py-4 space-y-1 overflow-y-auto">
						<SidebarNavigationItem
							v-for="item in navigationItems"
							:key="item.name"
							:item="item"
							@click="$emit('close')"
						/>
					</div>
				</div>
			</div>
		</div>

		<!-- Desktop sidebar -->

		<div class="hidden lg:flex lg:flex-shrink-0">
			<div class="flex flex-col w-64">
				<div class="flex flex-col h-0 flex-1">
					<div class="px-4 py-6 bg-primary-700 flex items-center">
						<div class="flex items-center space-x-2">
							<img src="/logo-white.svg" alt="Whispers" class="h-8 w-auto" />
							<span class="text-xl font-bold text-white">Creator Studio</span>
						</div>
					</div>

					<div class="flex-1 flex flex-col overflow-y-auto">
						<nav class="flex-1 px-2 py-4 space-y-1">
							<SidebarNavigationItem v-for="item in navigationItems" :key="item.name" :item="item" />
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup>
defineProps({
	isMobileOpen: {
		type: Boolean,
		default: false,
	},
})

defineEmits(['close'])

const navigationItems = [
	{
		name: 'Dashboard',
		href: '/creator/dashboard',
		icon: 'lucide:layout-dashboard',
	},
	{ name: 'Content', href: '/creator/content', icon: 'lucide:image' },
	{ name: 'Posts', href: '/creator/posts', icon: 'lucide:file-text' },
	{
		name: 'Messages',
		href: '/creator/messages',
		icon: 'lucide:message-circle',
	},
	{ name: 'Subscribers', href: '/creator/subscribers', icon: 'lucide:users' },
	{ name: 'Earnings', href: '/creator/earnings', icon: 'lucide:dollar-sign' },
	{ name: 'Settings', href: '/creator/settings', icon: 'lucide:settings' },
	{
		name: 'View Profile',
		href: '/profile',
		icon: 'lucide:external-link',
		divider: true,
	},
]
</script>
