// apps/creator-next-app/components/home/post-card.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { useTranslation } from "react-i18next"
import Image from "next/image"
import Link from "next/link"
import { Heart, MessageCircle, Send, Coins, Bookmark, MoreVertical } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import type { Post } from "@/types/dashboard"
import { cn } from "@/lib/utils"
import MediaPreviewModal from "./media-preview-modal"

interface PostCardProps {
  post: Post
  isSubscribed: boolean
  onSubscribe: (creatorId: string) => void
  onTip: (post: Post) => void
  onAddComment?: (postId: string, comment: string) => void
}

interface MediaItem {
  url: string
  type: "image" | "video"
}

interface Message {
  text: string
  timestamp: Date
  user: {
    name: string
    avatar: string
  }
  isCurrentUser: boolean
}

export default function PostCard({ post, isSubscribed, onSubscribe, onTip, onAddComment }: PostCardProps) {
  const { t } = useTranslation()
  const [isLiked, setIsLiked] = useState(false)
  const [likesCount, setLikesCount] = useState(post.likes)
  const [showModal, setShowModal] = useState(false)
  const [quickComment, setQuickComment] = useState("")
  const [localComments, setLocalComments] = useState<string[]>([])
  const [currentMediaIndex, setCurrentMediaIndex] = useState(0)

  // Mock current user - replace with actual user data
  const currentUser = {
    name: "YourUsername",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  }

  const formatNumber = (num: number): string => {
    return new Intl.NumberFormat("en-US").format(num)
  }

  const formatTimeAgo = (date: Date): string => {
    const now = new Date()
    const diffInSeconds = Math.floor((now.getTime() - new Date(date).getTime()) / 1000)

    if (diffInSeconds < 60) {
      return t("secondsAgo", { count: diffInSeconds }) || `${diffInSeconds}s ago`
    }
    if (diffInSeconds < 3600) {
      return t("minutesAgo", { count: Math.floor(diffInSeconds / 60) }) || `${Math.floor(diffInSeconds / 60)}m ago`
    }
    if (diffInSeconds < 86400) {
      return t("hoursAgo", { count: Math.floor(diffInSeconds / 3600) }) || `${Math.floor(diffInSeconds / 3600)}h ago`
    }
    return t("daysAgo", { count: Math.floor(diffInSeconds / 86400) }) || `${Math.floor(diffInSeconds / 86400)}d ago`
  }

  const handleLike = () => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    setIsLiked(!isLiked)
    setLikesCount((prev) => (isLiked ? prev - 1 : prev + 1))
  }

  const handleComment = () => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    openModal(0, true)
  }

  const handleShare = () => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    // Implement share functionality
  }

  const handleTip = () => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    onTip(post)
  }

  const handleBookmark = () => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    // Implement bookmark functionality
  }

  const openModal = (index = 0, withComments = false) => {
    if (post.isPremium && !isSubscribed) {
      onSubscribe(post.creator.id)
      return
    }
    setCurrentMediaIndex(index)
    setShowModal(true)
  }

  const closeModal = () => {
    setShowModal(false)
  }

  const addComment = () => {
    if (!quickComment.trim()) return

    setLocalComments((prev) => [...prev, quickComment])
    onAddComment?.(post.id, quickComment)
    setQuickComment("")
  }

  const handleNewComment = (comment: string) => {
    setLocalComments((prev) => [...prev, comment])
    onAddComment?.(post.id, comment)
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      addComment()
    }
  }

  // Format media items for the modal
  const mediaItemsForModal: MediaItem[] = [
    {
      url: post.image || "",
      type: "image",
    },
  ]

  // Combine post comments and local comments for modal
  const allCommentsForModal: Message[] = [
    // Caption as first message
    {
      text: post.content,
      timestamp: post.createdAt,
      user: {
        name: post.creator.name,
        avatar: post.creator.avatar,
      },
      isCurrentUser: false,
    },
    // Post comments
    ...post.comments.map((comment: any) => ({
      text: comment.content,
      timestamp: comment.createdAt,
      user: {
        name: comment.user.name,
        avatar: comment.user.avatar,
      },
      isCurrentUser: false,
    })),
    // Local comments
    ...localComments.map((comment) => ({
      text: comment,
      timestamp: new Date(),
      user: {
        name: currentUser.name,
        avatar: currentUser.avatar,
      },
      isCurrentUser: true,
    })),
  ]

  return (
    <>
      <div className="bg-white dark:bg-gray-900 rounded-xl shadow-md border border-gray-100 dark:border-gray-800 mb-8 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3">
          <div className="flex items-center">
            <Link href="/@user" className="flex-shrink-0">
              <Image
                src={post.creator.avatar || "/placeholder.svg"}
                alt={post.creator.name}
                width={32}
                height={32}
                className="w-8 h-8 rounded-full object-cover border border-gray-200 dark:border-gray-700"
              />
            </Link>

            <div className="ml-3">
              <Link href="/@user">
                <h3 className="font-semibold text-sm text-gray-900 dark:text-white hover:underline">
                  {post.creator.name}
                </h3>
              </Link>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                {(post as any).location || t("unknownLocation") || "Unknown location"}
              </p>
            </div>
          </div>

          <button className="text-gray-500 dark:text-gray-400">
            <MoreVertical className="w-5 h-5" />
          </button>
        </div>

        {/* Media Content */}
        <div className="relative aspect-video w-full bg-gray-100 dark:bg-gray-800 overflow-hidden">
          {post.isPremium && !isSubscribed ? (
            <>
              <div className="absolute inset-0 z-10 flex flex-col justify-center items-center bg-white/70 dark:bg-gray-900/70">
                <Button
                  onClick={() => onSubscribe(post.creator.id)}
                  className="max-w-md rounded-full bg-gradient-to-r from-primary-600 to-primary-700 hover:from-primary-700 hover:to-primary-800 text-white font-semibold py-4 px-6 text-lg transition-all"
                >
                  {t("subscribe") || "Subscribe"}
                </Button>
              </div>

              <div className="absolute inset-0 w-full h-full filter blur-sm pointer-events-none select-none">
                <Image src={post.image || "/placeholder.svg"} alt="Post content" fill className="object-cover" />
              </div>
            </>
          ) : (
            <div className="absolute inset-0 w-full h-full cursor-pointer" onClick={() => openModal(0)}>
              <Image src={post.image || "/placeholder.svg"} alt="Post content" fill className="object-cover" />
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="px-4 py-3">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center space-x-4">
              <button
                disabled={post.isPremium && !isSubscribed}
                className={cn(
                  post.isPremium && !isSubscribed ? "opacity-50 cursor-not-allowed" : "",
                  "text-gray-900 dark:text-white",
                )}
                onClick={handleLike}
                title={isLiked ? t("home.unlike") || "Unlike" : t("home.like") || "Like"}
              >
                <Heart className={cn("w-6 h-6", isLiked && "fill-red-500 text-red-500")} />
              </button>

              <button
                disabled={post.isPremium && !isSubscribed}
                className={cn(
                  post.isPremium && !isSubscribed ? "opacity-50 cursor-not-allowed" : "",
                  "text-gray-900 dark:text-white",
                )}
                onClick={handleComment}
                title={t("home.comment") || "Comment"}
              >
                <MessageCircle className="w-6 h-6" />
              </button>

              <button
                disabled={post.isPremium && !isSubscribed}
                className={cn(
                  post.isPremium && !isSubscribed ? "opacity-50 cursor-not-allowed" : "",
                  "text-gray-900 dark:text-white",
                )}
                onClick={handleShare}
                title={t("home.share") || "Share"}
              >
                <Send className="w-6 h-6" />
              </button>

              <button
                disabled={post.isPremium && !isSubscribed}
                className={cn(
                  post.isPremium && !isSubscribed ? "opacity-50 cursor-not-allowed" : "",
                  "text-gray-900 dark:text-white",
                )}
                onClick={handleTip}
                title={t("home.tipCreator") || "Tip Creator"}
              >
                <Coins className="w-6 h-6" />
              </button>
            </div>

            <button
              disabled={post.isPremium && !isSubscribed}
              className={cn(
                post.isPremium && !isSubscribed ? "opacity-50 cursor-not-allowed" : "",
                "text-gray-900 dark:text-white",
              )}
              onClick={handleBookmark}
              title={t("home.save") || "Save"}
            >
              <Bookmark className="w-6 h-6" />
            </button>
          </div>

          <p className="text-sm font-semibold text-gray-900 dark:text-white mb-1">
            {formatNumber(likesCount)} {t("likes") || "likes"}
          </p>

          <p className="text-sm text-gray-900 dark:text-white mb-1">
            <span className="font-semibold">{post.creator.name}</span> {post.content}
          </p>

          {(post.comments.length > 0 || localComments.length > 0) && !(post.isPremium && !isSubscribed) && (
            <button className="text-sm text-gray-500 dark:text-gray-400 mb-1" onClick={() => openModal(0, true)}>
              {t("viewAllComments", { count: post.comments.length + localComments.length }) ||
                `View all ${post.comments.length + localComments.length} comments`}
            </button>
          )}

          {!(post.isPremium && !isSubscribed) && (
            <div>
              {localComments.map((comment, index) => (
                <div key={`local-${index}`} className="mb-1">
                  <p className="text-sm text-gray-900 dark:text-white">
                    <span className="font-semibold">{currentUser.name}</span> {comment}
                  </p>
                </div>
              ))}
            </div>
          )}

          <p className="text-xs text-gray-400 dark:text-gray-500 uppercase mt-2">{formatTimeAgo(post.createdAt)}</p>
        </div>

        {/* Comment Input */}
        {!(post.isPremium && !isSubscribed) && (
          <div className="px-4 py-3 border-t border-gray-100 dark:border-gray-800 flex items-center">
            <Input
              value={quickComment}
              onChange={(e) => setQuickComment(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder={t("addAComment") || "Add a comment..."}
              className="flex-1 bg-transparent border-none text-sm text-gray-900 dark:text-white placeholder-gray-400 focus:ring-0 p-0"
            />
            <button
              className="text-primary-600 dark:text-primary-400 font-semibold text-sm disabled:opacity-50 ml-2"
              disabled={!quickComment.trim()}
              onClick={addComment}
            >
              {t("post") || "Post"}
            </button>
          </div>
        )}
      </div>

      {/* Media Preview Modal */}
      <MediaPreviewModal
        isOpen={showModal}
        mediaItems={mediaItemsForModal}
        title="Comments"
        currentIndex={currentMediaIndex}
        showSidebar={true}
        messages={allCommentsForModal}
        currentUser={currentUser}
        onClose={closeModal}
        onUpdateCurrentIndex={setCurrentMediaIndex}
        onSendMessage={handleNewComment}
      />
    </>
  )
}

// apps/creator/components/PostCard.vue
<template>
	<div>
		<div
			class="bg-white dark:bg-gray-900 rounded-xl shadow-md border border-gray-100 dark:border-gray-800 mb-8 overflow-hidden"
		>
			<!-- Header -->

			<div class="flex items-center justify-between px-4 py-3">
				<div class="flex items-center">
					<NuxtLink to="/@user" class="flex-shrink-0">
						<img
							:src="post.creator.avatar"
							:alt="post.creator.name"
							class="w-8 h-8 rounded-full object-cover border border-gray-200 dark:border-gray-700"
						/>
					</NuxtLink>

					<div class="ml-3">
						<NuxtLink to="/@user">
							<h3 class="font-semibold text-sm text-gray-900 dark:text-white hover:underline">
								{{ post.creator.name }}
							</h3>
						</NuxtLink>

						<p class="text-xs text-gray-500 dark:text-gray-400">{{ post.location || t('unknownLocation') }}</p>
					</div>
				</div>

				<button class="text-gray-500 dark:text-gray-400">
					<Icon name="lucide:more-vertical" class="w-5 h-5" />
				</button>
			</div>

			<!-- Media Container -->

			<div class="relative aspect-video w-full bg-gray-100 dark:bg-gray-800 overflow-hidden">
				<template v-if="post.isPremium && !isSubscribed">
					<div class="absolute inset-0 z-10 flex flex-col justify-center items-center bg-white/70 dark:bg-gray-900/70">
						<button
							class="max-w-md rounded-full btn-primary text-white font-semibold py-4 px-6 text-lg transition-all"
							@click="$emit('subscribe')"
						>
							{{ t('subscribe') }}
						</button>
					</div>

					<div class="absolute inset-0 w-full h-full filter blur-sm pointer-events-none select-none">
						<img v-if="post.image" :src="post.image" class="w-full h-full object-cover" alt="Post content" />
						<video v-else-if="post.video" class="w-full h-full object-cover" :poster="post.image">
							<source :src="post.video" type="video/mp4" />
						</video>
					</div>
				</template>
				<template v-else>
					<div class="absolute inset-0 w-full h-full cursor-pointer" @click="openModal(0)">
						<img v-if="post.image" :src="post.image" class="w-full h-full object-cover" />
						<video v-if="post.video" class="w-full h-full object-cover" :poster="post.image">
							<source :src="post.video" type="video/mp4" />
						</video>
					</div>
				</template>
			</div>

			<!-- Actions -->

			<div class="px-4 py-3">
				<div class="flex items-center justify-between mb-2">
					<div class="flex items-center space-x-4">
						<button
							:disabled="post.isPremium && !isSubscribed"
							:class="[
								post.isPremium && !isSubscribed ? 'opacity-50 cursor-not-allowed' : '',
								'text-gray-900 dark:text-white',
							]"
							@click="toggleLike"
						>
							<Icon
								:name="isLiked ? 'lucide:heart' : 'lucide:heart'"
								class="w-6 h-6"
								:class="{ 'fill-red-500 text-red-500': isLiked }"
							/>
						</button>
						<button
							:disabled="post.isPremium && !isSubscribed"
							:class="[
								post.isPremium && !isSubscribed ? 'opacity-50 cursor-not-allowed' : '',
								'text-gray-900 dark:text-white',
							]"
							@click="openModal(0, true)"
						>
							<Icon name="lucide:message-circle" class="w-6 h-6" />
						</button>
						<button
							:disabled="post.isPremium && !isSubscribed"
							:class="[
								post.isPremium && !isSubscribed ? 'opacity-50 cursor-not-allowed' : '',
								'text-gray-900 dark:text-white',
							]"
						>
							<Icon name="lucide:send" class="w-6 h-6" />
						</button>
					</div>
					<button
						:disabled="post.isPremium && !isSubscribed"
						:class="[
							post.isPremium && !isSubscribed ? 'opacity-50 cursor-not-allowed' : '',
							'text-gray-900 dark:text-white',
						]"
					>
						<Icon name="lucide:bookmark" class="w-6 h-6" />
					</button>
				</div>

				<!-- Likes count -->

				<p class="text-sm font-semibold text-gray-900 dark:text-white mb-1">{{ formatNumber(post.likes) }} {{ t('likes') }}</p>

				<!-- Caption with username -->

				<p class="text-sm text-gray-900 dark:text-white mb-1">
					<span class="font-semibold">{{ post.creator.name }}</span> {{ post.content }}
				</p>

				<!-- View comments -->
				<button
					v-if="(post.comments.length > 0 || localComments.length > 0) && !(post.isPremium && !isSubscribed)"
					class="text-sm text-gray-500 dark:text-gray-400 mb-1"
					@click="openModal(0, true)"
				>
					{{ t('viewAllComments', { count: post.comments.length + localComments.length }) }}
				</button>

				<!-- Display local comments -->

				<template v-if="!(post.isPremium && !isSubscribed)">
					<div v-for="(comment, index) in localComments" :key="'local-' + index" class="mb-1">
						<p class="text-sm text-gray-900 dark:text-white">
							<span class="font-semibold">{{ currentUser.name }}</span> {{ comment }}
						</p>
					</div>
				</template>

				<!-- Timestamp -->

				<p class="text-xs text-gray-400 dark:text-gray-500 uppercase mt-2">{{ formatTimeAgo(post.createdAt) }}</p>
			</div>

			<!-- Add comment (quick) -->

			<div
				v-if="!(post.isPremium && !isSubscribed)"
				class="px-4 py-3 border-t border-gray-100 dark:border-gray-800 flex items-center"
			>
				<input
					v-model="quickComment"
					type="text"
					:placeholder="t('addAComment')"
					class="flex-1 bg-transparent border-none text-sm text-gray-900 dark:text-white placeholder-gray-400 focus:ring-0"
					@keyup.enter="addComment"
				/>
				<button
					class="text-primary-600 dark:text-primary-400 font-semibold text-sm disabled:opacity-50"
					:disabled="!quickComment.trim()"
					@click="addComment"
				>
					{{ t('post') }}
				</button>
			</div>
		</div>

		<!-- Media Preview Modal -->
		<media-preview-modal
			v-if="showModal"
			:is-open="showModal"
			:media-items="mediaItemsForModal"
			:current-index="currentMediaIndex"
			:show-sidebar="true"
			:messages="allCommentsForModal"
			:current-user="currentUser"
			@close="closeModal"
			@update:current-index="updateMediaIndex"
			@send-message="handleNewComment"
		/>
	</div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useI18n } from 'vue-i18n';
import MediaPreviewModal from './ui/MediaPreviewModal.vue';

interface User {
	name: string
	avatar: string
}

interface Comment {
	content: string
	createdAt: Date
	user: User
}

interface Post {
	id: string
	creator: User
	content: string
	location?: string
	image?: string
	video?: string
	createdAt: Date
	likes: number
	isPremium: boolean
	comments: Comment[]
}

interface PostCardProps {
	post: Post
	isSubscribed: boolean
}

interface PostCardEmits {
	(e: 'subscribe'): void
	(e: 'tip'): void
	(e: 'add-comment', comment: string): void
}

interface MediaItem {
	url: string
	type: 'image' | 'video'
}

interface Message {
	text: string
	timestamp: Date
	user: User
	isCurrentUser: boolean
}

// Current user data
const currentUser = ref<User>({
	name: 'YourUsername',
	avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
});

const props = defineProps<PostCardProps>();

const emit = defineEmits<PostCardEmits>();

const showModal = ref(false);
const quickComment = ref('');
const isLiked = ref(false);
const currentMediaIndex = ref(0);
const showComments = ref(false);
const localComments = ref<string[]>([]);

const { t } = useI18n();

const formatNumber = (num: number): string => {
	return new Intl.NumberFormat('en-US').format(num);
};

// Format media items for the modal
const mediaItemsForModal = computed<MediaItem[]>(() => {
	return [
		{
			url: props.post.video || props.post.image || '',
			type: props.post.video ? 'video' : 'image',
		},
	];
});

// Combine post comments and local comments for modal
const allCommentsForModal = computed<Message[]>(() => {
	const captionMessage: Message = {
		text: props.post.content,
		timestamp: props.post.createdAt,
		user: {
			name: props.post.creator.name,
			avatar: props.post.creator.avatar,
		},
		isCurrentUser: false,
	};

	const postComments: Message[] = props.post.comments.map((comment) => ({
		text: comment.content,
		timestamp: comment.createdAt,
		user: {
			name: comment.user.name,
			avatar: comment.user.avatar,
		},
		isCurrentUser: false,
	}));

	const localCommentMessages: Message[] = localComments.value.map((comment) => ({
		text: comment,
		timestamp: new Date(),
		user: {
			name: currentUser.value.name,
			avatar: currentUser.value.avatar,
		},
		isCurrentUser: true,
	}));

	return [captionMessage, ...postComments, ...localCommentMessages];
});

const formatTimeAgo = (date: Date): string => {
	const now = new Date();
	const diffInSeconds = Math.floor((now.getTime() - new Date(date).getTime()) / 1000);

	if (diffInSeconds < 60) {
		return t('secondsAgo', { count: diffInSeconds });
	}
	if (diffInSeconds < 3600) {
		return t('minutesAgo', { count: Math.floor(diffInSeconds / 60) });
	}
	if (diffInSeconds < 86400) {
		return t('hoursAgo', { count: Math.floor(diffInSeconds / 3600) });
	}
	return t('daysAgo', { count: Math.floor(diffInSeconds / 86400) });
};

const toggleLike = (): void => {
	isLiked.value = !isLiked.value;
};

const openModal = (index = 0, withComments = false): void => {
	if (props.post.isPremium && !props.isSubscribed) {
		emit('subscribe');
		return;
	}
	currentMediaIndex.value = index;
	showComments.value = withComments;
	showModal.value = true;
};

const closeModal = (): void => {
	showModal.value = false;
	showComments.value = false;
};

const updateMediaIndex = (index: number): void => {
	currentMediaIndex.value = index;
};

const addComment = (): void => {
	if (!quickComment.value.trim()) {
		return;
	}

	localComments.value.push(quickComment.value);
	emit('add-comment', quickComment.value);
	quickComment.value = '';
};

const handleNewComment = (comment: string): void => {
	localComments.value.push(comment);
	emit('add-comment', comment);
};
</script>

<style scoped>
/* Custom styles for the post card */
video {
	background-color: #000;
}
</style>
