// apps/creator/components/earnings/TransactionsTable.vue
<template>
  <div class="bg-white dark:bg-gray-900 shadow-sm rounded-lg">
    <div class="p-6">
      <div class="sm:flex sm:items-center sm:justify-between mb-6">
        <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">{{ t('earnings.transactions.title') }}</h2>

        <div class="mt-3 sm:mt-0">
          <button class="btn-outline" @click="$emit('download')">{{ t('earnings.transactions.downloadCsv') }}</button>
        </div>
      </div>

      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th
                v-for="(label, key) in headers"
                :key="key"
                class="px-6 py-3 bg-gray-50 dark:bg-gray-800 text-left text-xs font-medium text-gray-500 dark:text-gray-200 dark:text-gray-400 uppercase tracking-wider"
              >
                {{ label }}
              </th>
            </tr>
          </thead>

          <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200">
            <tr
              v-for="transaction in paginatedTransactions"
              :key="transaction.id"
              class="hover:bg-gray-50 hover:dark:bg-gray-600"
            >
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
                {{ formatDate(transaction.date) }}
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <span
                  class="badge"
                  :class="{
                    'badge-primary': transaction.type === 'subscription',
                    'badge-secondary': transaction.type === 'tip',
                    'badge-accent': transaction.type === 'ppv',
                  }"
                >
                  {{ t(`earnings.transactions.types.${transaction.type}`) }}
                </span>
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="avatar h-8 w-8">
                    <img
                      :src="transaction.customer.avatar"
                      :alt="transaction.customer.name"
                      class="h-full w-full object-cover"
                    />
                  </div>

                  <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900 dark:text-gray-100">
                      {{ transaction.customer.name }}
                    </div>

                    <div class="text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
                      {{ transaction.customer.email }}
                    </div>
                  </div>
                </div>
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900 dark:text-gray-100">${{ transaction.amount.toFixed(2) }}</div>

                <div class="text-xs text-gray-500 dark:text-gray-200 dark:text-gray-400">
                  {{ t('earnings.transactions.afterFees', { amount: (transaction.amount * 0.8).toFixed(2) }) }}
                </div>
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <span
                  class="badge"
                  :class="{
                    'badge-success': transaction.status === 'completed',
                    'badge-warning': transaction.status === 'pending',
                    'badge-error': transaction.status === 'failed',
                  }"
                >
                  {{ t(`earnings.transactions.status.${transaction.status}`) }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <Pagination
        v-if="totalPages > 1"
        :current-page="currentPage"
        :per-page="perPage"
        :total-items="transactions.length"
        :per-page-options="[10, 20, 50, 100]"
        :show-end-buttons="true"
        :show-per-page="true"
        :show-range="true"
        @update:current-page="$emit('update:currentPage', $event)"
        @update:per-page="$emit('update:perPage', $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import Pagination from '~/components/ui/Pagination.vue';

interface Customer {
  name: string
  email: string
  avatar: string
}

interface Transaction {
  id: string
  date: string
  type: 'subscription' | 'tip' | 'ppv'
  customer: Customer
  amount: number
  status: 'completed' | 'pending' | 'failed'
}

interface Headers {
  [key: string]: string
}

const props = defineProps<{
  headers: Headers
  transactions: Transaction[]
  currentPage: number
  perPage: number
}>();

defineEmits<{
  (e: 'download'): void
  (e: 'update:currentPage', page: number): void
  (e: 'update:perPage', perPage: number): void
}>();

const { t } = useI18n();

const totalPages = computed(() => Math.ceil(props.transactions.length / props.perPage));

const paginatedTransactions = computed(() => {
  const start = (props.currentPage - 1) * props.perPage;
  const end = start + props.perPage;
  return props.transactions.slice(start, end);
});

const formatDate = (date: string): string => {
  return new Date(date).toLocaleDateString();
};
</script>

// apps/creator-next-app/components/earnings/transactions-table.tsx
"use client"

import { useTranslation } from "react-i18next"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"

interface Customer {
  name: string
  email: string
  avatar: string
}

interface Transaction {
  id: string
  date: Date
  type: "subscription" | "tip" | "ppv"
  customer: Customer
  amount: number
  status: "completed" | "pending" | "failed"
}

interface TransactionsTableProps {
  transactions: Transaction[]
  formatDate: (date: Date) => string
}

const typeColorMap: Record<string, string> = {
  subscription: "bg-primary-100 text-primary-800 dark:bg-primary-900 dark:text-primary-300",
  tip: "bg-secondary-100 text-secondary-800 dark:bg-secondary-900 dark:text-secondary-300",
  ppv: "bg-accent-100 text-accent-800 dark:bg-accent-900 dark:text-accent-300",
}

const statusColorMap: Record<string, string> = {
  completed: "bg-success-100 text-success-800 dark:bg-success-900 dark:text-success-300",
  pending: "bg-warning-100 text-warning-800 dark:bg-warning-900 dark:text-warning-300",
  failed: "bg-error-100 text-error-800 dark:bg-error-900 dark:text-error-300",
}

export function TransactionsTable({ transactions, formatDate }: TransactionsTableProps) {
  const { t } = useTranslation()

  const transactionHeaders = {
    date: t("earnings.transactions.headers.date"),
    type: t("earnings.transactions.headers.type"),
    customer: t("earnings.transactions.headers.customer"),
    amount: t("earnings.transactions.headers.amount"),
    status: t("earnings.transactions.headers.status"),
  }

  return (
    <div className="overflow-x-auto">
      <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
        <thead>
          <tr>
            {Object.entries(transactionHeaders).map(([key, label]) => (
              <th
                key={key}
                className="px-6 py-3 bg-gray-50 dark:bg-gray-800 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider"
              >
                {label}
              </th>
            ))}
          </tr>
        </thead>

        <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
          {transactions.map((transaction) => (
            <tr key={transaction.id} className="hover:bg-gray-50 dark:hover:bg-gray-800">
              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                {formatDate(transaction.date)}
              </td>

              <td className="px-6 py-4 whitespace-nowrap">
                <Badge className={typeColorMap[transaction.type]}>
                  {t(`earnings.transactions.types.${transaction.type}`)}
                </Badge>
              </td>

              <td className="px-6 py-4 whitespace-nowrap">
                <div className="flex items-center">
                  <Avatar className="h-8 w-8">
                    <AvatarImage src={transaction.customer.avatar} alt={transaction.customer.name} />
                    <AvatarFallback>
                      {transaction.customer.name.split(" ").map((n) => n[0]).join("")}
                    </AvatarFallback>
                  </Avatar>

                  <div className="ml-4">
                    <div className="text-sm font-medium text-gray-900 dark:text-gray-100">
                      {transaction.customer.name}
                    </div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      {transaction.customer.email}
                    </div>
                  </div>
                </div>
              </td>

              <td className="px-6 py-4 whitespace-nowrap">
                <div className="text-sm text-gray-900 dark:text-gray-100">
                  ${transaction.amount.toFixed(2)}
                </div>
                <div className="text-xs text-gray-500 dark:text-gray-400">
                  {t("earnings.transactions.afterFees", { amount: (transaction.amount * 0.8).toFixed(2) })}
                </div>
              </td>

              <td className="px-6 py-4 whitespace-nowrap">
                <Badge className={statusColorMap[transaction.status]}>
                  {t(`earnings.transactions.status.${transaction.status}`)}
                </Badge>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
