// apps/creator/pages/content/edit/[id].vue
<template>
	<div class="max-w-6xl mx-auto">
		<Head>
			<Title>{{ $t('content.edit.title') }} - Whispers</Title>
		</Head>

		<div class="mb-6">
			<div class="flex items-center">
				<NuxtLink to="/content" class="mr-2 text-gray-500 dark:text-gray-200 hover:text-gray-700">
					<Icon name="lucide:arrow-left" class="h-5 w-5" />
				</NuxtLink>
				<h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">{{ $t('content.edit.title') }}</h1>
			</div>
			<p class="mt-1 text-sm text-gray-500 dark:text-gray-200">{{ $t('content.edit.description') }}</p>
		</div>

		<div class="bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
			<SkeletonLoader v-if="loading" variant="post-form" :rows="5" width="80%" height="2rem" class="mx-auto my-8" />
			<PostForm
				v-else-if="postData" 
				:initial-values="postData" 
				:errors="errors" 
				:loading="updateLoading"
				:min-schedule-date="minScheduleDate" 
				:is-edit-mode="true"
				@submit="handleSubmit" 
				@draft="saveAsDraft"
				@cancel="() => router.push('/content')" 
			/>

			<div v-else class="p-8 text-center text-gray-500 dark:text-gray-200">{{ $t('content.edit.loading') }}</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useContentStore } from '../../../store/content';
import PostForm from '../../../components/PostForm.vue';
import SkeletonLoader from '../../../components/ui/SkeletonLoader.vue';
import { useNotification } from '../../../composables/useNotifications';

const router = useRouter();
const route = useRoute();
const contentStore = useContentStore();
const { t } = useI18n();
const { success, error, info } = useNotification();

definePageMeta({
  middleware: ['auth'],
  layout: 'creator',
  meta: {
    requiresAuth: true,
    requiresCreator: true,
  },
});

interface PostFormData {
  title: string
  content: string
  visibility: 'public' | 'private' | 'pay-to-view'
  price: number
  mediaUrls: string[]
}

interface PostFormErrors {
  title: string
  content: string
  mediaFiles: string
  visibility: string
  price: string
  scheduledDate: string
}

const errors = reactive<PostFormErrors>({
  title: '',
  content: '',
  mediaFiles: '',
  visibility: '',
  price: '',
  scheduledDate: '',
});

const minScheduleDate = computed<string>(() => {
  const date = new Date();
  date.setMinutes(date.getMinutes() + 10);
  return date.toISOString().slice(0, 16);
});

const postData = ref<PostFormData | null>(null);
const loading = ref(true);
const updateLoading = ref(false);

onMounted(async () => {
  loading.value = true;
  try {
    const response = await contentStore.getContentById(route.params.id as string);
    const post = response.data.post;
    
    // Transform the post data to match PostForm expectations
    postData.value = {
      title: post.title,
      content: post.body,
      visibility: post.visibility,
      price: post.price,
      // Transform mediaFiles array to the expected format
      mediaUrls: post.mediaFiles ? post.mediaFiles.map(file => ({
        id: file.id || file._id,
        url: file.url || file.fileUrl,
        type: file.type,
        name: file.name,
        thumbnailUrl: file.thumbnailUrl,
        cover: file.cover || file.coverUrl,
        duration: file.duration,
        size: file.size
      })) : [],
      scheduledDate: post.scheduledDate
    };
  } catch (e) {
    error(t('content.edit.loadFailed'));
  } finally {
    loading.value = false;
  }
});

function validateForm(formData: PostFormData): boolean {
  let isValid = true;
  Object.keys(errors).forEach((key) => {
    (errors as any)[key] = '';
  });
  
  if (!formData.title || !formData.title.trim()) {
    errors.title = t('validation.required', { field: t('content.form.title') });
    isValid = false;
  } else if (formData.title.length > 100) {
    errors.title = t('validation.maxLength', { field: t('content.form.title'), max: 100 });
    isValid = false;
  }
  
  if (!formData.content || !formData.content.trim()) {
    errors.content = t('validation.required', { field: t('content.form.content') });
    isValid = false;
  }
  
  if (formData.mediaUrls && formData.mediaUrls.length > 10) {
    errors.mediaFiles = t('validation.maxFiles', { max: 10 });
    isValid = false;
  }
  
  if (formData.visibility === 'pay-to-view') {
    if (!formData.price) {
      errors.price = t('validation.required', { field: t('content.form.price') });
      isValid = false;
    } else if (formData.price < 1 || formData.price > 100) {
      errors.price = t('validation.priceRange');
      isValid = false;
    }
  }
  
  return isValid;
}

async function handleSubmit(formData: any): Promise<void> {
  try {
    updateLoading.value = true;
    // Extract media file IDs properly - formData.mediaFiles should contain the IDs
    const mediaFileIds = Array.isArray(formData.mediaFiles) 
      ? formData.mediaFiles.filter(Boolean)
      : [];

    const updateData = {
      title: formData.title,
      body: formData.body || formData.content,
      visibility: formData.visibility,
      mediaFiles: mediaFileIds,
      ...(formData.visibility === 'pay-to-view' && { price: formData.price }),
      ...(formData.isScheduled && { scheduledDate: formData.scheduledDate })
    };

    await contentStore.updateContent(route.params.id as string, updateData);
    success(t('notifications.contentUpdated'));
    router.push('/content');
  } catch (err) {
    error(t('notifications.contentUpdateFailed'));
    console.error('Update failed:', err);
  } finally {
    updateLoading.value = false;
  }
}

function saveAsDraft(formData: any): void {
  // Handle draft saving for edit mode
  info(t('notifications.draftSaved'));
}
</script>

// apps/creator-next-app/app/(dashboard)/content/edit/[id]/page.tsx
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"
import { PostForm } from "@/components/content/post-form"
import { useContentById, useUpdateContent } from "@/lib/content/content-hooks"
import { useAuthStore } from "@/lib/auth/auth-store"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import Link from "next/link"
import { useRouter, useParams } from "next/navigation"
import type { PostFormValues } from "@/components/content/post-form"

export default function EditContentPage() {
  const { t } = useTranslation()
  const router = useRouter()
  const params = useParams()
  const [isClient, setIsClient] = useState(false)
  const { isAuthenticated } = useAuthStore()

  const contentId = params.id as string
  const { data: contentData, isLoading: loading, error } = useContentById(contentId)
  const updateMutation = useUpdateContent()

  useEffect(() => {
    setIsClient(true)
  }, [])

  if (!isClient) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-96 bg-gray-200 dark:bg-gray-700 rounded"></div>
        </div>
      </div>
    )
  }

  if (!isAuthenticated) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">Please log in to edit content</h2>
          <Button onClick={() => (window.location.href = "/auth")}>Go to Login</Button>
        </div>
      </div>
    )
  }

  const minScheduleDate = new Date()
  minScheduleDate.setMinutes(minScheduleDate.getMinutes() + 10)

  const handleSubmit = async (formData: PostFormValues) => {
    const mediaFileIds = Array.isArray(formData.mediaFiles) ? formData.mediaFiles.filter(Boolean) : []

    const updateData = {
      title: formData.title,
      body: formData.content,
      visibility: formData.visibility,
      mediaFiles: mediaFileIds,
      ...(formData.visibility === "pay-to-view" && { price: formData.price }),
      ...(formData.scheduledDate && { scheduledDate: formData.scheduledDate }),
    }

    updateMutation.mutate(
      { id: contentId, data: updateData },
      {
        onSuccess: () => {
          toast.success(t("notifications.contentUpdated"))
          router.push("/content")
        },
        onError: () => {
          toast.error(t("notifications.contentUpdateFailed"))
        },
      },
    )
  }

  const handleDraft = async (formData: PostFormValues) => {
    toast.success(t("notifications.draftSaved"))
  }

  const handleCancel = () => {
    router.push("/content")
  }

  if (loading) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="mb-6">
          <div className="flex items-center">
            <Link href="/content" className="mr-2 text-gray-500 dark:text-gray-200 hover:text-gray-700">
              <Icons.arrowLeft className="h-5 w-5" />
            </Link>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{t("content.edit.title")}</h1>
          </div>
          <p className="mt-1 text-sm text-gray-500 dark:text-gray-200">{t("content.edit.description")}</p>
        </div>

        <div className="bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
          <div className="p-8">
            <div className="animate-pulse space-y-6">
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4"></div>
              <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded"></div>
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2"></div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  if (error || !contentData || !contentData?.post) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-red-600 mb-4">{t("content.edit.loadFailed")}</h2>
          <Button onClick={() => window.location.reload()}>Retry</Button>
        </div>
      </div>
    )
  }

  const initialValues = {
    title: contentData?.post?.title,
    content: contentData?.post?.body,
    visibility: (contentData?.post?.visibility === "private"
      ? "subscribers"
      : contentData?.post?.visibility === "premium"
      ? "pay-to-view"
      : "public") as "public" | "subscribers" | "pay-to-view",
    price: contentData?.post?.price || 4.99,
    mediaUrls: contentData?.post?.mediaFiles
      ? contentData?.post?.mediaFiles.map((file: any) => ({
          id: file.id || file._id,
          url: file.url || file.fileUrl,
          type: file.type,
          name: file.name,
          thumbnailUrl: file.thumbnailUrl,
          cover: file.cover || file.coverUrl,
          duration: file.duration,
          size: file.size,
        }))
      : [],
    ...(typeof (contentData as any)?.post?.scheduledDate === "string" ? { scheduledDate: (contentData as any)?.post?.scheduledDate } : {}),
  }
  
  return (
    <div className="max-w-6xl mx-auto p-6">
      <div className="mb-6">
        <div className="flex items-center">
          <Link href="/content" className="mr-2 text-gray-500 dark:text-gray-200 hover:text-gray-700">
            <Icons.arrowLeft className="h-5 w-5" />
          </Link>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{t("content.edit.title")}</h1>
        </div>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-200">{t("content.edit.description")}</p>
      </div>

      <div className="bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
        <PostForm
          initialValues={initialValues}
          loading={updateMutation.isPending}
          minScheduleDate={minScheduleDate.toISOString().slice(0, 16)}
          isEditMode={true}
          onSubmit={handleSubmit}
          onDraft={handleDraft}
          onCancel={handleCancel}
        />
      </div>
    </div>
  )
}
