// apps/creator-next-app/components/apply/ApplyForm.tsx
"use client"

import { useEffect, useMemo, useState } from "react"
import { useForm } from "@tanstack/react-form"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { z } from "zod"
import {
  applyFormSchema,
  type ApplyFormValues,
  availableCategoriesData,
  type PricingPreference,
} from "@/lib/apply-schema"
import { DoorClosedIcon as CloseIcon } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Facebook, Instagram, Twitter, Music, Send, Loader2, AlertCircle } from "lucide-react"

// Placeholder for i18n - replace with your i18n solution
const t = (key: string, fallback: string) => fallback

const initialFormValues: ApplyFormValues = {
  displayName: "",
  username: "",
  bio: "",
  categories: [],
  social: { facebook: "", instagram: "", twitter: "", tiktok: "" },
  monthlyPrice: 4.99,
  discounts: {}, // Will be populated from preferences
  acceptTerms: false,
  confirmAge: false,
}

async function fetchCreatorPreferences(): Promise<PricingPreference[]> {
  const res = await fetch("/api/creator-preferences")
  if (!res.ok) throw new Error("Failed to fetch pricing preferences")
  return res.json()
}

async function submitApplication(values: ApplyFormValues) {
  const res = await fetch("/api/apply", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(values),
  })
  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}))
    throw new Error(errorData.message || "Application submission failed")
  }
  return res.json()
}

export default function ApplyCreatorForm() {
  const queryClient = useQueryClient()
  const [formError, setFormError] = useState<string | null>(null)
  const [formSuccess, setFormSuccess] = useState<string | null>(null)

  const { data: pricingPreferences = [], isLoading: isLoadingPreferences } = useQuery<PricingPreference[]>({
    queryKey: ["creatorPreferences"],
    queryFn: fetchCreatorPreferences,
  })

  const preferencesByCycle = useMemo(() => {
    const grouped: Record<string, PricingPreference[]> = {}
    for (const pref of pricingPreferences) {
      if (!grouped[pref.cycle]) grouped[pref.cycle] = []
      grouped[pref.cycle].push(pref)
    }
    return grouped
  }, [pricingPreferences])

  const form = useForm<ApplyFormValues>({
    defaultValues: initialFormValues,
    validators: {
      onChange: applyFormSchema,
    },
    onSubmit: async ({ value }) => {
      setFormError(null)
      setFormSuccess(null)
      console.log("Submitting form with values:", value)
      await applicationMutation.mutateAsync(value)
    },
  })

  const applicationMutation = useMutation({
    mutationFn: submitApplication,
    onSuccess: (data) => {
      setFormSuccess(data.message || "Application submitted successfully!")
      form.reset()
      // queryClient.invalidateQueries({ queryKey: ['someOtherData'] }) // If needed
    },
    onError: (error: Error) => {
      setFormError(error.message || "An unknown error occurred.")
    },
  })

  // Effect to set initial discount values once preferences are loaded
  useEffect(() => {
    if (pricingPreferences.length > 0 && form.state.values.monthlyPrice) {
      const initialDiscounts: Record<string, string> = {}
      Object.entries(preferencesByCycle).forEach(([cycle, prefs]) => {
        const zeroDiscount = prefs.find((p) => p.discount === 0)
        if (zeroDiscount) {
          initialDiscounts[cycle] = zeroDiscount._id
        } else if (prefs.length > 0) {
          initialDiscounts[cycle] = prefs[0]._id
        }
      })
      form.setFieldValue("discounts", initialDiscounts)
    }
  }, [pricingPreferences, preferencesByCycle, form.setFieldValue, form.state.values.monthlyPrice])

  const monthlyPrice = form.useStore((s) => s.values.monthlyPrice)
  const currentDiscounts = form.useStore((s) => s.values.discounts)

  const periodPrices = useMemo(() => {
    const calculatedPrices: Record<string, number> = {}
    if (!monthlyPrice || Object.keys(currentDiscounts).length === 0 || pricingPreferences.length === 0) {
      return calculatedPrices
    }

    Object.entries(currentDiscounts).forEach(([cycle, selectedId]) => {
      const cyclePrefs = preferencesByCycle[cycle]
      if (!cyclePrefs || !selectedId) return

      const option = cyclePrefs.find((opt) => opt._id === selectedId)
      if (option) {
        let multiplier = 1
        if (cycle === "quarterly") multiplier = 3
        if (cycle === "yearly") multiplier = 12
        calculatedPrices[cycle] = Math.round(monthlyPrice * multiplier * (1 - option.discount / 100) * 100) / 100
      }
    })
    return calculatedPrices
  }, [monthlyPrice, currentDiscounts, preferencesByCycle, pricingPreferences])

  const FieldInfo = ({ field }: { field: any }) => (
    <>
      {field.state.meta.touchedErrors ? (
        <p className="text-sm text-red-500 mt-1">{field.state.meta.touchedErrors}</p>
      ) : null}
      {/* {field.state.meta.isValidating ? 'Validating...' : null} */}
    </>
  )

  return (
    <Card className="w-full max-w-3xl mx-auto my-8">
      <CardHeader>
        <CardTitle>{t("apply.title", "Apply to be a Creator")}</CardTitle>
        <CardDescription>{t("apply.description", "Fill out the form below to start your journey.")}</CardDescription>
      </CardHeader>
      <CardContent>
        <form.Provider>
          <form
            onSubmit={(e) => {
              e.preventDefault()
              e.stopPropagation()
              form.handleSubmit()
            }}
            className="space-y-10"
          >
            {/* Basic Information */}
            <section>
              <h2 className="text-xl font-semibold mb-6">{t("apply.basicInfo.title", "Basic Information")}</h2>
              <div className="space-y-6">
                <form.Field
                  name="displayName"
                  validators={{ onChange: applyFormSchema.shape.displayName }}
                  children={(field) => (
                    <div>
                      <Label htmlFor={field.name}>
                        {t("apply.basicInfo.displayName", "Display Name")} <span className="text-red-500">*</span>
                      </Label>
                      <Input
                        id={field.name}
                        name={field.name}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(e) => field.handleChange(e.target.value)}
                        placeholder={t("apply.basicInfo.displayNamePlaceholder", "Your public name")}
                        className="mt-1"
                      />
                      <FieldInfo field={field} />
                    </div>
                  )}
                />
                <form.Field
                  name="username"
                  validators={{ onChange: applyFormSchema.shape.username }}
                  children={(field) => (
                    <div>
                      <Label htmlFor={field.name}>
                        {t("apply.basicInfo.username", "Username")} <span className="text-red-500">*</span>
                      </Label>
                      <Input
                        id={field.name}
                        name={field.name}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(e) => field.handleChange(e.target.value)}
                        placeholder={t("apply.basicInfo.usernamePlaceholder", "your_unique_username")}
                        className="mt-1"
                      />
                      <FieldInfo field={field} />
                    </div>
                  )}
                />
                <form.Field
                  name="bio"
                  validators={{ onChange: applyFormSchema.shape.bio }}
                  children={(field) => (
                    <div>
                      <Label htmlFor={field.name}>
                        {t("apply.basicInfo.bio", "Bio")} <span className="text-red-500">*</span>
                      </Label>
                      <Textarea
                        id={field.name}
                        name={field.name}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(e) => field.handleChange(e.target.value)}
                        placeholder={t("apply.basicInfo.bioPlaceholder", "Tell us about yourself...")}
                        rows={3}
                        className="mt-1"
                      />
                      <FieldInfo field={field} />
                    </div>
                  )}
                />
                <form.Field
                  name="categories"
                  validators={{ onChange: applyFormSchema.shape.categories }}
                  children={(field) => (
                    <div>
                      <Label>
                        {t("apply.basicInfo.categories", "Categories")} <span className="text-red-500">*</span>
                      </Label>
                      <div className="flex flex-wrap gap-2 mt-1">
                        {availableCategoriesData.map((cat) => (
                          <Button
                            key={cat}
                            type="button"
                            variant={field.state.value.includes(cat) ? "default" : "outline"}
                            size="sm"
                            onClick={() => {
                              const currentCategories = field.state.value
                              const newCategories = currentCategories.includes(cat)
                                ? currentCategories.filter((c) => c !== cat)
                                : [...currentCategories, cat]
                              field.handleChange(newCategories)
                            }}
                          >
                            {cat}
                            {field.state.value.includes(cat) && <CloseIcon className="ml-2 h-4 w-4" />}
                          </Button>
                        ))}
                      </div>
                      <FieldInfo field={field} />
                    </div>
                  )}
                />
              </div>
            </section>

            {/* Social Media */}
            <section className="pt-8 border-t">
              <h2 className="text-xl font-semibold mb-6">{t("apply.social.title", "Social Media")}</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {(["facebook", "instagram", "twitter", "tiktok"] as const).map((socialPlatform) => (
                  <form.Field
                    key={socialPlatform}
                    name={`social.${socialPlatform}`}
                    validators={{ onChange: applyFormSchema.shape.social.shape[socialPlatform] }}
                    children={(field) => (
                      <div>
                        <Label htmlFor={field.name} className="capitalize flex items-center">
                          {socialPlatform === "facebook" && <Facebook className="mr-2 h-4 w-4" />}
                          {socialPlatform === "instagram" && <Instagram className="mr-2 h-4 w-4" />}
                          {socialPlatform === "twitter" && <Twitter className="mr-2 h-4 w-4" />}
                          {socialPlatform === "tiktok" && <Music className="mr-2 h-4 w-4" />}
                          {t(`apply.social.${socialPlatform}`, socialPlatform)}
                        </Label>
                        <Input
                          id={field.name}
                          name={field.name}
                          value={field.state.value || ""}
                          onBlur={field.handleBlur}
                          onChange={(e) => field.handleChange(e.target.value)}
                          placeholder={t("apply.social.usernamePlaceholder", "Your username")}
                          className="mt-1"
                        />
                        <FieldInfo field={field} />
                      </div>
                    )}
                  />
                ))}
              </div>
              <form.Field
                name="social" // For object-level error
                children={(field) => <FieldInfo field={field} />}
              />
            </section>

            {/* Pricing Section */}
            <section className="pt-8 border-t">
              <h2 className="text-xl font-semibold mb-6">{t("apply.pricing.title", "Pricing")}</h2>
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-medium mb-2">
                    {t("apply.pricing.monthlySubscription", "Monthly Subscription")}
                  </h3>
                  <form.Field
                    name="monthlyPrice"
                    validators={{ onChange: applyFormSchema.shape.monthlyPrice }}
                    children={(field) => (
                      <div>
                        <Label htmlFor={field.name}>
                          {t("apply.pricing.monthlyPrice", "Monthly Price (USD)")}{" "}
                          <span className="text-red-500">*</span>
                        </Label>
                        <Input
                          id={field.name}
                          name={field.name}
                          type="number"
                          value={field.state.value}
                          onBlur={field.handleBlur}
                          onChange={(e) => field.handleChange(Number.parseFloat(e.target.value))}
                          placeholder="4.99"
                          min="4.99"
                          step="0.01"
                          className="mt-1"
                        />
                        <FieldInfo field={field} />
                      </div>
                    )}
                  />
                </div>

                <h3 className="text-lg font-medium mb-2">
                  {t("apply.pricing.subscriptionPlans", "Subscription Plans (Optional Discounts)")}
                </h3>
                {isLoadingPreferences && <p>Loading pricing options...</p>}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {Object.entries(preferencesByCycle).map(([cycle, cyclePrefs]) => (
                    <Card key={cycle}>
                      <CardHeader>
                        <CardTitle className="capitalize">{t(`apply.pricing.${cycle}Plan`, `${cycle} Plan`)}</CardTitle>
                        <CardDescription>
                          {t(`apply.pricing.${cycle}Description`, `Discount for ${cycle} subscription.`)}
                        </CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        <form.Field
                          name={`discounts.${cycle}`}
                          children={(field) => (
                            <div>
                              <Label htmlFor={field.name}>{t("apply.pricing.discount", "Select Discount")}</Label>
                              <Select
                                value={field.state.value || ""}
                                onValueChange={(value) => field.handleChange(value)}
                              >
                                <SelectTrigger id={field.name} className="mt-1">
                                  <SelectValue placeholder={t("common.select", "Select discount...")} />
                                </SelectTrigger>
                                <SelectContent>
                                  {cyclePrefs.map((opt) => (
                                    <SelectItem key={opt._id} value={opt._id}>
                                      {opt.discount}% {t("common.off", "off")}
                                    </SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                              <FieldInfo field={field} />
                            </div>
                          )}
                        />
                        <div>
                          <Label>
                            {t(
                              `apply.pricing.total${cycle.charAt(0).toUpperCase() + cycle.slice(1)}Price`,
                              `Total ${cycle} Price`,
                            )}
                          </Label>
                          <Input
                            value={periodPrices[cycle]?.toFixed(2) || t("apply.pricing.calculating", "Calculating...")}
                            readOnly
                            className="mt-1 bg-gray-100 dark:bg-gray-800"
                          />
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            </section>

            {/* Legal Section */}
            <section className="pt-8 border-t">
              <h2 className="text-xl font-semibold mb-6">{t("apply.legal.title", "Legal")}</h2>
              <form.Field
                name="acceptTerms"
                validators={{ onChange: z.boolean().refine((v) => v, { message: "Required" }) }}
                children={(field) => (
                  <div className="flex items-start space-x-3">
                    <Checkbox
                      id={field.name}
                      checked={field.state.value}
                      onCheckedChange={(checked) => field.handleChange(Boolean(checked))}
                      onBlur={field.handleBlur}
                    />
                    <div className="grid gap-1.5 leading-none">
                      <Label htmlFor={field.name} className="font-medium">
                        {t("apply.legal.acceptTerms", "I accept the terms and conditions.")}{" "}
                        <span className="text-red-500">*</span>
                      </Label>
                      <FieldInfo field={field} />
                    </div>
                  </div>
                )}
              />
              <form.Field
                name="confirmAge"
                validators={{ onChange: z.boolean().refine((v) => v, { message: "Required" }) }}
                children={(field) => (
                  <div className="flex items-start space-x-3 mt-4">
                    <Checkbox
                      id={field.name}
                      checked={field.state.value}
                      onCheckedChange={(checked) => field.handleChange(Boolean(checked))}
                      onBlur={field.handleBlur}
                    />
                    <div className="grid gap-1.5 leading-none">
                      <Label htmlFor={field.name} className="font-medium">
                        {t("apply.legal.confirmAge", "I confirm I am of legal age to create content.")}{" "}
                        <span className="text-red-500">*</span>
                      </Label>
                      <FieldInfo field={field} />
                    </div>
                  </div>
                )}
              />
            </section>

            {formError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertTitle>{t("common.error", "Error")}</AlertTitle>
                <AlertDescription>{formError}</AlertDescription>
              </Alert>
            )}
            {formSuccess && (
              <Alert
                variant="default"
                className="bg-green-100 dark:bg-green-900 border-green-300 dark:border-green-700"
              >
                <AlertCircle className="h-4 w-4 text-green-700 dark:text-green-300" />
                <AlertTitle className="text-green-800 dark:text-green-200">{t("common.success", "Success")}</AlertTitle>
                <AlertDescription className="text-green-700 dark:text-green-300">{formSuccess}</AlertDescription>
              </Alert>
            )}

            <div className="pt-6 flex justify-end">
              <Button
                type="submit"
                disabled={applicationMutation.isPending || !form.state.isValid}
                className="w-full sm:w-auto"
              >
                {applicationMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    {t("apply.processing", "Processing...")}
                  </>
                ) : (
                  <>
                    <Send className="mr-2 h-4 w-4" />
                    {t("apply.button", "Submit Application")}
                  </>
                )}
              </Button>
            </div>
          </form>
        </form.Provider>
      </CardContent>
    </Card>
  )
}

// apps/creator/components/apply/ApplyForm.vue
<template>
  <Form :validation-schema="applyFormSchema" @submit="onSubmit" :initial-values="initialValues"
    v-slot="{ errors, meta, values, setFieldValue, setTouched, resetForm }" class="space-y-8" validate-on-input>
    <!-- Basic Information -->
    <section>
      <h2 class="text-xl font-semibold mb-6 text-gray-900 dark:text-gray-100">{{ t('apply.basicInfo.title') }}</h2>
      <div class="space-y-6">
        <Field name="displayName" v-slot="{ field, meta }">
          <FormInput v-model="field.value" :label="t('apply.basicInfo.displayName')" name="displayName"
            :placeholder="t('apply.basicInfo.displayNamePlaceholder')" v-bind="field"
            :error="meta.touched && errors.displayName" required />
        </Field>

        <Field name="username" v-slot="{ field, meta }">
          <FormInput v-model="field.value" v-bind="field" :label="t('apply.basicInfo.username')" name="username"
            :placeholder="t('apply.basicInfo.usernamePlaceholder')" :error="meta.touched && errors.username" required />
        </Field>

        <Field name="bio" v-slot="{ field, meta, handleChange }">
          <div>
            <label class="block text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
              {{ t('apply.basicInfo.bio') }} <span class="form-error text-error-600 dark:text-error-400">*</span>
            </label>
            <textarea v-bind="field" @input="(e) => {
              field.onChange(e);
              handleChange(e);
            }" rows="3" :placeholder="t('apply.basicInfo.bioPlaceholder')"
              class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-100 focus:border-primary-500 focus:ring-primary-500"
              :class="{ 'border-error-500': meta.touched && errors.bio }" />
            <ErrorMessage name="bio" class="text-sm form-error text-error-600 dark:text-error-400 mt-1" />
          </div>
        </Field>

        <Field name="categories" v-slot="{ value = [], handleChange }">
          <div>
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
              {{ t('apply.basicInfo.categories') }} <span class="form-error text-error-600 dark:text-error-400">*</span>
            </label>
            <div class="flex flex-wrap gap-2">
              <button v-for="cat in availableCategories" :key="cat" type="button"
                class="inline-flex items-center px-3 py-1 rounded-full text-sm transition-colors"
                :class="value.includes(cat)
                  ? 'bg-primary-100 text-primary-800 dark:bg-primary-900 dark:text-primary-200'
                  : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600'" @click="() => toggleCategory(cat, value, handleChange)">
                {{ cat }}
                <Icon v-if="value.includes(cat)" name="lucide:x" class="ml-1 h-4 w-4"
                  @click.stop="() => removeCategory(cat, value, handleChange)" />
              </button>
            </div>
            <ErrorMessage name="categories" class="text-sm form-error text-error-600 dark:text-error-400 mt-1" />
          </div>
        </Field>
      </div>
    </section>

    <!-- Social Media -->
    <section class="pt-8 border-t border-gray-200 dark:border-gray-700">
      <h2 class="text-xl font-semibold mb-6 text-gray-900 dark:text-gray-100">{{ t('apply.social.title') }}</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Field name="social.facebook" v-slot="{ field, meta }">
          <FormInput v-model="field.value" v-bind="field" :label="t('apply.social.facebook')" name="social.facebook"
            :placeholder="t('apply.social.usernamePlaceholder')" icon="lucide:facebook"
            @blur="onSocialBlur(setFieldValue)" />
        </Field>

        <Field name="social.instagram" v-slot="{ field, meta }">
          <FormInput v-model="field.value" v-bind="field" :label="t('apply.social.instagram')" name="social.instagram"
            :placeholder="t('apply.social.usernamePlaceholder')" icon="lucide:instagram"
            @blur="onSocialBlur(setFieldValue)" />
        </Field>

        <Field name="social.twitter" v-slot="{ field, meta }">
          <FormInput v-model="field.value" v-bind="field" :label="t('apply.social.twitter')" name="social.twitter"
            :placeholder="t('apply.social.usernamePlaceholder')" icon="lucide:twitter"
            @blur="onSocialBlur(setFieldValue)" />
        </Field>

        <Field name="social.tiktok" v-slot="{ field, meta }">
          <FormInput v-model="field.value" v-bind="field" :label="t('apply.social.tiktok')" name="social.tiktok"
            :placeholder="t('apply.social.usernamePlaceholder')" icon="lucide:music"
            @blur="onSocialBlur(setFieldValue)" />
        </Field>
      </div>
      <ErrorMessage name="social" class="text-error-600 dark:text-error-400 mt-1" />
    </section>

    <!-- Pricing Section -->
    <section class="pt-8 border-t border-gray-200 dark:border-gray-700">
      <h2 class="text-xl font-semibold mb-6 text-gray-900 dark:text-gray-100">{{ t('apply.pricing.title') }}</h2>
      <div class="space-y-6">
        <div class="mb-8">
          <h3 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-4">{{
            t('apply.pricing.monthlySubscription') }}</h3>
          <Field name="monthlyPrice" v-slot="{ field, meta }">
            <FormInput v-model="field.value" v-bind="field" type="number" :label="t('apply.pricing.monthlyPrice')"
              name="monthlyPrice" placeholder="" min="4.99" step="0.01" :error="meta.touched && errors.monthlyPrice"
              required @input="calculatePeriodPrices(values.monthlyPrice, values.discounts)" />
          </Field>
        </div>

        <h3 class="text-lg font-semibold text-gray-800 dark:text-gray-200">{{ t('apply.pricing.subscriptionPlans') }}
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div v-for="(options, cycle) in preferencesByCycle" :key="cycle"
            class="p-4 border rounded-lg dark:border-gray-600 bg-white dark:bg-gray-700 shadow-sm">
            <div class="flex md:items-center justify-between flex-col md:flex-row mb-3">
              <div>
                <h4 class="font-medium text-gray-800 dark:text-gray-200">
                  {{ t('apply.pricing.' + cycle + 'Plan') }}
                </h4>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                  {{ t('apply.pricing.' + cycle + 'Description') }}
                </p>
              </div>
              <!-- {{ options }} -->
              <Field :name="`discounts.${cycle}`" v-slot="{ field }">
                <select v-bind="field"
                  class="border rounded-md px-3 py-1 text-sm bg-white dark:bg-gray-600 dark:border-gray-500 dark:text-white"
                  @change="() => calculatePeriodPrices(values.monthlyPrice, values.discounts)">
                  <option disabled value="">{{ t('common.select') }}</option>
                  <option v-for="option in options" :key="option._id" :value="option._id">
                    {{ option?.discount }}%
                  </option>
                </select>
              </Field>
            </div>
            <FormInput :model-value="periodPrices[cycle]" type="number"
              :label="t('apply.pricing.total' + cycle.charAt(0).toUpperCase() + cycle.slice(1) + 'Price')"
              :placeholder="t('apply.pricing.calculating')" readonly />
          </div>
        </div>
      </div>
    </section>

    <section class="pt-8 border-t border-gray-200 dark:border-gray-700">
      <div class="flex items-start">
        <Field name="acceptTerms" type="checkbox" :value="true" :unchecked-value="false"
          v-slot="{ field, errorMessage, meta }">
          <div class="flex items-start mt-2">
            <div class="flex items-center h-5">
              <input type="checkbox" id="accept-terms" v-bind="field"
                class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500" />
            </div>
            <div class="ml-3 text-sm">
              <label for="accept-terms" class="font-medium text-gray-700 dark:text-gray-300">{{
                t('apply.legal.acceptTerms') }}</label>
              <div v-if="(meta.touched || meta.dirty) && errorMessage"
                class="text-sm form-error text-error-600 dark:text-error-400 mt-1">{{
                  errorMessage }}</div>
            </div>
          </div>
        </Field>
      </div>

      <Field name="confirmAge" type="checkbox" :value="true" :unchecked-value="false"
        v-slot="{ field, errorMessage, meta }" class="mt-4">
        <div class="flex items-start mt-2">
          <div class="flex items-center h-5">
            <input type="checkbox" id="confirm-age" v-bind="field"
              class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500" />
          </div>
          <div class="ml-3 text-sm">
            <label for="confirm-age" class="font-medium text-gray-700 dark:text-gray-300">{{ t('apply.legal.confirmAge')
            }}</label>
            <div v-if="(meta.touched || meta.dirty) && errorMessage"
              class="text-sm form-error text-error-600 dark:text-error-400 mt-1">
              {{ errorMessage }}
            </div>
          </div>
        </div>
      </Field>
    </section>

    <div class="pt-6 flex justify-end">
      <button type="submit" :disabled="!meta.valid || isSubmitting"
        class="w-full sm:w-auto px-6 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 transition-colors flex items-center justify-center gap-2"
        :class="{
          'bg-primary-600 text-white hover:bg-primary-700': meta.valid && !isSubmitting,
          'bg-primary-500 text-white cursor-wait': isSubmitting,
          'bg-gray-300 text-gray-500 cursor-not-allowed': !meta.valid
        }">
        <template v-if="isSubmitting">
          <Icon name="lucide:loader-2" class="h-5 w-5 animate-spin" />
          <span>{{ t('apply.processing') }}</span>
        </template>
        <template v-else>
          <Icon name="lucide:send" class="h-5 w-5" />
          <span>{{ t('apply.button') }}</span>
        </template>
      </button>
    </div>
  </Form>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { Form, Field, ErrorMessage, useForm } from 'vee-validate';
import * as yup from 'yup';
import FormInput from '../ui/BaseInput.vue';
import { createCreatorApi } from '@whispers/api';
import { useNotification } from '../../composables/useNotifications';

const { t } = useI18n();
const notification = useNotification();

interface SocialFields {
  facebook: string;
  instagram: string;
  twitter: string;
  tiktok: string;
}

interface FormValues {
  displayName: string;
  username: string;
  bio: string;
  categories: string[];
  social: SocialFields;
  monthlyPrice: number;
  discounts: Record<string, string>;
  acceptTerms: boolean;
  confirmAge: boolean;
  socialTouched: boolean;
}

const applyFormSchema = yup.object({
  displayName: yup.string()
    .required(t('validation.displayNameRequired'))
    .min(2, t('validation.displayNameMin'))
    .max(50, t('validation.displayNameMax')),
  username: yup.string()
    .required(t('validation.usernameRequired'))
    .min(3, t('validation.usernameMin'))
    .max(30, t('validation.usernameMax'))
    .matches(/^[a-zA-Z0-9_-]+$/, t('validation.usernamePattern')),
  bio: yup.string()
    .required(t('validation.bioRequired'))
    .min(10, t('validation.bioMin'))
    .max(500, t('validation.bioMax')),
  categories: yup.array().of(yup.string()).min(1, t('apply.basicInfo.required')).required(),
  social: yup.object({
    facebook: yup.string(),
    instagram: yup.string(),
    twitter: yup.string(),
    tiktok: yup.string(),
  }).test(
    'at-least-one',
    t('validation.atLeastOneSocial'),
    function (value) {
      if (!this.parent.socialTouched) return true;
      return Object.values(value || {}).some(val => val?.trim());
    }
  ),
  socialTouched: yup.boolean().default(false),
  monthlyPrice: yup.number().required().min(4.99),
  discounts: yup.object(),
  acceptTerms: yup.boolean().oneOf([true], t('apply.basicInfo.required')),
  confirmAge: yup.boolean().oneOf([true], t('apply.basicInfo.required'))
});

const isSubmitting = ref(false);
const { handleSubmit, meta: formMeta, setTouched, setFieldValue } = useForm<FormValues>({
  validationSchema: applyFormSchema,
  initialValues: {
    displayName: '',
    username: '',
    bio: '',
    categories: [],
    social: {
      facebook: '',
      instagram: '',
      twitter: '',
      tiktok: ''
    },
    monthlyPrice: 4.99,
    discounts: {},
    acceptTerms: false,
    confirmAge: false,
    socialTouched: false
  },
});

const availableCategories = computed(() => [
  t('categories.art'),
  t('categories.music'),
  t('categories.photography'),
  t('categories.writing'),
  t('categories.technology'),
  t('categories.education'),
  t('categories.entertainment'),
  t('categories.lifestyle'),
  t('categories.sports'),
  t('categories.gaming')
]);

function toggleCategory(category: string, currentCategories: string[], handleChange: (categories: string[]) => void) {
  const newCategories = currentCategories.includes(category)
    ? currentCategories.filter((c: string) => c !== category)
    : [...currentCategories, category];
  handleChange(newCategories);
}

function removeCategory(category: string, currentCategories: string[], handleChange: (categories: string[]) => void) {
  handleChange(currentCategories.filter((c: string) => c !== category));
}

const creatorApi = createCreatorApi();

const pricingPreferences = ref<any[]>([]);
const preferencesByCycle = computed<Record<string, any[]>>(() => {
  const grouped: Record<string, any[]> = {};
  for (const pref of pricingPreferences.value) {
    if (!grouped[pref.cycle]) grouped[pref.cycle] = [];
    grouped[pref.cycle].push(pref);
  }
  return grouped;
});

const periodPrices = ref<Record<string, number>>({});

onMounted(async () => {
  try {
    const { data } = await creatorApi.getCreatorPreferences();
    pricingPreferences.value = data;
    for (const cycle in preferencesByCycle.value) {
      if (!preferencesByCycle.value[cycle]) continue;
      const zeroDiscount = preferencesByCycle.value[cycle].find((opt: any) => opt.discount === 0);
      if (zeroDiscount) {
        setFieldValue(`discounts.${cycle}`, zeroDiscount._id);
      } else if (preferencesByCycle.value[cycle][0]) {
        setFieldValue(`discounts.${cycle}`, preferencesByCycle.value[cycle][0]._id);
      }
    }
  } catch (e) {
    notification.error(t('notifications.preferencesFailed'));
  }
});

const initialValues = {
  displayName: '',
  username: '',
  bio: '',
  categories: [],
  social: {
    facebook: '',
    instagram: '',
    twitter: '',
    tiktok: ''
  },
  monthlyPrice: 4.99,
  discounts: {},
  acceptTerms: false,
  confirmAge: false
};

const onSocialBlur = (setFieldValue: (field: keyof FormValues, value: any) => void) => {
  setFieldValue('socialTouched', true);
  setTouched({
    'social.facebook': true,
    'social.instagram': true,
    'social.twitter': true,
    'social.tiktok': true
  });
};

function calculatePeriodPrices(monthlyPrice: number, discounts: Record<string, string>) {
  for (const cycle in discounts) {
    if (!preferencesByCycle.value[cycle]) continue;
    const selectedId = discounts[cycle];
    const option = preferencesByCycle.value[cycle]?.find((opt: any) => opt._id === selectedId);
    if (option) {
      let multiplier = 1;
      if (cycle === 'quarterly') multiplier = 3;
      if (cycle === 'yearly') multiplier = 12;
      periodPrices.value[cycle] = Math.round(monthlyPrice * multiplier * (1 - option.discount / 100) * 100) / 100;
    }
  }
}

async function onSubmit(values: FormValues, { resetForm }: { resetForm: () => void }) {
  try {
    isSubmitting.value = true;
    const allowedPlatforms = ['facebook', 'instagram', 'twitter', 'tiktok', 'youtube'] as const;
    const socialUrlMap = {
      facebook: (username: string) => `https://facebook.com/${username}`,
      instagram: (username: string) => `https://instagram.com/${username}`,
      twitter: (username: string) => `https://twitter.com/${username}`,
      tiktok: (username: string) => `https://tiktok.com/@${username}`,
      youtube: (username: string) => `https://youtube.com/${username}`,
    };
    const payload = {
      displayName: values.displayName,
      username: values.username,
      bio: values.bio,
      categories: values.categories,
      socialMedia: Object.entries(values.social)
        .filter(([platform, username]) => allowedPlatforms.includes(platform as any) && username && username.trim())
        .map(([platform, username]) => ({
          platform: platform as typeof allowedPlatforms[number],
          url: socialUrlMap[platform as keyof typeof socialUrlMap](username),
        })),
      pricing: {
        amount: values.monthlyPrice,
        models: Object.keys(preferencesByCycle.value).map((cycle) => {
          return values.discounts[cycle] || preferencesByCycle.value[cycle][0]?._id;
        }),
      },
      legal: {
        termsOfService: values.acceptTerms,
        legallyAnAdult: values.confirmAge,
        contentGuidelines: values.acceptTerms,
      },
    };
    await creatorApi.createCreator(payload);
    notification.success(t('notifications.applicationSubmitted'));

    resetForm();

    for (const cycle in preferencesByCycle.value) {
      if (!preferencesByCycle.value[cycle]) continue;
      const zeroDiscount = preferencesByCycle.value[cycle].find((opt: any) => opt.discount === 0);
      if (zeroDiscount) {
        setFieldValue(`discounts.${cycle}`, zeroDiscount._id);
      } else if (preferencesByCycle.value[cycle][0]) {
        setFieldValue(`discounts.${cycle}`, preferencesByCycle.value[cycle][0]._id);
      }
    }

    calculatePeriodPrices(initialValues.monthlyPrice, initialValues.discounts);

    calculatePeriodPrices(initialValues.monthlyPrice, initialValues.discounts);
  } catch (error: any) {
    const apiError =
      error?.response?.data?.error ||
      error?.response?.data?.message ||
      error?.message ||
      t('notifications.applicationFailed');
    notification.error(apiError);
  } finally {
    isSubmitting.value = false;
  }
}
</script>
