// apps/creator/pages/messages/index.vue
<template>
  <div class="container mx-auto max-w-6xl">
    <div>
      <h1 class="text-2xl font-bold mb-6 dark:text-white">Messages</h1>
      
      <div class="bg-white dark:bg-gray-900 rounded-lg shadow-sm">
        <div class="grid grid-cols-1 md:grid-cols-3">
          <!-- Conversations list -->
          <div class="border-r border-gray-200 dark:border-gray-700">
            <div class="p-4 border-b border-gray-200 dark:border-gray-700">
              <FormInput
                v-model="searchQuery"
                placeholder="Search messages..."
                icon="lucide:search"
                class="dark:bg-gray-800 dark:text-white"
              />
            </div>
            
            <div class="divide-y divide-gray-200 dark:divide-gray-700 max-h-[600px] overflow-y-auto">
              <div
                v-for="chat in filteredChats"
                :key="chat.id"
                class="p-4 hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer"
                :class="{ 'bg-primary-50 dark:bg-primary-900/40': selectedChat?.id === chat.id }"
                @click="selectChat(chat)"
              >
                <div class="flex items-center space-x-3">
                  <div class="avatar h-10 w-10">
                    <img
                      :src="chat.user.avatar"
                      :alt="chat.user.name"
                      class="h-full w-full object-cover"
                    />
                  </div>
                  <div class="flex-1 min-w-0">
                    <div class="flex items-center justify-between">
                      <p class="text-sm font-medium text-gray-900 dark:text-white truncate">
                        {{ chat.user.name }}
                      </p>
                      <p class="text-xs text-gray-500 dark:text-gray-300">
                        {{ formatTime(chat.lastMessage.timestamp) }}
                      </p>
                    </div>
                    <p class="text-sm text-gray-500 dark:text-gray-300 truncate">
                      {{ chat.lastMessage.content }}
                    </p>
                  </div>
                </div>
                <div v-if="chat.unreadCount > 0" class="mt-1 flex items-center justify-end">
                  <span class="bg-primary-500 text-white text-xs px-2 py-0.5 rounded-full">
                    {{ chat.unreadCount }}
                  </span>
                </div>
              </div>
              
              <div v-if="filteredChats.length === 0" class="p-8 text-center text-gray-500 dark:text-gray-300">
                No messages found
              </div>
            </div>
          </div>

          <!-- Chat window -->
          <div class="col-span-2 flex flex-col h-[600px] dark:bg-gray-900">
            <template v-if="selectedChat">
              <!-- Chat header -->
              <div class="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="avatar h-10 w-10">
                    <img
                      :src="selectedChat.user.avatar"
                      :alt="selectedChat.user.name"
                      class="h-full w-full object-cover"
                    />
                  </div>
                  <div>
                    <h2 class="text-lg font-medium dark:text-white">{{ selectedChat.user.name }}</h2>
                    <p class="text-sm text-gray-500 dark:text-gray-300">
                      {{ selectedChat.user.isOnline ? 'Online' : 'Offline' }}
                    </p>
                  </div>
                </div>
                <button class="text-gray-400 hover:text-gray-600 dark:text-gray-300 dark:hover:text-white">
                  <Icon name="lucide:more-vertical" class="h-5 w-5" />
                </button>
              </div>

              <!-- Messages -->
              <div class="flex-1 overflow-y-auto p-4 space-y-4 dark:bg-gray-900">
                <div
                  v-for="message in selectedChat.messages"
                  :key="message.id"
                  class="flex"
                  :class="message.isSelf ? 'justify-end' : 'justify-start'"
                >
                  <div
                    class="max-w-[70%] rounded-lg px-4 py-2"
                    :class="message.isSelf ? 'bg-primary-500 text-white dark:bg-primary-600' : 'bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-100'"
                  >
                    <!-- Media preview: support multiple media per message -->
                    <div v-if="message.media && (Array.isArray(message.media) ? message.media.length : true)" class="mb-2 flex gap-2 flex-wrap">
                      <template v-if="Array.isArray(message.media)">
                        <div v-for="(media, idx) in message.media" :key="idx">
                          <img
                            v-if="media.type === 'image'"
                            :src="media.url"
                            :alt="message.content"
                            class="rounded-lg max-h-48 cursor-pointer dark:border dark:border-gray-700"
                            @click="openMediaPreviewForChat(media, message.id)"
                          />
                          <video
                            v-else-if="media.type === 'video'"
                            :src="media.url"
                            controls
                            controlsList="nodownload"
                            class="rounded-lg max-h-48 w-full cursor-pointer dark:border dark:border-gray-700"
                            @click="openMediaPreviewForChat(media, message.id)"
                          ></video>
                        </div>
                      </template>
                      <template v-else>
                        <img
                          v-if="message.media.type === 'image'"
                          :src="message.media.url"
                          :alt="message.content"
                          class="rounded-lg max-h-48 cursor-pointer dark:border dark:border-gray-700"
                          @click="openMediaPreviewForChat(message.media, message.id)"
                        />
                        <video
                          v-else-if="message.media.type === 'video'"
                          :src="message.media.url"
                          controls
                          controlsList="nodownload"
                          class="rounded-lg max-h-48 w-full cursor-pointer dark:border dark:border-gray-700"
                          @click="openMediaPreviewForChat(message.media, message.id)"
                        ></video>
                      </template>
                    </div>
                    <p class="text-sm dark:text-gray-100">{{ message.content }}</p>
                    <div class="flex items-center justify-end mt-1 space-x-1">
                      <p class="text-xs opacity-70 dark:text-gray-300">
                        {{ formatTime(message.timestamp) }}
                      </p>
                      <!-- Read receipt -->
                      <Icon
                        v-if="message.isSelf"
                        :name="message.isRead ? 'lucide:check-check' : 'lucide:check'"
                        class="h-4 w-4"
                        :class="message.isRead ? 'text-accent-500' : 'opacity-70'"
                      />
                    </div>
                  </div>
                </div>
                
                <!-- Typing indicator -->
                <div
                  v-if="selectedChat.isTyping"
                  class="flex items-center space-x-2 text-gray-500 dark:text-gray-300"
                >
                  <div class="flex space-x-1">
                    <div class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce"></div>
                    <div class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce" style="animation-delay: 0.2s"></div>
                    <div class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce" style="animation-delay: 0.4s"></div>
                  </div>
                  <span class="text-sm">{{ selectedChat.user.name }} is typing...</span>
                </div>
              </div>

              <!-- Message input -->
              <div class="p-4 border-t border-gray-200 dark:border-gray-700 dark:bg-gray-900">
                <form @submit.prevent="sendMessage" class="space-y-4">
                  <!-- Media preview -->
                  <div v-if="mediaPreview.length > 0" class="flex space-x-2 overflow-x-auto pb-2">
                    <div
                      v-for="(media, index) in mediaPreview"
                      :key="index"
                      class="relative flex-shrink-0"
                    >
                      <img
                        v-if="media.type === 'image'"
                        :src="media.preview"
                        class="h-20 w-20 object-cover rounded-lg dark:border dark:border-gray-700"
                      />
                      <video
                        v-else-if="media.type === 'video'"
                        :src="media.preview"
                        controlsList="nodownload"
                        class="h-20 w-20 object-cover rounded-lg dark:border dark:border-gray-700"
                      ></video>
                      <button
                        @click="removeMedia(index)"
                        class="absolute -top-2 -right-2 bg-error-100 dark:bg-error-900 rounded-full p-1 text-error-600 dark:text-error-200 hover:bg-error-200 dark:hover:bg-error-800"
                      >
                        <Icon name="lucide:x" class="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                  
                  <div class="flex space-x-2">
                    <FormInput
                      v-model="newMessage"
                      placeholder="Type a message..."
                      class="flex-1 dark:bg-gray-800 dark:text-white"
                      @input="handleTyping"
                    />
                    
                    <!-- Media upload buttons -->
                    <div class="flex space-x-2">
                      <input
                        ref="imageInput"
                        type="file"
                        accept="image/*"
                        multiple
                        class="hidden"
                        @change="handleImageUpload"
                      />
                      <input
                        ref="videoInput"
                        type="file"
                        accept="video/*"
                        class="hidden"
                        @change="handleVideoUpload"
                      />
                      
                      <button
                        type="button"
                        class="p-2 text-gray-500 dark:text-gray-200 hover:text-primary-600 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full"
                        @click="$refs.imageInput.click()"
                      >
                        <Icon name="lucide:image" class="h-5 w-5" />
                      </button>
                      <button
                        type="button"
                        class="p-2 text-gray-500 dark:text-gray-200 hover:text-primary-600 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full"
                        @click="$refs.videoInput.click()"
                      >
                        <Icon name="lucide:video" class="h-5 w-5" />
                      </button>
                    </div>
                    
                    <button type="submit" class="btn-primary">
                      <Icon name="lucide:send" class="h-5 w-5" />
                    </button>
                  </div>
                </form>
              </div>
            </template>

            <div v-else class="flex-1 flex items-center justify-center text-gray-500 dark:text-gray-300">
              <div class="text-center">
                <Icon name="lucide:message-square" class="h-12 w-12 mx-auto mb-2" />
                <p>Select a conversation to start messaging</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Media preview modal -->
    <MediaPreviewModal
      v-if="mediaModal.isOpen"
      :isOpen="mediaModal.isOpen"
      :mediaItems="mediaModal.mediaItems"
      :currentIndex="mediaModal.currentIndex"
      @close="closeMediaPreview"
      @update:currentIndex="val => mediaModal.currentIndex = val"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue';
import FormInput from '@/components/ui/FormInput.vue'
import MediaPreviewModal from '@/components/ui/MediaPreviewModal.vue';

definePageMeta({
  middleware: ['auth'],
  layout: 'creator',
  meta: {
    requiresAuth: true
  }
});

interface User {
  name: string;
  avatar: string;
  isOnline: boolean;
}

interface MediaItem {
  type: 'image' | 'video';
  url: string;
  preview?: string;
  file?: File;
  _msgId?: string;
}

interface Message {
  id: string;
  content: string;
  timestamp: Date;
  isSelf: boolean;
  isRead: boolean;
  media?: MediaItem | MediaItem[];
}

interface Chat {
  id: string;
  user: User;
  lastMessage: {
    content: string;
    timestamp: Date;
  };
  unreadCount: number;
  isTyping: boolean;
  messages: Message[];
}

interface MediaModal {
  isOpen: boolean;
  mediaItems?: MediaItem[];
  currentIndex?: number;
  type?: string | null;
  url?: string | null;
}

const searchQuery = ref<string>('');
const selectedChat = ref<Chat | null>(null);
const newMessage = ref<string>('');
const typingTimeout = ref<ReturnType<typeof setTimeout> | null>(null);
const mediaPreview = ref<MediaItem[]>([]);
const mediaModal = ref<MediaModal>({
  isOpen: false,
  type: null,
  url: null
});

// Mock data for chats
const chats = ref<Chat[]>([
  {
    id: '1',
    user: {
      name: 'Jane Smith',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
      isOnline: true
    },
    lastMessage: {
      content: 'Thank you for subscribing!',
      timestamp: new Date(Date.now() - 5 * 60 * 1000)
    },
    unreadCount: 2,
    isTyping: false,
    messages: [
      {
        id: '1',
        content: 'Hi there! Thanks for checking out my content',
        timestamp: new Date(Date.now() - 30 * 60 * 1000),
        isSelf: false,
        isRead: true
      },
      {
        id: '2',
        content: 'Your latest post was amazing!',
        timestamp: new Date(Date.now() - 25 * 60 * 1000),
        isSelf: true,
        isRead: true
      },
      {
        id: '3',
        content: 'Thank you for subscribing!',
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
        isSelf: false,
        isRead: false,
        media: {
          type: 'image',
          url: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'
        }
      }
    ]
  },
  {
    id: '2',
    user: {
      name: 'Mike Johnson',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
      isOnline: false
    },
    lastMessage: {
      content: 'Check out my new photo collection!',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000)
    },
    unreadCount: 0,
    isTyping: false,
    messages: [
      {
        id: '1',
        content: 'Hey! I just posted a new photo collection',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
        isSelf: false,
        isRead: true
      },
      {
        id: '2',
        content: 'Check out my new photo collection!',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        isSelf: false,
        isRead: true,
        media: {
          type: 'video',
          url: 'https://player.vimeo.com/external/394678700.sd.mp4?s=353646b8d6a0da48b40f6a3fe0e8f09797c1f5dd&profile_id=165&oauth2_token_id=57447761'
        }
      }
    ]
  }
]);

// Computed
const filteredChats = computed<Chat[]>(() => {
  if (!searchQuery.value) return chats.value;
  
  const query = searchQuery.value.toLowerCase();
  return chats.value.filter((chat: Chat) => 
    chat.user.name.toLowerCase().includes(query) ||
    chat.lastMessage.content.toLowerCase().includes(query)
  );
});

const allChatMedia = computed<MediaItem[]>(() => {
  if (!selectedChat.value) return [];
  const mediaList: MediaItem[] = [];
  selectedChat.value.messages.forEach((msg: Message) => {
    if (msg.media) {
      if (Array.isArray(msg.media)) {
        (msg.media as MediaItem[]).forEach((m: MediaItem) => mediaList.push({ ...m, _msgId: msg.id }));
      } else {
        mediaList.push({ ...(msg.media as MediaItem), _msgId: msg.id });
      }
    }
  });
  return mediaList;
});

// Methods
function formatTime(date: Date | string): string {
  const now = new Date();
  const d = new Date(date);
  const diff = now.getTime() - d.getTime();
  
  const minutes = Math.floor(diff / (1000 * 60));
  const hours = Math.floor(diff / (1000 * 60 * 60));
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  
  if (minutes < 60) {
    return `${minutes}m ago`;
  } else if (hours < 24) {
    return `${hours}h ago`;
  } else if (days < 7) {
    return `${days}d ago`;
  } else {
    return d.toLocaleDateString();
  }
}

function selectChat(chat: Chat): void {
  selectedChat.value = chat;
  // Mark messages as read
  chat.unreadCount = 0;
  chat.messages.forEach((message: Message) => {
    if (!message.isSelf) {
      message.isRead = true;
    }
  });
}

function handleTyping() {
  if (typingTimeout.value) {
    clearTimeout(typingTimeout.value);
  }
  
  // Emit typing event
  // In a real app, this would be sent to the server
  
  typingTimeout.value = setTimeout(() => {
    // Stop typing
    // In a real app, this would be sent to the server
  }, 3000);
}

async function handleImageUpload(event: Event) {
  const input = event.target as HTMLInputElement;
  const files = Array.from(input.files || []);
  
  for (const file of files) {
    if (file.type.startsWith('image/')) {
      const preview = URL.createObjectURL(file);
      mediaPreview.value.push({
        file,
        type: 'image',
        preview
      });
    }
  }
  input.value = '';
}

async function handleVideoUpload(event: Event) {
  const input = event.target as HTMLInputElement;
  const file = input.files ? input.files[0] : undefined;
  
  if (file && file.type.startsWith('video/')) {
    const preview = URL.createObjectURL(file);
    mediaPreview.value.push({
      file,
      type: 'video',
      preview
    });
  }
  input.value = '';
}

function removeMedia(index: number) {
  const media = mediaPreview.value[index];
  if (media && media.preview) {
    URL.revokeObjectURL(media.preview);
  }
  mediaPreview.value.splice(index, 1);
}

function openMediaPreviewForChat(media: MediaItem, msgId: string) {
  const allMedia = allChatMedia.value;
  let globalIdx = 0;
  let found = false;
  for (let i = 0; i < allMedia.length; i++) {
    if (
      allMedia[i].url === media.url &&
      allMedia[i].type === media.type &&
      allMedia[i]._msgId === msgId
    ) {
      globalIdx = i;
      found = true;
      break;
    }
  }
  if (!found) globalIdx = 0;
  mediaModal.value = {
    isOpen: true,
    mediaItems: allMedia,
    currentIndex: globalIdx
  };
}

function closeMediaPreview() {
  mediaModal.value.isOpen = false;
}

async function sendMessage() {
  if (!newMessage.value.trim() && mediaPreview.value.length === 0) return;

  try {
    // In a real app, upload media files to server and get URLs
    const mediaUrls = mediaPreview.value.map(media => ({
      type: media.type,
      url: media.preview // In real app, this would be the uploaded file URL
    }));

    const message = {
      id: `msg-${Date.now()}`,
      content: newMessage.value,
      timestamp: new Date(),
      isSelf: true,
      isRead: false
    };

    if (mediaUrls.length > 0) {
      message.media = mediaUrls; // Assign all media
    }

    selectedChat.value.messages.push(message);
    selectedChat.value.lastMessage = {
      content: newMessage.value || 'Sent a media file',
      timestamp: new Date()
    };

    newMessage.value = '';
    mediaPreview.value = [];

    // Simulate other user typing
    setTimeout(() => {
      selectedChat.value.isTyping = true;

      setTimeout(() => {
        selectedChat.value.isTyping = false;

        // Simulate response
        selectedChat.value.messages.push({
          id: `msg-${Date.now()}`,
          content: 'Thanks for your message!',
          timestamp: new Date(),
          isSelf: false,
          isRead: true
        });
      }, 3000);
    }, 1000);
  } catch (error) {
    console.error('Failed to send message:', error);
  }
}

// Cleanup
onUnmounted(() => {
  mediaPreview.value.forEach(media => {
    URL.revokeObjectURL(media.preview);
  });
});
</script>

// apps/creator-next-app/app/(dashboard)/creator/messages/page.tsx
"use client"

import { useState, useEffect, useRef } from "react"
import { useTranslation } from "react-i18next"
import { ChatList } from "@/components/messages/chat-list"
import { ChatWindow } from "@/components/messages/chat-window"
import { MediaPreviewModal } from "@/components/messages/media-preview-modal"

interface User {
  id: string
  name: string
  avatar: string
  isOnline: boolean
  lastSeen?: Date
}

interface Media {
  type: "image" | "video" | "voice"
  url: string
  duration?: string
}

interface Message {
  id: string
  content: string
  timestamp: Date
  isSelf: boolean
  isRead: boolean
  isDelivered: boolean
  type: "text" | "voice" | "image" | "video"
  media?: Media
  voiceDuration?: string
  voiceProgress?: number
  isPlaying?: boolean
  isEdited?: boolean
  reactions?: Array<{
    emoji: string
    count: number
    users: string[]
  }>
  replyTo?: {
    messageId: string
    senderName: string
    content: string
  }
}

interface Chat {
  id: string
  user: User
  lastMessage: {
    content: string
    timestamp: Date
    type: string
    isSelf: boolean
    isRead: boolean
    isDelivered: boolean
  }
  unreadCount: number
  isTyping: boolean
  messages: Message[]
}

interface MediaPreview {
  file?: File
  type: "image" | "video" | "voice"
  preview?: string
  duration?: string
}

export default function CreatorMessagesPage() {
  const { t } = useTranslation()
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
  }, [])

  const [selectedChat, setSelectedChat] = useState<Chat | null>(null)
  const [searchQuery, setSearchQuery] = useState("")
  const [mediaPreview, setMediaPreview] = useState<MediaPreview[]>([])
  const [showChatMenu, setShowChatMenu] = useState(false)
  const [showReactionPicker, setShowReactionPicker] = useState<string | null>(null)
  const [replyingTo, setReplyingTo] = useState<{
    messageId: string
    senderName: string
    content: string
  } | null>(null)
  const [isRecording, setIsRecording] = useState(false)
  const [recordingDuration, setRecordingDuration] = useState(0)
  const [recordingInterval, setRecordingInterval] = useState<NodeJS.Timeout | null>(null)
  const [newMessage, setNewMessage] = useState("")
  const [mediaModal, setMediaModal] = useState({
    isOpen: false,
    mediaItems: [] as Media[],
    currentIndex: 0,
  })

  const audioRefs = useRef<Record<string, HTMLAudioElement>>({})
  const currentUser = { id: "currentUser", name: "You" }
  const allCommentsForModal: Message[] = []

  // Quick reactions
  const quickReactions = ["👍", "❤️", "😂", "😮", "😢"]

  // Mock data
  const [recentChats] = useState([
    {
      id: "1",
      user: {
        id: "user1",
        name: "Jane Smith",
        avatar: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200",
        isOnline: true,
      },
    },
    {
      id: "2",
      user: {
        id: "user2",
        name: "Mike Johnson",
        avatar: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200",
        isOnline: false,
      },
    },
    {
      id: "3",
      user: {
        id: "user3",
        name: "Sarah Wilson",
        avatar: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200",
        isOnline: true,
      },
    },
  ])

  const [chats] = useState<Chat[]>([
    {
      id: "1",
      user: {
        id: "user1",
        name: "Jane Smith",
        avatar: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200",
        isOnline: true,
      },
      lastMessage: {
        content: "Thank you for subscribing! 🎉",
        timestamp: new Date(Date.now() - 7 * 60 * 1000),
        type: "text",
        isSelf: false,
        isRead: false,
        isDelivered: true,
      },
      unreadCount: 2,
      isTyping: false,
      messages: [
        {
          id: "1",
          content: "Your latest post was amazing!",
          timestamp: new Date(Date.now() - 27 * 60 * 1000),
          isSelf: true,
          isRead: true,
          isDelivered: true,
          type: "text",
          reactions: [],
        },
        {
          id: "2",
          content: "",
          timestamp: new Date(Date.now() - 4 * 60 * 1000),
          isSelf: true,
          isRead: true,
          isDelivered: true,
          type: "voice",
          voiceDuration: "0:00",
          voiceProgress: 0,
          isPlaying: false,
          reactions: [],
        },
        {
          id: "3",
          content: "Thank you for subscribing! 🎉",
          timestamp: new Date(Date.now() - 7 * 60 * 1000),
          isSelf: false,
          isRead: false,
          isDelivered: true,
          type: "image",
          media: {
            type: "image",
            url: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          },
          reactions: [
            { emoji: "❤️", count: 2, users: ["user1", "currentUser"] },
            { emoji: "👍", count: 1, users: ["user2"] },
          ],
        },
        {
          id: "4",
          content: "",
          timestamp: new Date(Date.now() - 3 * 60 * 1000),
          isSelf: false,
          isRead: false,
          isDelivered: true,
          type: "video",
          media: {
            type: "video",
            url: "https://player.vimeo.com/external/394678700.sd.mp4?s=353646b8d6a0da48b40f6a3fe0e8f09797c1f5dd&profile_id=165&oauth2_token_id=57447761",
          },
          reactions: [],
        },
        {
          id: "5",
          content: "😊😊",
          timestamp: new Date(Date.now() - 1 * 60 * 1000),
          isSelf: true,
          isRead: false,
          isDelivered: true,
          type: "text",
          reactions: [],
        },
      ],
    },
    {
      id: "2",
      user: {
        id: "user2",
        name: "Mike Johnson",
        avatar: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200",
        isOnline: false,
        lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      lastMessage: {
        content: "Voice message",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        type: "voice",
        isSelf: false,
        isRead: true,
        isDelivered: true,
      },
      unreadCount: 0,
      isTyping: false,
      messages: [
        {
          id: "1",
          content: "",
          timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
          isSelf: false,
          isRead: true,
          isDelivered: true,
          type: "voice",
          voiceDuration: "0:15",
          voiceProgress: 0,
          isPlaying: false,
          reactions: [],
        },
      ],
    },
  ])

  // Handle URL parameters for direct messaging from subscribers
  useEffect(() => {
    if (isClient) {
      const urlParams = new URLSearchParams(window.location.search)
      const targetUser = urlParams.get('user')
      const targetUserId = urlParams.get('userId')
      
      if (targetUser && targetUserId) {
        // Find or create a chat with the target user
        const targetChat = chats.find(chat => chat.user.id === targetUserId)
        if (targetChat) {
          setSelectedChat(targetChat)
        } else {
          // Create a new chat if it doesn't exist
          const newChat: Chat = {
            id: targetUserId,
            user: {
              id: targetUserId,
              name: targetUser,
              avatar: `/placeholder.svg`,
              isOnline: false,
            },
            lastMessage: {
              content: "",
              timestamp: new Date(),
              type: "text",
              isSelf: false,
              isRead: true,
              isDelivered: true,
            },
            unreadCount: 0,
            isTyping: false,
            messages: [],
          }
          setSelectedChat(newChat)
        }
        
        // Clear the URL parameters
        const newUrl = window.location.pathname
        window.history.replaceState({}, '', newUrl)
      }
    }
  }, [isClient, chats])

  const filteredChats = chats.filter((chat) => {
    if (!searchQuery) return true
    const query = searchQuery.toLowerCase()
    return (
      chat.user.name.toLowerCase().includes(query) ||
      chat.lastMessage.content.toLowerCase().includes(query)
    )
  })

  const canSendMessage = newMessage.trim() || mediaPreview.length > 0

  const formatTime = (date: Date): string => {
    const now = new Date()
    const d = new Date(date)
    const diff = now.getTime() - d.getTime()
    const minutes = Math.floor(diff / (1000 * 60))
    const hours = Math.floor(diff / (1000 * 60 * 60))
    const days = Math.floor(diff / (1000 * 60 * 60 * 24))

    if (minutes < 1) return t("messages.now")
    if (minutes < 60) return `${minutes}m`
    if (hours < 24) return `${hours}h`
    if (days < 7) return `${days}d`
    return d.toLocaleDateString()
  }

  const formatMessageContent = (content: string): string => {
    const urlRegex = /(https?:\/\/[^\s]+)/g
    content = content.replace(urlRegex, '<a href="$1" target="_blank" class="text-blue-500 underline">$1</a>')
    return content.replace(/\n/g, "<br>")
  }

  const getLastMessagePreview = (lastMessage: { type: string; content: string }): string => {
    if (lastMessage.type === "voice") return t("messages.voiceMessage")
    if (lastMessage.type === "image") return t("messages.photo")
    if (lastMessage.type === "video") return t("messages.video")
    return lastMessage.content
  }

  const selectChat = (chat: Chat) => {
    const found = chats.find((c) => c.id === chat.id)
    if (found) {
      setSelectedChat(found)
      found.unreadCount = 0
      found.messages.forEach((message) => {
        if (!message.isSelf) message.isRead = true
      })
    }
  }

  const handleTyping = () => {
    // Handle typing indicator
  }

  const handleMediaUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || [])
    files.forEach((file) => {
      if (file.type.startsWith("image/")) {
        const preview = URL.createObjectURL(file)
        setMediaPreview((prev) => [...prev, { file, type: "image", preview }])
      } else if (file.type.startsWith("video/")) {
        const preview = URL.createObjectURL(file)
        setMediaPreview((prev) => [...prev, { file, type: "video", preview }])
      }
    })
    event.target.value = ""
  }

  const removeMedia = (index: number) => {
    const media = mediaPreview[index]
    if (media?.preview) URL.revokeObjectURL(media.preview)
    setMediaPreview((prev) => prev.filter((_, i) => i !== index))
  }

  const startVoiceRecording = () => {
    if (isRecording) return
    setIsRecording(true)
    setRecordingDuration(0)
    const interval = setInterval(() => {
      setRecordingDuration((prev) => prev + 1)
    }, 1000)
    setRecordingInterval(interval)
  }

  const stopVoiceRecording = () => {
    if (!isRecording) return
    setIsRecording(false)
    if (recordingInterval) {
      clearInterval(recordingInterval)
      setRecordingInterval(null)
    }

    setMediaPreview((prev) => [
      ...prev,
      {
        type: "voice",
        duration: `0:${recordingDuration.toString().padStart(2, "0")}`,
      },
    ])
  }

  const toggleVoicePlayback = (message: Message) => {
    const audio = audioRefs.current[message.id]
    if (!audio) return

    if (message.isPlaying) {
      audio.pause()
      message.isPlaying = false
    } else {
      audio.play()
      message.isPlaying = true
    }
  }

  const updateVoiceDuration = (message: Message) => {
    const audio = audioRefs.current[message.id]
    if (audio && audio.duration) {
      const minutes = Math.floor(audio.duration / 60)
      const seconds = Math.floor(audio.duration % 60)
      message.voiceDuration = `${minutes}:${seconds.toString().padStart(2, "0")}`
    }
  }

  const updateVoiceProgress = (message: Message) => {
    const audio = audioRefs.current[message.id]
    if (audio && audio.duration) {
      message.voiceProgress = (audio.currentTime / audio.duration) * 100
    }
  }

  const onVoiceEnded = (message: Message) => {
    message.isPlaying = false
    message.voiceProgress = 0
  }

  const addReaction = (message: Message, emoji: string) => {
    if (!message.reactions) message.reactions = []
    const existingReaction = message.reactions.find((r) => r.emoji === emoji)

    if (existingReaction) {
      if (existingReaction.users.includes("currentUser")) {
        existingReaction.users = existingReaction.users.filter((u) => u !== "currentUser")
        existingReaction.count--
        if (existingReaction.count === 0) {
          message.reactions = message.reactions.filter((r) => r.emoji !== emoji)
        }
      } else {
        existingReaction.users.push("currentUser")
        existingReaction.count++
      }
    } else {
      message.reactions.push({ emoji, count: 1, users: ["currentUser"] })
    }
    setShowReactionPicker(null)
  }

  const toggleReaction = (message: Message, emoji: string) => {
    addReaction(message, emoji)
  }

  const replyToMessage = (message: Message) => {
    setReplyingTo({
      messageId: message.id,
      senderName: message.isSelf ? "You" : selectedChat?.user.name || "",
      content: message.content || "Media message",
    })
  }

  const cancelReply = () => {
    setReplyingTo(null)
  }

  const editMessage = (message: Message) => {
    const newContent = prompt("Edit message:", message.content)
    if (newContent !== null && newContent !== message.content) {
      message.content = newContent
      message.isEdited = true
    }
  }

  const deleteMessage = (message: Message) => {
    if (confirm("Delete this message?")) {
      const index = selectedChat?.messages.findIndex((m) => m.id === message.id)
      if (index !== -1 && index !== undefined && selectedChat) {
        selectedChat.messages.splice(index, 1)
      }
    }
  }

  const clearChat = () => {
    if (selectedChat && confirm("Clear all messages?")) {
      selectedChat.messages = []
      setShowChatMenu(false)
    }
  }

  const blockUser = () => {
    if (confirm("Block this user?")) {
      setShowChatMenu(false)
    }
  }

  const openMediaPreview = (media: Media, msgId: string) => {
    const allMedia = selectedChat?.messages
      .filter((msg) => msg.media)
      .map((msg) => ({ ...msg.media!, _msgId: msg.id })) || []
    const index = allMedia.findIndex((m) => m.url === media.url && m._msgId === msgId)

    setMediaModal({
      isOpen: true,
      mediaItems: allMedia,
      currentIndex: Math.max(0, index),
    })
  }

  const closeMediaPreview = () => {
    setMediaModal({ isOpen: false, mediaItems: [], currentIndex: 0 })
  }

  const updateMediaIndex = (index: number) => {
    setMediaModal((prev) => ({ ...prev, currentIndex: index }))
  }

  const handleNewComment = (comment: string) => {
    // Optionally handle new comment from media preview modal
  }

  const sendMessage = () => {
    if (!canSendMessage || !selectedChat) return

    const mediaUrls = mediaPreview.map((media) => ({
      type: media.type,
      url: media.preview || "",
      duration: media.duration,
    }))

    const message: Message = {
      id: `msg-${Date.now()}`,
      content: newMessage,
      timestamp: new Date(),
      isSelf: true,
      isRead: false,
      isDelivered: true,
      type: mediaUrls.length > 0 ? mediaUrls[0].type : "text",
      replyTo: replyingTo || undefined,
      reactions: [],
    }

    if (mediaUrls.length > 0) {
      message.media = mediaUrls[0]
      if (message.type === "voice") {
        message.voiceDuration = mediaUrls[0].duration
        message.voiceProgress = 0
        message.isPlaying = false
      }
    }

    selectedChat.messages.push(message)
    selectedChat.lastMessage = {
      content: newMessage || getLastMessagePreview({ type: message.type, content: "" }),
      timestamp: new Date(),
      type: message.type,
      isSelf: true,
      isRead: false,
      isDelivered: true,
    }

    // Clear inputs
    setNewMessage("")
    mediaPreview.forEach((media) => {
      if (media.preview) URL.revokeObjectURL(media.preview)
    })
    setMediaPreview([])
    setReplyingTo(null)
  }

  // Show loading skeleton while client-side hydration completes
  if (!isClient) {
    return (
      <div className="container mx-auto max-w-6xl p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">Messages</h2>
        </div>
        <div className="animate-pulse">
          <div className="grid grid-cols-1 lg:grid-cols-4 h-[800px] bg-white dark:bg-gray-900 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
            <div className="lg:col-span-1 border-r border-gray-200 dark:border-gray-700 p-4">
              <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded mb-4"></div>
              <div className="space-y-4">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="flex items-center space-x-3">
                    <div className="w-12 h-12 bg-gray-200 dark:bg-gray-700 rounded-full"></div>
                    <div className="flex-1">
                      <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4 mb-2"></div>
                      <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded w-1/2"></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="lg:col-span-3 bg-gray-50 dark:bg-gray-900"></div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto max-w-6xl">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">Messages</h2>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-4 flex-1 h-[800px] bg-white dark:bg-gray-900 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
        {/* Chat List */}
        <ChatList
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          recentChats={recentChats}
          filteredChats={filteredChats}
          selectedChat={selectedChat}
          onSelectChat={selectChat}
          formatTime={formatTime}
          getLastMessagePreview={getLastMessagePreview}
        />

        {/* Chat Window */}
        <ChatWindow
          selectedChat={selectedChat}
          setSelectedChat={setSelectedChat}
          newMessage={newMessage}
          setNewMessage={setNewMessage}
          mediaPreview={mediaPreview}
          setMediaPreview={setMediaPreview}
          showChatMenu={showChatMenu}
          setShowChatMenu={setShowChatMenu}
          showReactionPicker={showReactionPicker}
          setShowReactionPicker={setShowReactionPicker}
          replyingTo={replyingTo}
          setReplyingTo={setReplyingTo}
          isRecording={isRecording}
          setIsRecording={setIsRecording}
          recordingDuration={recordingDuration}
          setRecordingDuration={setRecordingDuration}
          recordingInterval={recordingInterval}
          setRecordingInterval={setRecordingInterval}
          canSendMessage={canSendMessage}
          quickReactions={quickReactions}
          audioRefs={audioRefs}
          formatTime={formatTime}
          formatMessageContent={formatMessageContent}
          handleTyping={handleTyping}
          handleMediaUpload={handleMediaUpload}
          removeMedia={removeMedia}
          startVoiceRecording={startVoiceRecording}
          stopVoiceRecording={stopVoiceRecording}
          toggleVoicePlayback={toggleVoicePlayback}
          updateVoiceDuration={updateVoiceDuration}
          updateVoiceProgress={updateVoiceProgress}
          onVoiceEnded={onVoiceEnded}
          addReaction={addReaction}
          toggleReaction={toggleReaction}
          replyToMessage={replyToMessage}
          cancelReply={cancelReply}
          editMessage={editMessage}
          deleteMessage={deleteMessage}
          clearChat={clearChat}
          blockUser={blockUser}
          openMediaPreview={openMediaPreview}
          sendMessage={sendMessage}
        />
      </div>

      {/* Media Preview Modal */}
      <MediaPreviewModal
        isOpen={mediaModal.isOpen}
        mediaItems={mediaModal.mediaItems}
        currentIndex={mediaModal.currentIndex}
        messages={allCommentsForModal}
        currentUser={currentUser}
        onClose={closeMediaPreview}
        onUpdateCurrentIndex={updateMediaIndex}
        onSendMessage={handleNewComment}
      />
    </div>
  )
}
