// apps/creator/components/ui/MediaGallery.vue
<template>
	<Modal v-if="isOpen" size="xl" @close="close">
		<div class="w-full max-w-2xl mx-auto p-0">
			<!-- Header -->
			<div class="flex items-center justify-between border-b border-gray-200 dark:border-gray-700 px-6 pt-6 pb-2">
				<h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
					{{ t('mediaLibrary.title') || 'Media' }}
				</h2>
			</div>

			<!-- Tabs -->
			<div class="flex border-b border-gray-200 dark:border-gray-700">
				<button
					v-for="tab in tabs"
					:key="tab.key"
					type="button"
					:class="[
						'flex-1 py-3 text-center font-medium transition',
						activeTab === tab.key
							? 'border-b-2 border-primary-600 dark:border-primary-400 text-primary-600 dark:text-primary-400 bg-white dark:bg-gray-800'
							: 'text-gray-500 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-400'
					]"
					@click="activeTab = tab.key"
				>
					{{ t(tab.label) || (tab.key === 'library' ? 'Media Library' : 'From Device') }}
				</button>
			</div>
      
			<!-- Tab Content -->
			<div class="p-6">
				<!-- Media Library Tab -->
				<div v-if="activeTab === 'library'">
					<div v-if="loading" class="flex justify-center items-center py-8">
						<Icon name="lucide:loader-2" class="animate-spin h-6 w-6 text-primary-600 dark:text-primary-400" />
					</div>
					<div v-else-if="filteredMedia.length === 0" class="text-center text-gray-500 dark:text-gray-400 py-8">
						{{ t('mediaLibrary.noMedia') || 'No media found' }}
					</div>
					<div v-else class="grid grid-cols-2 sm:grid-cols-3 gap-4">
						<div
							v-for="media in filteredMedia"
							:key="media.id"
							:class="[
								'relative rounded-lg border transition cursor-pointer overflow-hidden',
								selectedIds.includes(media.id)
									? 'border-primary-600 dark:border-primary-400 ring-2 ring-primary-500 dark:ring-primary-400'
									: 'border-gray-200 dark:border-gray-700 hover:border-primary-400 dark:hover:border-primary-400'
							]"
							@click="toggleSelect(media)"
						>
							<img v-if="media.type === 'image'" :src="media.url" class="w-full h-32 object-cover" />
							<div v-else-if="media.type === 'video'" class="relative w-full h-32">
								<video :src="media.url" class="w-full h-full object-cover" />
								<div class="absolute inset-0 flex items-center justify-center">
									<div class="bg-black/50 rounded-full p-2">
										<Icon name="lucide:play" class="h-5 w-5 text-white" />
									</div>
								</div>
								<div v-if="media.duration" class="absolute bottom-1 right-1 bg-black/70 text-white text-xs px-1.5 py-0.5 rounded">
									{{ formatDuration(media.duration) }}
								</div>
							</div>
							<div v-if="selectedIds.includes(media.id)" class="absolute top-2 left-2 bg-primary-600 dark:bg-primary-400 text-white rounded-full p-1">
								<Icon name="lucide:check" class="h-4 w-4" />
							</div>
							<div class="absolute bottom-0 left-0 right-0 bg-black/40 text-xs text-white px-2 py-1 truncate">
								{{ media.name }}
							</div>
						</div>
					</div>
					<Pagination
						v-if="totalPages > 1"
						:current-page="currentPage"
						:per-page="perPage"
						:total-items="totalItems"
						@update:current-page="(val: number) => { currentPage.value = val }"
						@update:per-page="(val: number) => { perPage.value = val }"
					/>
				</div>
        
				<!-- From Device Tab -->
				<div v-else>
					<!-- Pick from device button -->
					<button
						type="button"
						class="w-full py-3 bg-primary-600 hover:bg-primary-700 text-white font-medium rounded-md transition-colors mt-3"
						@click="() => deviceFileInput?.click()"
					>
						Pick from device & continue
					</button>
          
					<p class="text-sm text-gray-500 dark:text-gray-400 mt-2 mb-6">
						Maximum {{ MAX_FILES }} files allowed
					</p>
          
					<!-- Selected files list -->
					<div v-if="selectedFiles.length > 0" class="space-y-3 mb-6">
						<div
							v-for="(file, index) in selectedFiles"
							:key="index"
							class="flex items-center justify-between p-3 bg-gray-100 dark:bg-gray-800 rounded-lg"
						>
							<div class="flex items-center gap-3">
								<div class="flex-shrink-0">
									<Icon 
										:name="file.type === 'image' ? 'lucide:image' : 'lucide:video'" 
										class="h-6 w-6 text-gray-500 dark:text-gray-400" 
									/>
								</div>
								<div class="min-w-0">
									<p class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
										{{ file.name }}
									</p>
									<p class="text-xs text-gray-500 dark:text-gray-400">
										{{ formatFileSize(file.size) }}
									</p>
								</div>
							</div>
							<button
								type="button"
								class="text-gray-500 hover:text-red-500 dark:text-gray-400 dark:hover:text-red-400"
								@click="removeSelectedFile(index)"
							>
								<Icon name="lucide:x" class="h-5 w-5" />
							</button>
						</div>
					</div>
          
					<input
						ref="deviceFileInput"
						type="file"
						accept="image/*,video/*"
						multiple
						class="hidden"
						@change="onFilesSelected"
					/>
				</div>
			</div>
      
			<!-- Footer -->
			<div class="flex justify-end border-t border-gray-200 dark:border-gray-700 px-6 py-4 bg-gray-50 dark:bg-gray-800">
				<button
					type="button"
					class="px-6 py-2 bg-primary-600 hover:bg-primary-700 text-white font-medium rounded-md transition-colors"
					:disabled="!canProceed"
					:class="{'opacity-50 cursor-not-allowed': !canProceed}"
					@click="handleNext"
				>
					Next
				</button>
			</div>
		</div>

		<!-- Preview Modal -->
		<Teleport to="body">
			<MediaPreviewModal
				v-if="showPreviewModal"
				:is-open="showPreviewModal"
				:media-items="previewMediaItems"
				:current-index="previewCurrentIndex"
				:enable-video-edit="true"
				:show-edit="true"
				:show-next-button="true"
				:max-files="MAX_FILES"
				:is-uploading="isUploading"
				:upload-progress="uploadProgress"
				@close="closePreviewModal"
				@add-media="onAddMedia"
				@update:current-index="updatePreviewIndex"
				@next="handleBatchUpload"
			/>
		</Teleport>
	</Modal>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue';
import { useI18n } from 'vue-i18n';
import Modal from './Modal.vue';
import MediaPreviewModal from './MediaPreviewModal.vue';
import { createCreatorApi } from '@whispers/api';
import { useNotification } from '../../composables/useNotifications';
import Pagination from './Pagination.vue';

const props = defineProps<{ isOpen: boolean }>();

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'select', files: any[]): void
  (e: 'upload-complete', results: any[]): void
}>();

const { t } = useI18n();

interface MediaItem {
  id: string
  url: string
  name: string
  type: 'image' | 'video'
  size?: number
  duration?: number
  file?: File
}

const MAX_FILES = 10;

const tabs = [
  { key: 'library', label: 'mediaLibrary.tabLibrary' },
  { key: 'device', label: 'mediaLibrary.tabDevice' }
];
const activeTab = ref<'library' | 'device'>('device');
const loading = ref(false);
const mediaFiles = ref<MediaItem[]>([]);
const selectedIds = ref<string[]>([]);
const selectedFiles = ref<MediaItem[]>([]);
const deviceFileInput = ref<HTMLInputElement | null>(null);

// Preview modal state
const showPreviewModal = ref(false);
const previewFiles = ref<File[]>([]);
const previewCurrentIndex = ref(0);
const isUploading = ref(false);
const uploadProgress = ref({ completed: 0, total: 0 });

const notification = useNotification();

// Pagination state
const currentPage = ref(1);
const perPage = ref(10);
const totalItems = ref(0);
const totalPages = ref(1);

async function fetchMediaFiles() {
  loading.value = true;
  try {
    const creatorApi = createCreatorApi();
    const response = await creatorApi.getMediaFiles({ 
      page: currentPage.value.toString(), 
      limit: perPage.value.toString() 
    });
    mediaFiles.value = (response.mediaFiles || []).map((file: any) => ({
      id: file._id,
      url: file.url,
      name: file.url.split('/').pop() || 'media',
      type: file.type,
      size: file.size,
      duration: file.duration
    }));
    totalItems.value = response.pagination?.total || 0;
    totalPages.value = response.pagination?.pages || 1;
  } catch (error) {
    notification.error(t('notifications.contentLoadFailed'));
    mediaFiles.value = [];
  } finally {
    loading.value = false;
  }
}

onMounted(fetchMediaFiles);

watch([currentPage, perPage], fetchMediaFiles);

watch(() => props.isOpen, (isOpen: boolean) => {
  if (isOpen) {
    selectedIds.value = [];
    selectedFiles.value = [];
    previewFiles.value = [];
    loading.value = false;
    isUploading.value = false;
    uploadProgress.value = { completed: 0, total: 0 };
  }
});

const filteredMedia = computed(() => mediaFiles.value);

const canProceed = computed(() => {
  if (activeTab.value === 'library') {
    return selectedIds.value.length > 0;
  } else {
    return selectedFiles.value.length > 0;
  }
});

const previewMediaItems = computed(() =>
  previewFiles.value.map((file: File, index: number) => ({
    id: `preview-${index}`,
    url: URL.createObjectURL(file),
    name: file.name,
    type: file.type.startsWith('image/') ? 'image' : 'video',
    file
  }))
);

function toggleSelect(media: MediaItem) {
  const index = selectedIds.value.indexOf(media.id);
  if (index > -1) {
    selectedIds.value.splice(index, 1);
  } else {
    selectedIds.value.push(media.id);
  }
}

function onFilesSelected(event: Event) {
  const input = event.target as HTMLInputElement;
  if (!input.files || input.files.length === 0) return;

  const files = Array.from(input.files);
  const remainingSlots = MAX_FILES - selectedFiles.value.length;

  if (remainingSlots <= 0) {
    notification.error(`Maximum ${MAX_FILES} files allowed`);
    return;
  }

  const filesToAdd = files.slice(0, remainingSlots).map((file) => {
    const mediaItem = {
      id: `selected-${Date.now()}-${Math.random()}`,
      url: URL.createObjectURL(file),
      name: file.name,
      type: file.type.startsWith('image/') ? 'image' : 'video',
      size: file.size,
      file
    };
    selectedFiles.value.push(mediaItem);
    return file;
  });

  previewFiles.value = [...previewFiles.value, ...filesToAdd];
  previewCurrentIndex.value = Math.max(0, previewFiles.value.length - filesToAdd.length);
  showPreviewModal.value = true;

  if (deviceFileInput.value) {
    deviceFileInput.value.value = '';
  }
}

function removeSelectedFile(index: number) {
  const file = selectedFiles.value[index];
  if (file.url.startsWith('blob:')) {
    URL.revokeObjectURL(file.url);
  }
  selectedFiles.value.splice(index, 1);
  
  // Also remove from previewFiles if it exists there
  const previewIndex = previewFiles.value.findIndex(f => 
    file.file ? f === file.file : f.name === file.name
  );
  if (previewIndex > -1) {
    previewFiles.value.splice(previewIndex, 1);
  }
}

function updatePreviewIndex(newIndex: number) {
  previewCurrentIndex.value = newIndex;
}

async function onAddMedia(files: File[]) {
  if (!files || files.length === 0) return;
  
  const remainingSlots = MAX_FILES - previewFiles.value.length;
  if (remainingSlots <= 0) {
    notification.error(`Maximum ${MAX_FILES} files allowed`);
    return;
  }
  
  const filesToAdd = files.slice(0, remainingSlots);
  if (filesToAdd.length < files.length) {
    notification.warning(`Only ${filesToAdd.length} files added. Maximum ${MAX_FILES} files allowed.`);
  }
  
  // Add to both preview and selected files
  filesToAdd.forEach(file => {
    const mediaItem = {
      id: `selected-${Date.now()}-${Math.random()}`,
      url: URL.createObjectURL(file),
      name: file.name,
      type: file.type.startsWith('image/') ? 'image' : 'video',
      size: file.size,
      file
    };
    selectedFiles.value.push(mediaItem);
  });
  
  previewFiles.value = [...previewFiles.value, ...filesToAdd];
}

function dataURLtoFile(dataurl: string, filename: string): File {
  const arr = dataurl.split(',');
  const mimeMatch = arr[0].match(/:(.*?);/);
  const mime = mimeMatch ? mimeMatch[1] : 'image/jpeg';
  const bstr = atob(arr[1]);
  let n = bstr.length;
  const u8arr = new Uint8Array(n);
  while (n--) u8arr[n] = bstr.charCodeAt(n);
  return new File([u8arr], filename, { type: mime });
}

// Update the handleBatchUpload function
async function handleBatchUpload(mediaData: any[]) {
  if (mediaData.length === 0) return;

  isUploading.value = true;
  uploadProgress.value = { completed: 0, total: mediaData.length };

  try {
    // 1. Upload covers for videos first, if needed
    const coverUploads: Record<number, string> = {};
    await Promise.all(mediaData.map(async (media, i) => {
      const file = media.file || media.originalData?.file;
      const fileType = file?.type?.startsWith('video') || media.type === 'video' ? 'video' : 'image';
      if (fileType === 'video' && media.cover) {
        let coverFile: File | null = null;
        if (media.cover instanceof File) {
          coverFile = media.cover;
        } else if (typeof media.cover === 'string' && media.cover.startsWith('data:')) {
          const uuid = crypto.randomUUID();
          const coverFileName = `${uuid}.jpg`;
          coverFile = dataURLtoFile(media.cover, coverFileName);
        }
        if (coverFile) {
          // Get a pre-signed URL for the cover upload
          const creatorApi = createCreatorApi();
          const coverPayload = {
            files: [{
              uuid: crypto.randomUUID(),
              fileName: coverFile.name,
              fileType: 'image',
              size: coverFile.size
            }]
          };
          const coverResp = await creatorApi.uploadMediaFile(coverPayload);
          const coverUploadUrl = Array.isArray(coverResp)
            ? coverResp[0]?.uploadUrl
            : coverResp.uploadUrl;
          const coverFileName = Array.isArray(coverResp)
            ? coverResp[0]?.fileName
            : coverResp.fileName;
          if (coverUploadUrl && coverFileName) {
            await fetch(coverUploadUrl, {
              method: 'PUT',
              body: coverFile,
              headers: { 'Content-Type': coverFile.type },
            });
            coverUploads[i] = coverFileName;
          }
        }
      }
    }));

    // 2. Prepare the main payload for videos/images
    const payload = {
      files: mediaData.map((media, i) => {
        const file = media.file || media.originalData?.file;
        const fileType = file?.type?.startsWith('video') || media.type === 'video' ? 'video' : 'image';
        const filePayload: any = {
          uuid: crypto.randomUUID(),
          fileName: file?.name || media.name,
          fileType,
          size: file?.size || 0
        };
        if (fileType === 'video' && coverUploads[i]) {
          filePayload.coverName = coverUploads[i];
        }
        return filePayload;
      })
    };

    // 3. Get pre-signed URLs for main files (call uploadMediaFile ONCE)
    const response = await createCreatorApi().uploadMediaFile(payload);
    const uploadResponses = Array.isArray(response)
      ? response
      : Array.isArray(response.data)
        ? response.data
        : [response];

    // 4. Upload each file to S3 using the returned uploadUrl
    await Promise.all(
      uploadResponses.map(async (res: any, i: number) => {
        if (!res.uploadUrl) {
          console.error('Missing uploadUrl for file', i, res);
          return;
        }
        const fileToUpload = mediaData[i].file || mediaData[i].originalData?.file;
        if (!fileToUpload) {
          console.error('No file to upload for item', i);
          return;
        }
        await fetch(res.uploadUrl, {
          method: 'PUT',
          body: fileToUpload,
          headers: { 'Content-Type': fileToUpload.type },
        });
        uploadProgress.value.completed++;
      })
    );

    // 5. Add uploaded files to selectedFiles and clear preview
    const uploadedFiles = uploadResponses.map((res: any, i: number) => ({
      id: res.mediaFileId,
      url: res.fileUrl,
      name: mediaData[i].name,
      type: mediaData[i].type.startsWith('image/') ? 'image' : 'video',
      size: mediaData[i].file?.size || 0
    })).filter((f: any) => f.size > 0);

    notification.success(t('notifications.contentCreated'));
    await fetchMediaFiles();
    emit('upload-complete', uploadedFiles);
    selectedFiles.value = [
      ...selectedFiles.value,
      ...uploadedFiles
    ];
    previewFiles.value = [];
    showPreviewModal.value = false;
  } catch (error) {
    notification.error(t('notifications.mediaUploadFailed'));
    console.error('Upload failed:', error);
  } finally {
    isUploading.value = false;
  }
}

// Update the closePreviewModal function
function closePreviewModal() {
  // Clear all preview data
  previewMediaItems.value.forEach((item: any) => {
    URL.revokeObjectURL(item.url);
  });
  
  previewFiles.value = [];
  showPreviewModal.value = false;
  previewCurrentIndex.value = 0;
  
  // Don't clear selectedFiles here - let user keep their selection
}
function handleNext() {
  if (!canProceed.value) return;
  
  if (activeTab.value === 'library') {
    const selected = mediaFiles.value.filter((m: any) => selectedIds.value.includes(m.id));
    emit('select', selected);
  } else {
    emit('select', selectedFiles.value);
  }
  
  close();
}

function close() {
  // Clean up all blob URLs
  selectedFiles.value.forEach((file: any) => {
    if (file.url.startsWith('blob:')) {
      URL.revokeObjectURL(file.url);
    }
  });
  previewMediaItems.value.forEach((item: any) => {
    URL.revokeObjectURL(item.url);
  });
  selectedFiles.value = [];
  emit('close');
}

function formatFileSize(bytes?: number): string {
  if (!bytes) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function formatDuration(seconds?: number): string {
  if (!seconds) return '0:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

onUnmounted(() => {
  // Final cleanup
  selectedFiles.value.forEach((file: any) => {
    if (file.url.startsWith('blob:')) {
      URL.revokeObjectURL(file.url);
    }
  });
  
  previewMediaItems.value.forEach((item: any) => {
    URL.revokeObjectURL(item.url);
  });
});
</script>

// apps/creator-next-app/components/home/media-gallery.tsx
'use client'

import { useState, useEffect, useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { Upload, Folder } from 'lucide-react'
import { Dialog, DialogContent } from '@/components/ui/dialog'
import { toast } from 'sonner'
import MediaGalleryHeader from './media-gallery-header'
import MediaTabs from './media-tabs'
import MediaLibraryTab from './media-library-tab'
import DeviceUploadTab from './device-upload-tab'
import MediaGalleryFooter from './media-gallery-footer'
import MediaPreviewModal from './media-preview-modal'
import { creatorApi } from '@/lib/creator/creator-api'

interface MediaItem {
	id: string
	url: string
	name: string
	type: 'image' | 'video'
	size?: number
	duration?: number
	file?: File
	thumbnailUrl?: string
	tempId?: string
}

interface MediaGalleryProps {
	isOpen: boolean
	onClose: () => void
	onSelect: (files: MediaItem[]) => void
	onUploadComplete: (results: MediaItem[]) => void
}

const MAX_FILES = 10

export default function MediaGallery({ isOpen, onClose, onSelect, onUploadComplete }: MediaGalleryProps) {
	const { t } = useTranslation()

	// Tab configuration
	const tabs = [
		{ key: 'device', label: 'Upload New', icon: <Upload className="w-5 h-5" /> },
		{ key: 'library', label: 'Media Library', icon: <Folder className="w-5 h-5" /> },
	]

	// State management
	const [activeTab, setActiveTab] = useState<'library' | 'device'>('device')
	const [activeMediaTab, setActiveMediaTab] = useState<'images' | 'videos' | 'all'>('images')
	const [loading, setLoading] = useState(false)
	const [mediaFiles, setMediaFiles] = useState<MediaItem[]>([])
	const [selectedIds, setSelectedIds] = useState<string[]>([])
	const [selectedFiles, setSelectedFiles] = useState<MediaItem[]>([])
	const [searchQuery, setSearchQuery] = useState('')

	// Preview modal state
	const [showPreviewModal, setShowPreviewModal] = useState(false)
	const [previewFiles, setPreviewFiles] = useState<File[]>([])
	const [previewCurrentIndex, setPreviewCurrentIndex] = useState(0)
	const [isUploading, setIsUploading] = useState(false)
	const [uploadProgress, setUploadProgress] = useState({ completed: 0, total: 0 })

	// Pagination state
	const [currentPage, setCurrentPage] = useState(1)
	const [perPage, setPerPage] = useState(12)
	const [totalItems, setTotalItems] = useState(0)
	const [totalPages, setTotalPages] = useState(1)

	// Fetch media files from API
	const fetchMediaFiles = async () => {
		setLoading(true)
		try {
			const params: any = {
				page: currentPage.toString(),
				limit: perPage.toString(),
				search: searchQuery,
			}

			if (activeMediaTab === 'images') {
				params.type = 'image'
			} else if (activeMediaTab === 'videos') {
				params.type = 'video'
			}

			const response = await creatorApi.getMediaFiles(params)

			const mediaFiles = (response.data.mediaFiles || []).map((file: any) => ({
				id: file._id,
				url: file.url,
				thumbnailUrl: file.type === 'video' ? file.coverUrl : file.thumbnailUrl || file.url,
				name: file.url.split('/').pop() || 'media',
				type: file.type,
				size: file.size,
				duration: file.duration,
			}))

			setMediaFiles(mediaFiles)
			setTotalItems(response.data.pagination?.total || 0)
			setTotalPages(response.data.pagination?.pages || 1)
		} catch (error) {
			console.log(error, 'error')
			toast.error(t('notifications.contentLoadFailed') || 'Failed to load media files')
			setMediaFiles([])
		} finally {
			setLoading(false)
		}
	}

	// Process file uploads
	const processUploads = async (mediaData: any[]) => {
		const filesPayload = mediaData.map((file) => {
			const payload: any = {
				uuid:
					file.uuid ||
					(typeof crypto !== 'undefined' && crypto.randomUUID
						? crypto.randomUUID()
						: Math.random().toString(36).substring(2, 15)),
				fileName: file.name,
				fileType: file.type === 'video' ? 'video' : 'image',
				size: file.size,
			}

			if (file.type === 'video' && file.coverFile) {
				payload.coverName = file.coverFile.name
			}

			return payload
		})

		const response = await creatorApi.uploadMediaFile({ files: filesPayload })
		const uploadResults = []

		for (let i = 0; i < response.data.length; i++) {
			const { uploadUrl, fileKey, mediaFileId, coverUploadUrl } = response.data[i]
			const fileObj = mediaData[i].file

			// Upload main file
			await fetch(uploadUrl, {
				method: 'PUT',
				body: fileObj,
				headers: {
					'Content-Type': fileObj.type,
				},
			})

			// Upload cover if exists
			if (coverUploadUrl && mediaData[i].coverFile) {
				await fetch(coverUploadUrl, {
					method: 'PUT',
					body: mediaData[i].coverFile,
					headers: {
						'Content-Type': mediaData[i].coverFile.type,
					},
				})
			}

			uploadResults.push({
				...response.data[i],
				fileKey,
				mediaFileId,
			})
		}

		return uploadResults
	}

	// Base64 to File conversion utility
	const base64ToFile = (base64: string, filename: string, mimeType?: string) => {
		const arr = base64.split(',')
		const match = arr[0].match(/:(.*?);/)
		const mime = mimeType || (match ? match[1] : '')
		const bstr = atob(arr[1])
		let n = bstr.length
		const u8arr = new Uint8Array(n)
		while (n--) {
			u8arr[n] = bstr.charCodeAt(n)
		}
		return new File([u8arr], filename, { type: mime })
	}

	// Effects
	useEffect(() => {
		if (isOpen) {
			fetchMediaFiles()
		}
	}, [isOpen])

	useEffect(() => {
		if (isOpen) {
			setSelectedIds([])
			setSelectedFiles([])
			setPreviewFiles([])
			setShowPreviewModal(false)
			setLoading(false)
			setIsUploading(false)
			setUploadProgress({ completed: 0, total: 0 })
			setSearchQuery('')
			fetchMediaFiles()
		}
	}, [isOpen])

	useEffect(() => {
		fetchMediaFiles()
	}, [currentPage, perPage, activeMediaTab, searchQuery])

	// Computed values
	const canProceed = useMemo(() => {
		if (activeTab === 'library') {
			return selectedIds.length > 0
		} else {
			return selectedFiles.length > 0
		}
	}, [activeTab, selectedIds.length, selectedFiles.length])

	const previewMediaItems = useMemo(
		() =>
			previewFiles.map((file, index) => ({
				id:
					(file as any)?._id ||
					(file as any)?.tempId ||
					(typeof crypto !== 'undefined' && crypto.randomUUID
						? crypto.randomUUID()
						: Math.random().toString(36).substring(2, 15)),
				url: URL.createObjectURL(file),
				name: file.name || (file as any)?.fileName,
				type: file.type.startsWith('image/') ? ('image' as const) : ('video' as const),
				file,
				tempId: (file as any)?.tempId,
			})),
		[previewFiles],
	)

	// Event handlers
	const toggleSelect = (media: MediaItem) => {
		setSelectedIds((prev) => {
			const index = prev.indexOf(media.id)
			if (index > -1) {
				return prev.filter((id) => id !== media.id)
			} else {
				return [...prev, media.id]
			}
		})
	}

	const onFilesSelected = (files: File[]) => {
		const remainingSlots = MAX_FILES - selectedFiles.length
		if (remainingSlots <= 0) {
			toast.error(`Maximum ${MAX_FILES} files allowed`)
			return
		}

		const filesToAdd = files.slice(0, remainingSlots).map((file) => {
			const tempId = `temp-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
			;(file as any).tempId = tempId

			const mediaItem: MediaItem = {
				id: (file as any)?._id || (file as any)?.mediaFileId || tempId,
				url: URL.createObjectURL(file),
				name: file.name || (file as any)?.fileName,
				type: file.type.startsWith('image/') ? 'image' : 'video',
				size: file.size,
				file,
				tempId,
			}
			return mediaItem
		})

		setSelectedFiles((prev) => [...prev, ...filesToAdd])
		setPreviewFiles((prev) => [...prev, ...filesToAdd.map((item) => item.file!)])
		setPreviewCurrentIndex(Math.max(0, previewFiles.length))
		setShowPreviewModal(true)
	}

	const removeSelectedFile = (index: number) => {
		const file = selectedFiles[index]
		if (!file) return

		if (file.url.startsWith('blob:')) {
			URL.revokeObjectURL(file.url)
		}

		setSelectedFiles((prev) => prev.filter((_, i) => i !== index))

		const previewIndex = previewFiles.findIndex((f) => {
			if (file.tempId && (f as any).tempId) {
				return (f as any).tempId === file.tempId
			}
			return f === file.file || f.name === file.name
		})

		if (previewIndex > -1) {
			setPreviewFiles((prev) => prev.filter((_, i) => i !== previewIndex))
		}

		setPreviewCurrentIndex((prev) => {
			if (prev >= previewFiles.length - 1 && previewFiles.length > 1) {
				return previewFiles.length - 2
			} else if (previewFiles.length <= 1) {
				return 0
			}
			return prev
		})
	}

	const updatePreviewIndex = (newIndex: number) => {
		setPreviewCurrentIndex(newIndex)
	}

	const onAddMedia = (files: File[]) => {
		if (!files || files.length === 0) return

		const remainingSlots = MAX_FILES - previewFiles.length
		if (remainingSlots <= 0) {
			toast.error(`Maximum ${MAX_FILES} files allowed`)
			return
		}

		const filesToAdd = files.slice(0, remainingSlots)
		if (filesToAdd.length < files.length) {
			toast.error(`Only ${filesToAdd.length} files added. Maximum ${MAX_FILES} files allowed.`)
		}

		filesToAdd.forEach((file) => {
			const tempId = `temp-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
			const mediaItem: MediaItem = {
				id: tempId,
				url: URL.createObjectURL(file),
				name: file.name || (file as any)?.fileName,
				type: file.type.startsWith('image/') ? 'image' : 'video',
				size: file.size,
				file,
				tempId,
			}
			setSelectedFiles((prev) => [...prev, mediaItem])
		})

		setPreviewFiles((prev) => [...prev, ...filesToAdd])
	}

	const closePreviewModal = () => {
		previewMediaItems.forEach((item) => {
			if (item.url.startsWith('blob:')) {
				URL.revokeObjectURL(item.url)
			}
		})

		setPreviewFiles([])
		setShowPreviewModal(false)
		setPreviewCurrentIndex(0)

		selectedFiles.forEach((file) => {
			if (file.url.startsWith('blob:')) {
				URL.revokeObjectURL(file.url)
			}
		})
		setSelectedFiles([])
	}

	const handleBatchUpload = async (mediaData: any[]) => {
		if (mediaData.length === 0) return

		// Convert base64 cover to File for videos
		mediaData.forEach((item) => {
			if (item.type === 'video' && item.cover && !item.coverFile) {
				const baseName = item.name ? item.name.replace(/\.[^/.]+$/, '') : `cover-${Date.now()}`
				const coverFileName = `${baseName}-cover.jpg`
				item.coverFile = base64ToFile(item.cover, coverFileName, 'image/jpeg')
			}
		})

		setIsUploading(true)
		setUploadProgress({ completed: 0, total: mediaData.length })

		try {
			const results = await processUploads(mediaData)

			const emittedResults = results.map((r, index) => {
				const original = mediaData[index]
				return {
					id: r.mediaFileId,
					name: original?.name,
					type: original?.type,
					url: r.fileUrl || r.url,
					thumbnailUrl: original?.type === 'image' ? r.fileUrl || r.url : undefined,
					coverUrl: original?.type === 'video' ? r.coverUrl : undefined,
				}
			})

			onUploadComplete(emittedResults)
			setPreviewFiles([])
			setShowPreviewModal(false)
			toast.success(t('notifications.mediaUploadSuccess') || 'Upload completed successfully!')
		} catch (error) {
			toast.error(t('notifications.mediaUploadFailed') || 'Upload failed. Please try again.')
		} finally {
			setIsUploading(false)
		}
	}

	const handleSearch = (query: string) => {
		setSearchQuery(query)
		setCurrentPage(1)
	}

	const handleNext = () => {
		if (!canProceed) return

		if (activeTab === 'library') {
			const selected = mediaFiles.filter((m) => selectedIds.includes(m.id))
			onSelect(selected)
		} else {
			if (selectedFiles.length === 0) {
				return
			}
			onSelect(selectedFiles)
		}
		handleClose()
	}

	const handleClose = () => {
		// Clean up all blob URLs
		selectedFiles.forEach((file) => {
			if (file.url.startsWith('blob:')) {
				URL.revokeObjectURL(file.url)
			}
		})
		previewMediaItems.forEach((item) => {
			if (item.url.startsWith('blob:')) {
				URL.revokeObjectURL(item.url)
			}
		})

		// Reset all state
		setSelectedFiles([])
		setSelectedIds([])
		setPreviewFiles([])
		setShowPreviewModal(false)

		onClose()
	}

	return (
		<>
			<Dialog open={isOpen} onOpenChange={handleClose}>
				<DialogContent className="max-w-6xl h-[80vh] p-0 overflow-hidden">
					<MediaGalleryHeader title={t('mediaLibrary.title') || 'Media Library'} />

					<div className="overflow-hidden">
						{/* Main Content */}
						<div className="flex flex-col h-[600px]">
							{/* Tab Navigation */}
							<MediaTabs activeTab={activeTab} tabs={tabs} onUpdateActiveTab={setActiveTab} />

							{/* Content Area */}
							<div className="flex-1 overflow-hidden">
								{/* Media Library Tab */}
								{activeTab === 'library' && (
									<MediaLibraryTab
										loading={loading}
										mediaFiles={mediaFiles}
										selectedIds={selectedIds}
										currentPage={currentPage}
										perPage={perPage}
										totalPages={totalPages}
										totalItems={totalItems}
										activeMediaTab={activeMediaTab}
										onUpdateActiveMediaTab={setActiveMediaTab}
										onUpdateCurrentPage={setCurrentPage}
										onUpdatePerPage={setPerPage}
										onToggleSelect={toggleSelect}
										onSearch={handleSearch}
									/>
								)}

								{/* Device Upload Tab */}
								{activeTab === 'device' && (
									<DeviceUploadTab
										selectedFiles={selectedFiles}
										maxFiles={MAX_FILES}
										onFilesSelected={onFilesSelected}
										onRemoveFile={removeSelectedFile}
									/>
								)}
							</div>

							{/* Footer */}
							<MediaGalleryFooter canProceed={canProceed} isUploading={isUploading} onNext={handleNext} />
						</div>
					</div>
				</DialogContent>
			</Dialog>

			{/* Preview Modal */}
			{showPreviewModal && (
				<MediaPreviewModal
					isOpen={showPreviewModal}
					mediaItems={previewMediaItems}
					currentIndex={previewCurrentIndex}
					enableVideoEdit={true}
					showEdit={true}
					showNextButton={true}
					maxFiles={MAX_FILES}
					isUploading={isUploading}
					uploadProgress={uploadProgress}
					onClose={closePreviewModal}
					onAddMedia={onAddMedia}
					onUpdateCurrentIndex={updatePreviewIndex}
					onNext={handleBatchUpload}
				/>
			)}
		</>
	)
}
