// apps/creator/pages/creator/content/new.vue
<template>
	<div class="max-w-6xl mx-auto">
		<Head>
			<Title>{{ $t('content.new.title') }} - Whispers</Title>
		</Head>

		<div class="mb-6">
			<div class="flex items-center">
				<NuxtLink to="/creator/content" class="mr-2 text-gray-500 dark:text-gray-200 hover:text-gray-700">
					<Icon name="lucide:arrow-left" class="h-5 w-5" />
				</NuxtLink>

				<h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">{{ $t('content.new.title') }}</h1>
			</div>

			<p class="mt-1 text-sm text-gray-500 dark:text-gray-200">{{ $t('content.new.description') }}</p>
		</div>

		<div class="bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
			<post-form
				:initial-values="post"
				:errors="errors"
				:loading="contentStore.loading"
				:min-schedule-date="minScheduleDate"
				@submit="handleSubmit"
				@draft="saveAsDraft"
				@cancel="() => router.push('/creator/content')"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
import { reactive, computed } from 'vue'
import { toast } from 'vue3-toastify'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useContentStore } from '../../../store/content'
import PostForm from '@/components/PostForm.vue'

const router = useRouter()
const contentStore = useContentStore()
const { t } = useI18n()

definePageMeta({
	middleware: ['auth'],
	layout: 'creator',
	meta: {
		requiresAuth: true,
		requiresCreator: true,
	},
})

interface PostFormData {
	title: string
	content: string
	visibility: 'public' | 'private' | 'premium'
	price: number
	mediaUrls: string[]
}

interface PostFormErrors {
	title: string
	content: string
	mediaFiles: string
	visibility: string
	price: string
	scheduledDate: string
}

const post = reactive<PostFormData>({
	title: '',
	content: '',
	visibility: 'public',
	price: 4.99,
	mediaUrls: [],
})

const errors = reactive<PostFormErrors>({
	title: '',
	content: '',
	mediaFiles: '',
	visibility: '',
	price: '',
	scheduledDate: '',
})

const minScheduleDate = computed<string>(() => {
	const date = new Date()
	date.setMinutes(date.getMinutes() + 10)
	return date.toISOString().slice(0, 16)
})

function validateForm(formData: PostFormData): boolean {
	let isValid = true
	Object.keys(errors).forEach((key) => {
		;(errors as any)[key] = ''
	})
	if (!formData.title || !formData.title.trim()) {
		errors.title = t('validation.required', { field: t('content.form.title') })
		isValid = false
	} else if (formData.title.length > 100) {
		errors.title = t('validation.maxLength', { field: t('content.form.title'), max: 100 })
		isValid = false
	}
	if (!formData.content || !formData.content.trim()) {
		errors.content = t('validation.required', { field: t('content.form.content') })
		isValid = false
	}
	if (formData.mediaUrls && formData.mediaUrls.length > 10) {
		errors.mediaFiles = t('validation.maxFiles', { max: 10 })
		isValid = false
	}
	if (formData.visibility === 'premium') {
		if (!formData.price) {
			errors.price = t('validation.required', { field: t('content.form.price') })
			isValid = false
		} else if (formData.price < 1 || formData.price > 100) {
			errors.price = t('validation.priceRange')
			isValid = false
		}
	}
	return isValid
}

async function handleSubmit(formData: PostFormData): Promise<void> {
	if (!validateForm(formData)) {
		toast.error(t('validation.fixErrors'))
		return
	}
	try {
		post.title = formData.title
		post.content = formData.content
		post.visibility = formData.visibility
		post.price = formData.price
		post.mediaUrls = formData.mediaUrls
		const postData = {
			...post,
			creatorId: '123', // This should come from the auth store
		}
		await contentStore.createPost(postData)
		toast.success(t('notifications.contentCreated'))
		router.push('/creator/content')
	} catch {
		toast.error(t('notifications.contentCreateFailed'))
	}
}

function saveAsDraft(formData: PostFormData): void {
	console.log(formData)
	toast.info(t('notifications.draftSaved'))
}
</script>

// apps/creator-next-app/app/(dashboard)/content/new/page.tsx
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Icons } from "@/components/ui/icons"
import { PostForm } from "@/components/content/post-form"
import { useCreateContent } from "@/lib/content/content-hooks"
import { useAuthStore } from "@/lib/auth-store"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import Link from "next/link"
import { useRouter } from "next/navigation"

export default function NewContentPage() {
  const { t } = useTranslation()
  const router = useRouter()
  const [isClient, setIsClient] = useState(false)
  const { isAuthenticated } = useAuthStore()
  const createMutation = useCreateContent()

  useEffect(() => {
    setIsClient(true)
  }, [])

  if (!isClient) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-96 bg-gray-200 dark:bg-gray-700 rounded"></div>
        </div>
      </div>
    )
  }

  if (!isAuthenticated()) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Please log in to create content
          </h2>
          <Button onClick={() => (window.location.href = "/auth")}>Go to Login</Button>
        </div>
      </div>
    )
  }

  const initialValues = {
    title: "",
    content: "",
    visibility: "public" as const,
    price: 4.99,
    mediaUrls: [],
  }

  const minScheduleDate = new Date()
  minScheduleDate.setMinutes(minScheduleDate.getMinutes() + 10)

  const handleSubmit = async (formData: any) => {
    createMutation.mutate(
      {
        title: formData.title,
        body: formData.body || formData.content,
        mediaFiles: formData.mediaFiles || [],
        visibility: formData.visibility,
        price: formData.visibility === "pay-to-view" ? formData.price : undefined,
        scheduledDate: formData.isScheduled ? formData.scheduledDate : undefined,
      },
      {
        onSuccess: () => {
          toast.success(t("notifications.contentCreated"))
          router.push("/content")
        },
        onError: () => {
          toast.error(t("notifications.contentCreateFailed"))
        },
      },
    )
  }

  const handleDraft = async (formData: any) => {
    createMutation.mutate(
      {
        title: formData.title || t("content.untitledDraft"),
        body: formData.body || formData.content || "",
        mediaFiles: formData.mediaFiles || [],
        visibility: formData.visibility || "public",
        price: formData.visibility === "pay-to-view" ? formData.price : undefined,
        isDraft: true,
      },
      {
        onSuccess: () => {
          toast.success(t("notifications.draftSaved"))
          router.push("/content")
        },
        onError: () => {
          toast.error(t("notifications.draftSaveFailed"))
        },
      },
    )
  }

  const handleCancel = () => {
    router.push("/content")
  }

  return (
    <div className="max-w-6xl mx-auto p-6">
      <div className="mb-6">
        <div className="flex items-center">
          <Link href="/content" className="mr-2 text-gray-500 dark:text-gray-200 hover:text-gray-700">
            <Icons.arrowLeft className="h-5 w-5" />
          </Link>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{t("content.new.title")}</h1>
        </div>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-200">{t("content.new.description")}</p>
      </div>

      <div className="bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
        <PostForm
          initialValues={initialValues}
          loading={createMutation.isPending}
          minScheduleDate={minScheduleDate.toISOString().slice(0, 16)}
          onSubmit={handleSubmit}
          onDraft={handleDraft}
          onCancel={handleCancel}
        />
      </div>
    </div>
  )
}
