// apps/creator-next-app/app/auth/page.tsx
"use client"

import { useEffect, Suspense } from "react"
import { useTranslation } from "react-i18next"
import { useRouter, useSearchParams } from "next/navigation"
import Image from "next/image"

import { useAuthStore } from "@/lib/auth-store"
import { useLogin } from "@/lib/api-hooks"
import OAuthLogin from "@/components/auth/OAuthLogin"

function LoginLogic() {
  const { t } = useTranslation("auth")
  const router = useRouter()
  const searchParams = useSearchParams()
  const { isAuthenticated } = useAuthStore()
  const loginMutation = useLogin()

  useEffect(() => {
    if (isAuthenticated()) {
      router.replace("/")
      return
    }

    const accessToken = searchParams.get("accessToken")
    const refreshToken = searchParams.get("refreshToken")

    if (accessToken) {
      loginMutation.mutate({ accessToken, refreshToken })
      router.replace("/auth", { scroll: false })
    }
  }, [isAuthenticated, router, searchParams, loginMutation])

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
      <div className="w-full max-w-md p-8 space-y-8 bg-white dark:bg-gray-800 rounded-lg shadow">
        <div className="flex flex-col items-center">
          <Image src="/logo.svg?width=48&height=48" alt="Logo" width={48} height={48} className="mb-2" />
          <h2 className="mt-2 text-center text-2xl font-bold text-gray-900 dark:text-gray-100">{t("auth.signInTitle")}</h2>
        </div>
        <OAuthLogin loading={loginMutation.isPending} />

        {loginMutation.isPending && <div className="text-center text-sm text-gray-600">{t("auth.processingLogin")}</div>}

        {loginMutation.error && (
          <div className="text-center text-sm text-red-600">
            {t("auth.loginFailed", { error: loginMutation.error.message })}
          </div>
        )}
      </div>
    </div>
  )
}

export default function AuthPage() {
  const { t } = useTranslation("common")

  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center">
          <div>{t("loading")}</div>
        </div>
      }
    >
      <LoginLogic />
    </Suspense>
  )
}

// apps/creator/pages/auth/index.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
    <div class="w-full max-w-md p-8 space-y-8 bg-white dark:bg-gray-800 rounded-lg shadow">
      <div class="flex flex-col items-center">
        <img src="/logo.svg" alt="Logo" class="h-12 w-12 mb-2" />
        <h2 class="mt-2 text-center text-2xl font-bold text-gray-900 dark:text-gray-100">{{ $t('auth.signInTitle') }}
        </h2>
      </div>
      <!-- TODO: Move the loading state to the button -->
      <div v-if="loading">{{ $t('common.loading') }}</div>
      <div v-else-if="error">{{ error }}</div>
      <div v-else>
        <OAuthLogin />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router';
import { onMounted, ref } from 'vue';
import { useAuthStore } from '../../store/auth';
import OAuthLogin from '@/components/auth/OAuthLogin.vue';
import { createAuthApi } from '@whispers/api';
import { useI18n } from 'vue-i18n';
import { useNotification } from '../../composables/useNotifications';

const { t } = useI18n()
const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const notification = useNotification();
const loading = ref(false);
const error = ref<string | null>(null);

onMounted(async () => {
  if (authStore.isAuthenticated) {
    await router.replace('/');
    return;
  }

  const { accessToken, refreshToken } = route.query;

  if (accessToken && typeof accessToken === 'string') {
    await router.replace({ path: route.path });

    loading.value = true;
    try {
      authStore.setTokens(accessToken, refreshToken);
      const authApi = createAuthApi(accessToken);
      const profile = await authApi.getProfile();
      authStore.setProfile(profile);
      notification.success(t('auth.loginSuccess'));
      await router.replace('/');
    } catch (e) {
      try {
        const authApi = createAuthApi();
        const { accessToken: newAccessToken } = await authApi.refreshToken(refreshToken);
        authStore.setTokens(newAccessToken, refreshToken);
        const profile = await authApi.getProfile();
        authStore.setProfile(profile);
        notification.success(t('auth.loginSuccess'));
        await router.replace('/');
      } catch (refreshError) {
        error.value = t('auth.authenticationFailed');
        notification.error(t('auth.authenticationFailed'));
        authStore.logout();
      }
    } finally {
      loading.value = false;
    }
  }
});
</script>
