// apps/creator/pages/apply/index.vue
<template>
  <div class="min-h-screen max-w-6xl mx-autox">

    <Head>
      <Title>Become a Creator - Creator Dashboard</Title>
    </Head>
    <div class="container mx-auto px-4 py-8">
      <div>
        <div class="text-left mb-8">
          <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">{{ t('nav.becomeCreator') }}</h1>
        </div>
        <div class="bg-white dark:bg-gray-900 rounded-xl shadow-sm overflow-hidden">
          <div class="p-6 sm:p-8">
            <ApplyForm />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import ApplyForm from '../../components/apply/ApplyForm.vue';
const { t } = useI18n();

definePageMeta({
  layout: 'creator',
  middleware: ['auth'],
  meta: {
    requiresAuth: true,
  },
});
</script>

// apps/creator-next-app/app/(dashboard)/apply/page.tsx
"use client"

import { useTranslation } from "react-i18next"
import { useEffect, useState } from "react"
import ApplyCreatorForm from "@/components/apply/apply-creator-form"

export default function ApplyPage() {
  const { t } = useTranslation()
  const [mounted, setMounted] = useState(false)

  // Prevent hydration mismatch by only rendering after mount
  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return (
      <div className="min-h-screen">
        <div className="container mx-auto px-4 py-8">
          <div>
            <div className="text-left mb-8">
              <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Become a Creator</h1>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-xl shadow-sm overflow-hidden">
              <div className="p-6 sm:p-8">
                <div className="flex items-center justify-center py-12">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 dark:border-gray-100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen">
      <div className="container mx-auto px-4 py-8">
        <div>
          <div className="text-left mb-8">
            <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
              {t("nav.becomeCreator", "Become a Creator")}
            </h1>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-xl shadow-sm overflow-hidden">
            <div className="p-6 sm:p-8">
              <ApplyCreatorForm />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
