// apps/creator/pages/creator/content/index.vue
<template>
  <div>
    <Head>
      <Title>Content Management - Whispers</Title>
    </Head>

    <div class="sm:flex sm:items-center sm:justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">Content Management</h1>
        <p class="mt-1 text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
          Create, edit, and manage your content.
        </p>
      </div>
      <div class="mt-4 sm:mt-0">
        <NuxtLink to="/creator/content/new" class="btn-primary">
          <Icon name="lucide:plus" class="mr-2 h-4 w-4" />
          Create New Post
        </NuxtLink>
      </div>
    </div>

    <!-- Filters -->
    <div class="mt-6 bg-white dark:bg-gray-900 rounded-lg shadow-sm p-4 sm:flex sm:items-center space-y-4 sm:space-y-0 sm:space-x-4">
      <div class="flex-1">
        <label for="search" class="sr-only">Search</label>
        <div class="relative rounded-md shadow-sm">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Icon name="lucide:search" class="h-5 w-5 text-gray-400" />
          </div>
          <input
            id="search"
            v-model="search"
            type="search"
            placeholder="Search content..."
            class="form-input pl-10"
          />
        </div>
      </div>
      <div class="w-full sm:w-auto">
        <select
          v-model="visibilityFilter"
          class="form-input"
        >
          <option value="">All Visibility</option>
          <option value="public">Public</option>
          <option value="subscribers">Subscribers Only</option>
          <option value="ppv">Pay-per-view</option>
        </select>
      </div>
      <div class="w-full sm:w-auto">
        <select
          v-model="sortBy"
          class="form-input"
        >
          <option value="newest">Newest First</option>
          <option value="oldest">Oldest First</option>
          <option value="popular">Most Popular</option>
        </select>
      </div>
    </div>

    <!-- Content table/list -->
    <div class="mt-6 bg-white dark:bg-gray-900 shadow-sm rounded-lg overflow-hidden">
      <div class="bg-gray-50 dark:bg-gray-800 px-4 py-3 border-b border-gray-200 dark:border-gray-700 text-xs font-medium text-gray-500 dark:text-gray-200 dark:text-gray-400 uppercase tracking-wider">
        Content List
      </div>

      <div v-if="loading" class="p-8 text-center">
        <Icon name="lucide:loader" class="h-8 w-8 mx-auto animate-spin text-primary-500" />
        <p class="mt-2 text-gray-500 dark:text-gray-200 dark:text-gray-400">Loading content...</p>
      </div>

      <div v-else-if="filteredPosts.length === 0" class="p-8 text-center">
        <Icon name="lucide:file-x" class="h-12 w-12 mx-auto text-gray-400 dark:text-gray-500 dark:text-gray-200" />
        <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-gray-100">No content found</h3>
        <p class="mt-1 text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
          {{ search ? 'Try adjusting your search or filters.' : 'Get started by creating your first post.' }}
        </p>
        <div class="mt-6">
          <NuxtLink to="/creator/content/new" class="btn-primary">
            <Icon name="lucide:plus" class="mr-2 h-4 w-4" />
            Create New Post
          </NuxtLink>
        </div>
      </div>

      <ul v-else class="divide-y divide-gray-200">
        <li v-for="post in filteredPosts" :key="post.id" class="hover:bg-gray-50 hover:dark:bg-gray-700">
          <div class="px-4 py-4 sm:px-6 flex items-center">
            <div class="w-16 h-16 flex-shrink-0 rounded overflow-hidden bg-gray-100 mr-4">
              <img
                v-if="post.mediaUrls && post.mediaUrls.length > 0"
                :src="post.mediaUrls[0]"
                :alt="post.title"
                class="w-full h-full object-cover"
              />
              <div v-else class="w-full h-full flex items-center justify-center text-gray-400">
                <Icon name="lucide:file" class="h-6 w-6" />
              </div>
            </div>
            
            <div class="min-w-0 flex-1">
              <div class="flex items-center">
                <h3 class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">{{ post.title }}</h3>
                <span 
                  v-if="post.visibility === 'subscribers'" 
                  class="ml-2 badge badge-primary"
                >
                  Subscribers
                </span>
                <span 
                  v-else-if="post.visibility === 'ppv'" 
                  class="ml-2 badge badge-secondary"
                >
                  Pay-per-view
                </span>
                <span 
                  v-else 
                  class="ml-2 badge badge-success"
                >
                  Public
                </span>
                <span 
                  v-if="post.scheduledFor" 
                  class="ml-2 badge badge-warning"
                >
                  Scheduled
                </span>
              </div>
              
              <div class="mt-1">
                <p class="text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400 truncate">
                  {{ truncateContent(post.content) }}
                </p>
              </div>
              
              <div class="mt-2 flex items-center text-xs text-gray-500 dark:text-gray-200 dark:text-gray-400 space-x-4">
                <span class="flex items-center">
                  <Icon name="lucide:calendar" class="h-4 w-4 mr-1" />
                  {{ formatDate(post.createdAt) }}
                </span>
                <span class="flex items-center">
                  <Icon name="lucide:heart" class="h-4 w-4 mr-1" />
                  {{ post.likes }}
                </span>
                <span class="flex items-center">
                  <Icon name="lucide:message-square" class="h-4 w-4 mr-1" />
                  {{ post.comments }}
                </span>
                <span v-if="post.price" class="flex items-center">
                  <Icon name="lucide:dollar-sign" class="h-4 w-4 mr-1" />
                  {{ post.price }}
                </span>
              </div>
            </div>
            
            <div class="ml-4 flex-shrink-0 flex space-x-2">
              <button
                class="p-2 text-gray-500 dark:text-gray-200 hover:text-primary-600 rounded-md hover:bg-gray-100"
                @click="editPost(post.id)"
              >
                <Icon name="lucide:pencil" class="h-5 w-5" />
                <span class="sr-only">Edit</span>
              </button>
              <button
                class="p-2 text-gray-500 dark:text-gray-200 hover:text-error-600 rounded-md hover:bg-gray-100"
                @click="confirmDelete(post.id)"
              >
                <Icon name="lucide:trash-2" class="h-5 w-5" />
                <span class="sr-only">Delete</span>
              </button>
            </div>
          </div>
        </li>
      </ul>
    </div>

    <!-- Delete confirmation modal -->
    <div v-if="showDeleteModal" class="fixed inset-0 z-50 overflow-y-auto">
      <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 transition-opacity">
          <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
        </div>
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen">&#8203;</span>
        <div class="inline-block align-bottom bg-white dark:bg-gray-900 rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
          <div class="bg-white dark:bg-gray-900 px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <div class="sm:flex sm:items-start">
              <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-error-100 sm:mx-0 sm:h-10 sm:w-10">
                <Icon name="lucide:alert-triangle" class="h-6 w-6 text-error-600" />
              </div>
              <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                <h3 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">
                  Delete Content
                </h3>
                <div class="mt-2">
                  <p class="text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
                    Are you sure you want to delete this content? This action cannot be undone.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
            <button
              @click="deletePost"
              class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-error-600 text-base font-medium text-white hover:bg-error-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-error-500 sm:ml-3 sm:w-auto sm:text-sm"
            >
              Delete
            </button>
            <button
              @click="showDeleteModal = false"
              class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white dark:bg-gray-900 text-base font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useContentStore } from '~/stores/content';
import { toast } from 'vue3-toastify'

definePageMeta({
  layout: 'creator',
  middleware: ['auth'],
  meta: {
    requiresAuth: true,
    requiresCreator: true
  }
});

const contentStore = useContentStore();

// State
const loading = ref(true);
const search = ref('');
const visibilityFilter = ref('');
const sortBy = ref('newest');
const showDeleteModal = ref(false);
const postToDelete = ref(null);

// Fetch posts on mount
onMounted(async () => {
  try {
    await contentStore.fetchPosts({ creatorId: '123' }); // In a real app, this would be the current user's ID
    loading.value = false;
  } catch (error) {
    toast.error('Failed to load content. Please try again.');
    loading.value = false;
  }
});

// Computed properties
const filteredPosts = computed(() => {
  let result = [...contentStore.posts];
  
  // Apply search filter
  if (search.value) {
    const searchLower = search.value.toLowerCase();
    result = result.filter(post => 
      post.title.toLowerCase().includes(searchLower) || 
      post.content.toLowerCase().includes(searchLower)
    );
  }
  
  // Apply visibility filter
  if (visibilityFilter.value) {
    result = result.filter(post => post.visibility === visibilityFilter.value);
  }
  
  // Apply sorting
  switch (sortBy.value) {
    case 'newest':
      result.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
      break;
    case 'oldest':
      result.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
      break;
    case 'popular':
      result.sort((a, b) => b.likes - a.likes);
      break;
  }
  
  return result;
});

// Methods
function truncateContent(content, length = 80) {
  if (content.length <= length) return content;
  return content.substring(0, length) + '...';
}

function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
}

function editPost(id) {
  navigateTo(`/creator/content/edit/${id}`);
}

function confirmDelete(id) {
  postToDelete.value = id;
  showDeleteModal.value = true;
}

async function deletePost() {
  if (!postToDelete.value) return;
  
  try {
    await contentStore.deletePost(postToDelete.value);
    toast.success('Content deleted successfully');
    showDeleteModal.value = false;
    postToDelete.value = null;
  } catch (error) {
    toast.error('Failed to delete content. Please try again.');
  }
}
</script>

// apps/creator-next-app/app/(dashboard)/content/page.tsx
"use client"

import { useState, useEffect, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Icons } from "@/components/ui/icons"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { useContent, useDeleteContent } from "@/lib/content/content-hooks"
import { useAuthStore } from "@/lib/auth/auth-store"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import Link from "next/link"

interface Content {
  id: string
  title: string
  description?: string
  body: string
  visibility: "public" | "private" | "premium"
  price?: number
  tags?: string[]
  status: "published" | "draft" | "scheduled"
  createdAt: string
  updatedAt: string
  scheduledDate?: string
  mediaFiles?: Array<{
    id: string
    url: string
    type: string
    name: string
  }>
}

export default function ContentManagementPage() {
  const { t } = useTranslation()
  const [isClient, setIsClient] = useState(false)
  const [search, setSearch] = useState("")
  const [visibilityFilter, setVisibilityFilter] = useState("all")
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [contentToDelete, setContentToDelete] = useState<Content | null>(null)
  const [page, setPage] = useState(1)
  const [limit, setLimit] = useState(10)

  const { isAuthenticated } = useAuthStore()

  const { data: content, isLoading: loading, error } = useContent()
  const deleteMutation = useDeleteContent()

  useEffect(() => {
    setIsClient(true)
  }, [])

  const filteredContent = useMemo(() => {
    if (!content) return []

    let result = [...content]

    // Apply search filter
    if (search.trim()) {
      const searchTerm = search.toLowerCase().trim()
      result = result.filter(
        (item) =>
          item.title?.toLowerCase().includes(searchTerm) ||
          item.description?.toLowerCase().includes(searchTerm) ||
          item.tags?.some((tag) => tag.toLowerCase().includes(searchTerm)),
      )
    }

    // Apply visibility filter
    if (visibilityFilter !== "all") {
      result = result.filter((item) => item.visibility === visibilityFilter)
    }

    return result
  }, [content, search, visibilityFilter])

  const paginatedContent = useMemo(() => {
    const start = (page - 1) * limit
    const end = start + limit
    return filteredContent.slice(start, end)
  }, [filteredContent, page, limit])

  const pagination = useMemo(() => {
    const total = filteredContent.length
    const pages = Math.ceil(total / limit)
    return {
      total,
      pages,
      currentPage: page,
      perPage: limit,
    }
  }, [filteredContent.length, page, limit])

  const handleEdit = (content: Content) => {
    window.location.href = `/content/edit/${content.id}`
  }

  const handleDelete = (content: Content) => {
    setContentToDelete(content)
    setShowDeleteModal(true)
  }

  const confirmDelete = async () => {
    if (!contentToDelete) return

    deleteMutation.mutate(contentToDelete.id, {
      onSuccess: () => {
        toast.success(t("notifications.contentDeleted"))
        setShowDeleteModal(false)
        setContentToDelete(null)
        // Reset to page 1 if current page becomes empty
        if (paginatedContent.length === 1 && page > 1) {
          setPage(1)
        }
      },
      onError: () => {
        toast.error(t("notifications.contentDeleteFailed"))
      },
    })
  }

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  const getStatusBadge = (status: string) => {
    const statusConfig = {
      published: { color: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200", label: "Published" },
      draft: { color: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200", label: "Draft" },
      scheduled: { color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200", label: "Scheduled" },
    }

    const config = statusConfig[status as keyof typeof statusConfig] || statusConfig.draft

    return (
      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.color}`}>
        {config.label}
      </span>
    )
  }

  const getVisibilityIcon = (visibility: string) => {
    switch (visibility) {
      case "public":
        return <Icons.globe className="h-4 w-4" />
      case "subscribers":
        return <Icons.users className="h-4 w-4" />
      case "premium":
        return <Icons.dollarSign className="h-4 w-4" />
      default:
        return <Icons.globe className="h-4 w-4" />
    }
  }

  if (!isClient) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded"></div>
        </div>
      </div>
    )
  }

  if (!isAuthenticated()) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Please log in to manage your content
          </h2>
          <Button onClick={() => (window.location.href = "/auth")}>Go to Login</Button>
        </div>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded"></div>
          <div className="space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-20 bg-gray-200 dark:bg-gray-700 rounded"></div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-red-600 mb-4">Failed to load content</h2>
          <Button onClick={() => window.location.reload()}>Retry</Button>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
      {/* Header Section */}
      <div className="flex flex-col space-y-4 sm:flex-row sm:items-center sm:justify-between sm:space-y-0 mb-6">
        <div className="flex-1 min-w-0">
          <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 dark:text-gray-100 truncate">
            {t("content.management.title")}
          </h1>
          <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{t("content.management.description")}</p>
        </div>
        <div className="flex-shrink-0">
          <Link href="/content/new">
            <Button className="w-full sm:w-auto flex items-center justify-center">
              <Icons.plus className="mr-2 h-4 w-4" />
              <span className="hidden sm:inline">{t("content.management.createNew")}</span>
              <span className="sm:hidden">{t("content.management.createNew")}</span>
            </Button>
          </Link>
        </div>
      </div>

      {/* Filters Section */}
      <div className="mb-6 flex flex-col sm:flex-row gap-4">
        <div className="flex-1">
          <Input
            placeholder={t("content.search.placeholder") || "Search content..."}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full"
          />
        </div>
        <div className="w-full sm:w-48">
          <Select value={visibilityFilter} onValueChange={setVisibilityFilter}>
            <SelectTrigger>
              <SelectValue placeholder="Filter by visibility" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Visibility</SelectItem>
              <SelectItem value="public">Public</SelectItem>
              <SelectItem value="subscribers">Subscribers Only</SelectItem>
              <SelectItem value="premium">Pay-to-view</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Content Table Section */}
      <div className="mb-6">
        <Card>
          <CardContent className="p-0">
            {paginatedContent.length === 0 ? (
              <div className="text-center py-12">
                <Icons.fileText className="h-12 w-12 mx-auto text-gray-400" />
                <h3 className="mt-2 text-lg font-medium text-gray-900 dark:text-gray-100">No content found</h3>
                <p className="mt-1 text-gray-500 dark:text-gray-400">
                  {search || visibilityFilter !== "all"
                    ? "Try adjusting your filters"
                    : "Get started by creating your first post"}
                </p>
                {!search && visibilityFilter === "all" && (
                  <Link href="/content/new">
                    <Button className="mt-4">Create New Content</Button>
                  </Link>
                )}
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                  <thead className="bg-gray-50 dark:bg-gray-800">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Content
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Visibility
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Status
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Date
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                    {paginatedContent.map((item) => (
                      <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-gray-800">
                        <td className="px-6 py-4">
                          <div className="flex items-center">
                            <div className="flex-shrink-0 h-10 w-10">
                              {item.mediaFiles && item.mediaFiles.length > 0 ? (
                                <img
                                  className="h-10 w-10 rounded-lg object-cover"
                                  src={item.mediaFiles[0].thumbnailUrl || "/placeholder.svg"}
                                  alt={item.title}
                                />
                              ) : (
                                <div className="h-10 w-10 rounded-lg bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
                                  <Icons.fileText className="h-5 w-5 text-gray-400" />
                                </div>
                              )}
                            </div>
                            <div className="ml-4">
                              <div className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate max-w-xs">
                                {item.title}
                              </div>
                              {item.description && (
                                <div className="text-sm text-gray-500 dark:text-gray-400 truncate max-w-xs">
                                  {item.description}
                                </div>
                              )}
                            </div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center">
                            {getVisibilityIcon(item.visibility)}
                            <span className="ml-2 text-sm text-gray-900 dark:text-gray-100 capitalize">
                              {item.visibility === "premium" ? `$${item.price}` : item.visibility}
                            </span>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">{getStatusBadge(item.status)}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                          {formatDate(item.createdAt)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <div className="flex items-center justify-end space-x-2">
                            <Button variant="ghost" size="sm" onClick={() => handleEdit(item)}>
                              <Icons.edit className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleDelete(item)}
                              className="text-red-600 hover:text-red-700"
                            >
                              <Icons.trash className="h-4 w-4" />
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Pagination Section */}
      {pagination.pages > 1 && (
        <div className="flex justify-center sm:justify-between items-center">
          <div className="flex items-center space-x-2">
            <Button variant="outline" size="sm" onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>
              <Icons.chevronLeft className="h-4 w-4" />
              Previous
            </Button>
            <span className="text-sm text-gray-700 dark:text-gray-300">
              Page {page} of {pagination.pages}
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setPage(Math.min(pagination.pages, page + 1))}
              disabled={page === pagination.pages}
            >
              Next
              <Icons.chevronRight className="h-4 w-4" />
            </Button>
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-sm text-gray-700 dark:text-gray-300">Show:</span>
            <Select value={limit.toString()} onValueChange={(value) => setLimit(Number(value))}>
              <SelectTrigger className="w-20">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="10">10</SelectItem>
                <SelectItem value="20">20</SelectItem>
                <SelectItem value="50">50</SelectItem>
                <SelectItem value="100">100</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      )}

      {/* Delete Modal */}
      <Dialog open={showDeleteModal} onOpenChange={setShowDeleteModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Content</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Are you sure you want to delete "{contentToDelete?.title}"? This action cannot be undone.
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteModal(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmDelete} disabled={deleteMutation.isPending}>
              {deleteMutation.isPending ? <Icons.spinner className="h-4 w-4 animate-spin mr-2" /> : null}
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
