// apps/creator/pages/content/index.vue
<template>
	<div class="max-w-6xl mx-auto">

		<Head>
			<Title>{{ t('content.management.title') }} - Whispers</Title>
		</Head>

		<div class="sm:flex sm:items-center sm:justify-between">
			<div>
				<h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">{{ $t('content.management.title') }}</h1>

				<p class="mt-1 text-sm text-gray-500 dark:text-gray-200 dark:text-gray-400">
					{{ $t('content.management.description') }}
				</p>
			</div>

			<div class="mt-4 sm:mt-0">
				<NuxtLink to="/content/new" class="btn-primary">
					<Icon name="lucide:plus" class="mr-2 h-4 w-4" /> {{ $t('content.management.createNew') }}
				</NuxtLink>
			</div>
		</div>

		<!-- Filters -->

		<div class="mt-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
			<div class="flex-1">
				<label for="search" class="sr-only">{{ $t('content.management.search.placeholder') }}</label>
				<div class="relative">
					<div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
						<Icon name="lucide:search" class="h-5 w-5 text-gray-400" aria-hidden="true" />
					</div>
					<DebouncedInput v-model="search" :placeholder="$t('content.management.search.placeholder')" class="pl-10" />
				</div>
			</div>

			<div class="flex items-center gap-4">
				<select
					v-model="visibilityFilter"
					class="block rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 dark:text-gray-100 dark:bg-gray-800 ring-1 ring-inset ring-gray-300 dark:ring-gray-700 focus:ring-1 focus:ring-primary-600 sm:text-sm sm:leading-6">
					<option value="all">{{ $t('content.management.filters.all') }}</option>
					<option value="public">{{ $t('content.management.filters.public') }}</option>
					<option value="subscribers">{{ $t('content.management.filters.private') }}</option>
					<option value="pay-to-view">{{ $t('content.management.filters.pay-to-view') }}</option>
				</select>
			</div>
		</div>

		<!-- Content table/list -->

		<div class="mt-8 flow-root">
			<SkeletonLoader v-if="loading" variant="table" :rows="6" height="4rem" class="mb-4" />
			<div v-else class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
				<div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
					<div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
						<table class="min-w-full divide-y divide-gray-300 dark:divide-gray-700">
							<thead class="bg-gray-50 dark:bg-gray-800">
								<tr>
									<th
										scope="col"
										class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 dark:text-gray-100 sm:pl-6">
										{{ $t('content.management.list.title') }}
									</th>
									<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-100">
										{{ $t('content.management.list.visibility') }}
									</th>
									<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-100">
										{{ $t('content.management.list.views') }}
									</th>
									<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-gray-100">
										{{ $t('content.management.list.date') }}
									</th>
									<th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
										<span class="sr-only">{{ $t('content.management.list.actions') }}</span>
									</th>
								</tr>
							</thead>
							<tbody class="divide-y divide-gray-200 dark:divide-gray-700 bg-white dark:bg-gray-900">
								<tr v-if="loading">
									<td colspan="5" class="px-3 py-4 text-sm text-gray-500 dark:text-gray-400 text-center">
										{{ $t('content.management.list.loading') }}
									</td>
								</tr>
								<tr v-else-if="filteredContent.length === 0">
									<td colspan="5" class="px-3 py-4 text-sm text-gray-500 dark:text-gray-400 text-center">
										{{ $t('content.management.list.noContent') }}
									</td>
								</tr>
								<template v-else>
									<tr v-for="item in filteredContent" :key="item._id" class="hover:bg-gray-50 dark:hover:bg-gray-800">
										<td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
											<div class="flex items-center gap-2">
												<div>
													<div class="font-medium text-gray-900 dark:text-gray-100">{{ item.title }}</div>
													<div class="text-gray-500 dark:text-gray-400">{{ item.body }}</div>
												</div>
											</div>
										</td>
										<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
											<span
												class="inline-flex items-center rounded-md px-2 py-1 text-xs font-medium" :class="{
													'bg-green-50 text-green-700 dark:bg-green-900/30 dark:text-green-400':
														item.visibility === 'public',
													'bg-yellow-50 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400':
														item.visibility === 'private',
													'bg-purple-50 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400':
														item.visibility === 'pay-to-view',
												}">
												{{ $t(`content.management.filters.${item.visibility}`) }}
											</span>
										</td>
										<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">{{
											item.metadata.views }}</td>
										<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
											{{ new Date(item.createdAt).toLocaleDateString() }}
										</td>
										<td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
											<div class="flex justify-end gap-2">
												<button
													class="text-primary-600 hover:text-primary-900 dark:text-primary-400 dark:hover:text-primary-300 p-1"
													:title="$t('content.management.list.edit')" @click="editContent(item)">
													<Icon name="lucide:pencil" class="h-5 w-5" />
												</button>
												<button
													class="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300 p-1"
													:title="$t('content.management.list.delete')" @click="confirmDelete(item)">
													<Icon name="lucide:trash-2" class="h-5 w-5" />
												</button>
											</div>
										</td>
									</tr>
								</template>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

		<Pagination
			v-if="pagination.pages > 1" :current-page="page" :per-page="limit" :total-items="pagination.total"
			:per-page-options="[10, 20, 50, 100]" :show-end-buttons="true" :show-per-page="true" :show-range="true"
			@update:current-page="val => { page = val }" @update:per-page="val => { limit = val }" />

		<!-- Delete Confirmation Modal -->
		<TransitionRoot appear :show="showDeleteModal" as="template">
			<Dialog as="div" class="relative z-10" @close="closeDeleteModal">
				<TransitionChild
					as="template" enter="duration-300 ease-out" enter-from="opacity-0" enter-to="opacity-100"
					leave="duration-200 ease-in" leave-from="opacity-100" leave-to="opacity-0">
					<div class="fixed inset-0 bg-black/25 dark:bg-black/40" />
				</TransitionChild>

				<div class="fixed inset-0 overflow-y-auto">
					<div class="flex min-h-full items-center justify-center p-4 text-center">
						<TransitionChild
							as="template" enter="duration-300 ease-out" enter-from="opacity-0 scale-95"
							enter-to="opacity-100 scale-100" leave="duration-200 ease-in" leave-from="opacity-100 scale-100"
							leave-to="opacity-0 scale-95">
							<DialogPanel
								class="w-full max-w-md transform overflow-hidden rounded-2xl bg-white dark:bg-gray-900 p-6 text-left align-middle shadow-xl transition-all">
								<DialogTitle as="h3" class="text-lg font-medium leading-6 text-gray-900 dark:text-gray-100">
									{{ $t('content.management.delete.title') }}
								</DialogTitle>
								<div class="mt-2">
									<p class="text-sm text-gray-500 dark:text-gray-400">
										{{ $t('content.management.delete.description') }}
									</p>
								</div>

								<div class="mt-4 flex justify-end space-x-3">
									<button
										type="button"
										class="inline-flex justify-center rounded-md border border-transparent bg-red-100 dark:bg-red-900/30 px-4 py-2 text-sm font-medium text-red-900 dark:text-red-400 hover:bg-red-200 dark:hover:bg-red-900/50 focus:outline-none focus-visible:ring-1 focus-visible:ring-red-500 focus-visible:ring-offset-2"
										@click="deleteContent">
										{{ $t('content.management.delete.confirm') }}
									</button>
									<button
										type="button"
										class="inline-flex justify-center rounded-md border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-none focus-visible:ring-1 focus-visible:ring-primary-500 focus-visible:ring-offset-2"
										@click="closeDeleteModal">
										{{ $t('content.management.delete.cancel') }}
									</button>
								</div>
							</DialogPanel>
						</TransitionChild>
					</div>
				</div>
			</Dialog>
		</TransitionRoot>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { Dialog, DialogPanel, DialogTitle, TransitionChild, TransitionRoot } from '@headlessui/vue';
import { useI18n } from 'vue-i18n';
import { useContentStore } from '../../store/content';
import type { Content } from '../../types/content';
import Pagination from '../../components/ui/Pagination.vue';
import DebouncedInput from '../../components/ui/DebouncedInput.vue';
import SkeletonLoader from '../../components/ui/SkeletonLoader.vue';
import { useNotification } from '../../composables/useNotifications';

definePageMeta({
  layout: 'creator',
  middleware: ['auth'],
});

const { t } = useI18n();
const contentStore = useContentStore();
const { success, error, info } = useNotification();

const loading = ref<boolean>(true);
const search = ref<string>('');
const visibilityFilter = ref<string>('all');
const showDeleteModal = ref<boolean>(false);
const contentToDelete = ref<Content | null>(null);
const page = ref(1);
const limit = ref(10);

const filteredContent = computed<Content[]>(() => {
  if (!contentStore.content || !Array.isArray(contentStore.content.posts)) return [];
  const result = [...contentStore.content.posts];
  return result;
});

function editContent(content: Content): void {
  navigateTo(`/content/edit/${content._id}`);
}

function confirmDelete(content: Content): void {
  contentToDelete.value = content;
  showDeleteModal.value = true;
}

function closeDeleteModal(): void {
  showDeleteModal.value = false;
  contentToDelete.value = null;
}

async function deleteContent(): Promise<void> {
  if (!contentToDelete.value) return;
  try {
    await contentStore.deleteContent(contentToDelete.value._id);
    success(t('notifications.contentDeleted'));
    closeDeleteModal();
  } catch (err) {
    error(t('notifications.contentDeleteFailed'));
  }
}

watch([page, limit, visibilityFilter, search], async () => {
  loading.value = true;
  try {
    await contentStore.fetchContent({
      page: page.value,
      limit: limit.value,
      ...(visibilityFilter.value !== 'all' && { visibility: visibilityFilter.value }),
      ...(search.value && { search: search.value })
    });
  } finally {
    loading.value = false;
  }
}, { immediate: true });

const pagination = computed(() => contentStore.content?.pagination || { page: 1, limit: 10, total: 0, pages: 1 });
</script>

// apps/creator-next-app/app/(dashboard)/content/page.tsx
"use client"

import { useState, useEffect, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Icons } from "@/components/ui/icons"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { useContent, useDeleteContent } from "@/lib/content/content-hooks"
import { useAuthStore } from "@/lib/auth/auth-store"
import { useTranslation } from "react-i18next"
import { toast } from "sonner"
import Link from "next/link"

interface Content {
  id: string
  title: string
  description?: string
  body: string
  visibility: "public" | "private" | "premium"
  price?: number
  tags?: string[]
  status: "published" | "draft" | "scheduled"
  createdAt: string
  updatedAt: string
  scheduledDate?: string
  mediaFiles?: Array<{
    id: string
    url: string
    type: string
    name: string
  }>
}

export default function ContentManagementPage() {
  const { t } = useTranslation()
  const [isClient, setIsClient] = useState(false)
  const [search, setSearch] = useState("")
  const [visibilityFilter, setVisibilityFilter] = useState("all")
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [contentToDelete, setContentToDelete] = useState<Content | null>(null)
  const [page, setPage] = useState(1)
  const [limit, setLimit] = useState(10)

  const { isAuthenticated } = useAuthStore()

  const { data: content, isLoading: loading, error } = useContent()
  const deleteMutation = useDeleteContent()

  useEffect(() => {
    setIsClient(true)
  }, [])

  const filteredContent = useMemo(() => {
    if (!content) return []

    let result = [...content]

    // Apply search filter
    if (search.trim()) {
      const searchTerm = search.toLowerCase().trim()
      result = result.filter(
        (item) =>
          item.title?.toLowerCase().includes(searchTerm) ||
          item.description?.toLowerCase().includes(searchTerm) ||
          item.tags?.some((tag) => tag.toLowerCase().includes(searchTerm)),
      )
    }

    // Apply visibility filter
    if (visibilityFilter !== "all") {
      result = result.filter((item) => item.visibility === visibilityFilter)
    }

    return result
  }, [content, search, visibilityFilter])

  const paginatedContent = useMemo(() => {
    const start = (page - 1) * limit
    const end = start + limit
    return filteredContent.slice(start, end)
  }, [filteredContent, page, limit])

  const pagination = useMemo(() => {
    const total = filteredContent.length
    const pages = Math.ceil(total / limit)
    return {
      total,
      pages,
      currentPage: page,
      perPage: limit,
    }
  }, [filteredContent.length, page, limit])

  const handleEdit = (content: Content) => {
    window.location.href = `/content/edit/${content.id}`
  }

  const handleDelete = (content: Content) => {
    setContentToDelete(content)
    setShowDeleteModal(true)
  }

  const confirmDelete = async () => {
    if (!contentToDelete) return

    deleteMutation.mutate(contentToDelete.id, {
      onSuccess: () => {
        toast.success(t("notifications.contentDeleted"))
        setShowDeleteModal(false)
        setContentToDelete(null)
        // Reset to page 1 if current page becomes empty
        if (paginatedContent.length === 1 && page > 1) {
          setPage(1)
        }
      },
      onError: () => {
        toast.error(t("notifications.contentDeleteFailed"))
      },
    })
  }

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  const getStatusBadge = (status: string) => {
    const statusConfig = {
      published: { color: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200", label: "Published" },
      draft: { color: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200", label: "Draft" },
      scheduled: { color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200", label: "Scheduled" },
    }

    const config = statusConfig[status as keyof typeof statusConfig] || statusConfig.draft

    return (
      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.color}`}>
        {config.label}
      </span>
    )
  }

  const getVisibilityIcon = (visibility: string) => {
    switch (visibility) {
      case "public":
        return <Icons.globe className="h-4 w-4" />
      case "subscribers":
        return <Icons.users className="h-4 w-4" />
      case "premium":
        return <Icons.dollarSign className="h-4 w-4" />
      default:
        return <Icons.globe className="h-4 w-4" />
    }
  }

  if (!isClient) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded"></div>
        </div>
      </div>
    )
  }

  if (!isAuthenticated()) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Please log in to manage your content
          </h2>
          <Button onClick={() => (window.location.href = "/auth")}>Go to Login</Button>
        </div>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-1/4"></div>
          <div className="h-32 bg-gray-200 dark:bg-gray-700 rounded"></div>
          <div className="space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-20 bg-gray-200 dark:bg-gray-700 rounded"></div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-red-600 mb-4">Failed to load content</h2>
          <Button onClick={() => window.location.reload()}>Retry</Button>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-6xl mx-auto p-4 sm:p-6 lg:p-8">
      {/* Header Section */}
      <div className="flex flex-col space-y-4 sm:flex-row sm:items-center sm:justify-between sm:space-y-0 mb-6">
        <div className="flex-1 min-w-0">
          <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 dark:text-gray-100 truncate">
            {t("content.management.title")}
          </h1>
          <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{t("content.management.description")}</p>
        </div>
        <div className="flex-shrink-0">
          <Link href="/content/new">
            <Button className="w-full sm:w-auto flex items-center justify-center">
              <Icons.plus className="mr-2 h-4 w-4" />
              <span className="hidden sm:inline">{t("content.management.createNew")}</span>
              <span className="sm:hidden">{t("content.management.createNew")}</span>
            </Button>
          </Link>
        </div>
      </div>

      {/* Filters Section */}
      <div className="mb-6 flex flex-col sm:flex-row gap-4">
        <div className="flex-1">
          <Input
            placeholder={t("content.search.placeholder") || "Search content..."}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full"
          />
        </div>
        <div className="w-full sm:w-48">
          <Select value={visibilityFilter} onValueChange={setVisibilityFilter}>
            <SelectTrigger>
              <SelectValue placeholder="Filter by visibility" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Visibility</SelectItem>
              <SelectItem value="public">Public</SelectItem>
              <SelectItem value="subscribers">Subscribers Only</SelectItem>
              <SelectItem value="premium">Pay-to-view</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Content Table Section */}
      <div className="mb-6">
        <Card>
          <CardContent className="p-0">
            {paginatedContent.length === 0 ? (
              <div className="text-center py-12">
                <Icons.fileText className="h-12 w-12 mx-auto text-gray-400" />
                <h3 className="mt-2 text-lg font-medium text-gray-900 dark:text-gray-100">No content found</h3>
                <p className="mt-1 text-gray-500 dark:text-gray-400">
                  {search || visibilityFilter !== "all"
                    ? "Try adjusting your filters"
                    : "Get started by creating your first post"}
                </p>
                {!search && visibilityFilter === "all" && (
                  <Link href="/content/new">
                    <Button className="mt-4">Create New Content</Button>
                  </Link>
                )}
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                  <thead className="bg-gray-50 dark:bg-gray-800">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Content
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Visibility
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Status
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Date
                      </th>
                      <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                    {paginatedContent.map((item) => (
                      <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-gray-800">
                        <td className="px-6 py-4">
                          <div className="flex items-center">
                            <div className="flex-shrink-0 h-10 w-10">
                              {item.mediaFiles && item.mediaFiles.length > 0 ? (
                                <img
                                  className="h-10 w-10 rounded-lg object-cover"
                                  src={item.mediaFiles[0].thumbnailUrl || "/placeholder.svg"}
                                  alt={item.title}
                                />
                              ) : (
                                <div className="h-10 w-10 rounded-lg bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
                                  <Icons.fileText className="h-5 w-5 text-gray-400" />
                                </div>
                              )}
                            </div>
                            <div className="ml-4">
                              <div className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate max-w-xs">
                                {item.title}
                              </div>
                              {item.description && (
                                <div className="text-sm text-gray-500 dark:text-gray-400 truncate max-w-xs">
                                  {item.description}
                                </div>
                              )}
                            </div>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex items-center">
                            {getVisibilityIcon(item.visibility)}
                            <span className="ml-2 text-sm text-gray-900 dark:text-gray-100 capitalize">
                              {item.visibility === "premium" ? `$${item.price}` : item.visibility}
                            </span>
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">{getStatusBadge(item.status)}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                          {formatDate(item.createdAt)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <div className="flex items-center justify-end space-x-2">
                            <Button variant="ghost" size="sm" onClick={() => handleEdit(item)}>
                              <Icons.edit className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleDelete(item)}
                              className="text-red-600 hover:text-red-700"
                            >
                              <Icons.trash className="h-4 w-4" />
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Pagination Section */}
      {pagination.pages > 1 && (
        <div className="flex justify-center sm:justify-between items-center">
          <div className="flex items-center space-x-2">
            <Button variant="outline" size="sm" onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>
              <Icons.chevronLeft className="h-4 w-4" />
              Previous
            </Button>
            <span className="text-sm text-gray-700 dark:text-gray-300">
              Page {page} of {pagination.pages}
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setPage(Math.min(pagination.pages, page + 1))}
              disabled={page === pagination.pages}
            >
              Next
              <Icons.chevronRight className="h-4 w-4" />
            </Button>
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-sm text-gray-700 dark:text-gray-300">Show:</span>
            <Select value={limit.toString()} onValueChange={(value) => setLimit(Number(value))}>
              <SelectTrigger className="w-20">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="10">10</SelectItem>
                <SelectItem value="20">20</SelectItem>
                <SelectItem value="50">50</SelectItem>
                <SelectItem value="100">100</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      )}

      {/* Delete Modal */}
      <Dialog open={showDeleteModal} onOpenChange={setShowDeleteModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Content</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Are you sure you want to delete "{contentToDelete?.title}"? This action cannot be undone.
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteModal(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmDelete} disabled={deleteMutation.isPending}>
              {deleteMutation.isPending ? <Icons.spinner className="h-4 w-4 animate-spin mr-2" /> : null}
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
